### ISSUE TITLE
Feature Request: Auto-save draft

### ISSUE THREAD

**Issue by martec** [samclarke/SCEditor#130]
I will be very thankful if possible create this feature.

**Comment by scooley5200** [comment]
Just lost hours of work!  

Is there an auto-save draft feature at work in the back ground yet? 

It would be really great if I could recover my work where I'd not yet pressed the "Submit new issue button"?

**Comment by scooley5200** [comment]
Not Lazarus.

Susan F. Cooley

System Administrator
Career Academy of Real Estate
CareerAcademyOfRealEstate.com
