### ISSUE TITLE
resize window create problem for invisible editor page

### ISSUE THREAD

**Issue by imansa** [samclarke/SCEditor#156]
when the editor is not visible ( style of one of parent nodes has `display:none;` ) `handleWindowResize()` function will be fired with window resize and change editor size to something like `width:100px; height:0px;`. it can be correct with something like this one

``` javascript
handleWindowResize = function() {
    var tmp=base.getContentAreaContainer();
    if(typeof tmp[0]!='undefined') {
        if(!$(tmp[0]).is(':visible')) {
            return;
        }
    }
.
.
.
};
```

i am using Google Chrome Version 22.0.1229.94
and my initialize options are

``` javascript
$textarea.sceditor({
    height:'99%',
    width:'100%',
    resizeEnabled:false,
    autoUpdate:true
});
```

**Comment by samclarke** [comment]
Closing as already fixed by 24959709f94c3a31b173b0247e03c65f66c0ea81
