### ISSUE TITLE
Get the editor's content in another container.

### ISSUE THREAD

**Issue by Crapoto** [samclarke/SCEditor#157]
Hi ! I'm new to GitHub and also new on javascript coding, so be gentle with my newbie question :)

What i want to do, is to have the "source" content displayed in another textarea.
Only the text content, as this textarea will be "readonly", the visitors will not be allowed to edit content there .. Its just a 'preview' of the BBcode output.

I know there is a editor view switch that can be used to modify BBcode within the editor, but i did something like that;

$(document).ready(function() {
    var initEditor = function() {
        $("#editor").sceditor({
            plugins: 'bbcode',  
        });
    };
    initEditor();
    $('#editor').sceditor('instance').bind('blur', function(e) {
        document.getElementById("text").value = $('#editor').sceditor('instance').val();
    });
});

where "text" is a <textarea id="text"></textarea>  somewhere outside the editor.

It works, exept that then, when i change a line example i set the size of a title from [size=7] to [size=5], using the adapted size button in the toolbar, i get the following line:

[size=7][size=5]Harry Potter et la chambre des secrets[/size][/size]

But when i do not use "document.getElementById("text").value = $('#editor').sceditor('instance').val();", i get the correct output:
[size=5]Harry Potter et la chambre des secrets[/size]

What's wrong ?

Thanks in advance for the help, i'll keep learning with this really great tool !

**Comment by samclarke** [comment]
Closing as needs info
