### ISSUE TITLE
Forced focus on editor's iframe

### ISSUE THREAD

**Issue by parsadev** [samclarke/SCEditor#175]
hi
i am using Google Chrome Version 22.0.1229.94.
when i create a new instance of editor **init() function** force focus to editor iframe by openning iframe **ducument** object. i use inspect element for running line by line and visit **doc.close();** code in **init()** function is reason of this event.
when size of editor iframe is bigger than page size by some conditions this focus change page layout in chrome.

**Comment by samclarke** [comment]
Closing as needs info
