### ISSUE TITLE
BBcode Code issue in WYSIWYG mode

### ISSUE THREAD

**Issue by zied2** [samclarke/SCEditor#219]
Hello,

I have found 2 issues in WYSIWYG mode:

1/ When clicking on the code button and in the code area in use ctrl+v, the code block is removed.

2/ When pasting a content at the end of a code block, the code block is duplicated with the new content.

I use Firefox 23.0.1 with Windows vista as OS.

I want to thank you for this great work.

**Comment by samclarke** [comment]
Thanks for reporting! Closing as this looks to have been fixed a while ago.
