### ISSUE TITLE
Sceditor Instance .blur is triggered during toolbar selection on Chrome.

### ISSUE THREAD

**Issue by mcornetto** [samclarke/SCEditor#233]
Blur for the entire control is not triggered on IE if the control's toolbar is clicked but it is triggered in Chrome.  This causes an issue if your trying to do cross browser code using this event.   It should work one way or the other on both browsers.  Thanks.

**Comment by samclarke** [comment]
The blur event works consistently everywhere other than IE which prevents it to fix some selection bugs. It is reporting it accurately though, IE hasn't lost focus so there is no blur event.

It might be possible to fake the event in IE but it wouldn't really have lost focus which would probably be lest consistent than the current behaviour.
