### ISSUE TITLE
SCEditor does not set proper width / height when initialized hidden

### ISSUE THREAD

**Issue by rbu** [samclarke/SCEditor#276]
I have tried initializing a textarea within a div that was not visible (display none), due to a collapsible edit form. As the site uses a variable width, so does the SCEditor:
```
        $textarea.sceditor({
...
          "width": "77%",
          "resizeWidth": false
        })
```

Unfortunately, while the outer width (on sceditor-container) is applied correctly, the inner width (on the wysiwygEditor iframe) is set to an incorrect fixed value. This is due to a code path that tries to determine a pixel width from a relative width and which fails because jQuery cannot be relied upon to return any meaningful value when asking for the width of an invisible element,
SCEditor really should avoid calculating widths when initalized with non-integer values.

**Comment by joechilds** [comment]
Ignore the 94cb0f7 PR - I'd forgotten to check tab/space styling and my editor converted them automatically. 27b4f4b is the fixed PR which fixes this issue in my use-case and should fix in most situations I think.

**Comment by Frozen-byte** [comment]
I can confirm this bug.
Applied 'width: 100%' and the textbox is dynamically loaded via AJAX.
Same error occurs.
Musters commit (nor his repo) fixes this error.
