### ISSUE TITLE
Kindly help me in sceditor for my forum with forumotion.com

### ISSUE THREAD

**Issue by ramgp01** [samclarke/SCEditor#296]
This is Ram,

I am not strong knowledge in JavaScript.

We have a Tamil language forum got from forumotion.com. Forumotion now upgraded old editor to new Sceditor for all his forums.

Old editor textarea has a id attribute like "text_editor_textarea", we have using Google Tamil indic web version so worked perfectly. 

But in Sceditor the textarea has no such id attribute, so that we can't type in Tamil or any other languages(Except English).

How to assign id attribute to that textarea? or any other way to use google tamil indic in this sceditor?

Time being we are using Google Input Tools Desktop version 

Google indic web version JavaScript code given below: 
http://amarkkalam.com/Tools/tamileditor.html

<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<link href="http://www.google.com/uds/modules/elements/transliteration/api.css" type="text/css" rel="stylesheet">

<script type="text/javascript">
google.load("elements", "1", {
            packages: "transliteration"          });
      function onLoad() {
        var options = {
          sourceLanguage: 'en',
          destinationLanguage: ['ta'], 
          shortcutKey: 'alt+g',
          transliterationEnabled: true        };
             var control =
            new google.elements.transliteration.TransliterationControl(options);
        var ids = ["text_editor_textarea" ];
        control.makeTransliteratable(ids);
        control.showControl('translControl');      }
      google.setOnLoadCallback(onLoad);
    </script>

We also giving demo user id and password 

Site name: http://www.amarkkalam.net/login
Username: demo123
Password: [removed]

Screenshot: http://i.stack.imgur.com/Txsjw.jpg

Kindly help us. 

Warm Regards & Thanks 
Ram

**Comment by ramgp01** [comment]
Dear Mr. @samclarke,

Kindly refer [above ](https://github.com/samclarke/SCEditor/issues/296) thread. 

New browsers not support Tamil Languages (destinationLanguage: ['ta'],) 

If possible, kindly resolve this issue. 

And one more thing microphone add to textarea possible?

Warm Regards & Thanks!
Ram

Tag: @brunoais

**Comment by brunoais** [comment]
@ramgp01 Please make a new issue and... Expect quite some wait from @samclarke ... Dunno if he will ever answer.
