### ISSUE TITLE
AutoUpdate option prevents tab key from functioning properly (IE9 - IE11)

### ISSUE THREAD

**Issue by vikkoboy** [samclarke/SCEditor#301]
A problem with IE9 - IE11:
It is impossible to navigate away from the editor with tab key once it has gained focus If AutoUpdate is set to "true". We have some visually impaired or blind users who use screen readers, such as JAWS, and do not use mouse. They use tab key to navigate on the page and if they end up in a sceditor they will be stuck in it if AutoUpdate is on.

**Comment by samclarke** [comment]
Closing as needs info.
