### ISSUE TITLE
default <p> enclosure lost after deleting the content in editor

### ISSUE THREAD

**Issue by Tinja** [samclarke/SCEditor#305]
I just got the editor hooked up and I liked it very much!

One issue that I noticed though, please see the below for repros. If it's not by design, and if it's an easy fix, would you please help out or let me know the possible code changes needed? So I can do a quick fix on my copy of the code. 

Repro steps - using xhtml plugin

A
1. type letter 'a'
2. call API to get value using val(), and it returns `<p>a</p>`
3. delete the letter 'a'
4. call API to get value using val(), and it returns '' (an empty string)
5. type letter 'a' again
6. call API to get value using val(), and it returns 'a', basically the `'<p>'` enclosure is lost.

B
1. type letter 'a'
2. call API to get value using val(), and it returns `<p>a</p>`
3. hit enter
4. call API to get value using val(), and it returns `<p> a</p><p>    <br /></p>`
5. delete the letter 'a'
6. call API to get value using val(), and it returns '' (an empty string)
7. hit enter
8. call API to get value using val(), and it returns `<div>   <br /></div><div>   <br /></div>`

Thanks a lot! This is such a great editor, really appreciated!

**Comment by samclarke** [comment]
This has already been fixed so closing. Thanks for reporting!
