### ISSUE TITLE
Scrolling broken in iOS7

### ISSUE THREAD

**Issue by asgallant** [samclarke/SCEditor#312]
Scrolling the text box does not function correctly in iOS7.  Most of the time, attempting to scroll the text box scrolls the page instead.  Some vanishingly small percentage of scroll attempts result in the text box scrolling, but it is usually slow and choppy.

This is reproducible using the example editor on the sceditor.com home page, using an iPad 3 with iOS 7.0.4.

**Comment by samclarke** [comment]
Closing as needs info.
