### ISSUE TITLE
Create plain text pasting option

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#32]
Add an option to allow only plain text to be pasted into the WYSIWYG editor.

Would be a possible solution to #30

**Comment by OlafvdSpek** [comment]
+1, not having this is almost a showstopper..

> You can currently filter pasted text so that only formatting which has a valid BBCode equivalent will be kept by enabling the enablePasteFiltering option.

What happens if that's not enabled?
Is the formatting inserted as 'HTML'?

**Comment by OlafvdSpek** [comment]
Sam?

**Comment by samclarke** [comment]
@OlafvdSpek Oh sorry, I didn't see your question.

If it isn't enabled it will insert the HTML and then convert it when the form is submitted or the editor is switched to source mode. Paste filtering has been tested enough now so the next version will enable it by default as well as enabling pasting events so plain text pasting will finally be implemented.

**Comment by OlafvdSpek** [comment]
To what will it be converted?

**Comment by q2apro** [comment]
When will this option be available?

**Comment by danielocdh** [comment]
@berendiwema solution works nicely combined with enablePasteFiltering but it has issues, I noticed 2:
- You actually see the formated content pasted with format and then it looses its format
- Undo/redo gets broken

Hopefully an out of the box option can be added for future projects.
