### ISSUE TITLE
Tip: How to get all SCeditor instances

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#322]
I thought this might help some sceditor newbies: 

```
$("textarea").each( function() {
    var sceditorinst = $(this).sceditor("instance");
    if(typeof(sceditorinst) != 'undefined') {
        // output the content of each editor
        console.log( sceditorinst.val() );
    }
});
```

**Comment by Negroserias** [comment]
> That does not work well and that may override the window parameter. I think you are not teaching well there ;).
> 
> Also, what if there's no SCE on all textareas?

Your answer does not help
