### ISSUE TITLE
Link dialog: Allow links without http and create clean URL

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#326]
Having the SCEditor now in use at http://www.gute-mathe-fragen.de/ where there are 5000 - 10000 visitors per day - and replacing the CKEditor finally, thanks a lot (!) - I am getting great feedback of what usability problems SCEditor has. @samclarke: Congratulations, one year ago I stumbled over SCE. Now I have finally tweaked everything (plus your fixes), so it could go live.

One of the main problems is the link dialog: 
![capture](https://cloud.githubusercontent.com/assets/6764548/3847910/55f928f6-1e6a-11e4-99d0-5ed108ed8b14.PNG)

Some users just paste the link into this field, which causes two "http://" to appear. Thus, the link is not working. 

My suggestion: 
1. Leave the http:// out. No need!
2. Check the pasted link if it contains an "http://".
3. If not, add it to the link.

Additional issue: No one used the description field so far, how can i disable it without hacking the core files?

Edit: Also found the issue reported here: https://github.com/samclarke/SCEditor/issues/227

**Comment by q2apro** [comment]
The problem seems to be still there: 

When the user enters a link in the editor dialog like `www.mathegigant.de/` the output is: `<a href="`www.mathegigant.de/`">...` without the `http` - so the link will not work!

Please try to fix this issue, thank you.

**Comment by q2apro** [comment]
We actually need only to check, if `href="www` and then replace this part by `href="http://www`

**Comment by samclarke** [comment]
Auto focus was fixed in commit 3aa8d78fe86aec4524cda46828b6aa30965cf61e.

As adding `http://` to the start, that would prevent relative URLs from being inserted so couldn't really be done by default. The link command can be updated to do it so it's possible to do if relative URLs are not required.
