### ISSUE TITLE
Hitting Ctrl+A and deleting all text, then writing anew prevents p tags

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#331]
To reproduce: 
1. write "test" in sceditor (with html plugin, not bbcode)
2. hit `ctrl+a` to mark all text, hit `del` to remove all text
3. write something, hit `enter`, write next line, hit `enter`
4. see source (source button)
5. result: all line breaks are `<br />` and there are no `<p>` tags anymore.

Can this be solved?

Greetings :)
Kai

**Comment by q2apro** [comment]
Year 2016. This bug is still open. Can't there be a simple check as suggested above? And if empty, do 1. and 2. ?

**Comment by brunoais** [comment]
I'm working on that. I'm still stuck with 
https://bugzilla.mozilla.org/show_bug.cgi?id=1193517

**Comment by samclarke** [comment]
I've come up with a solution that I think works around the FF issue so should be fixed in V2.
