### ISSUE TITLE
Change font inside the iframe?

### ISSUE THREAD

**Issue by ghost** [samclarke/SCEditor#332]
Hi, 

I'm wondering if it's possible to change the font inside the iframe to one from Google Fonts (e.g. 'Open Sans')? I've tried to import the font at the top of the default.css (the stylesheet that my instance of sceditor uses):

```
@import url(http://fonts.googleapis.com/css?family=Open+Sans);
```

And then change the font of the iframe:

```
.sceditor-container iframe{
    font-family: 'Open Sans', sans-serif; !important
}
```

But that doesn't seem to work. :/

Thanks in advance,
RedRetro

**Comment by puroossosinistro** [comment]
I tryed your hint samclarke but doesn't work.

**Comment by puroossosinistro** [comment]
I have been searching on Github and in the documentation and I don't found anything about change the DEFAULT FONT-FAMILY or the list of SIZES (to PIXELS for example). Please, is there any solution for these situations?
