### ISSUE TITLE
Paste Event and Plain Text option

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#334]
We need to: 
1. have a plain text pasting option, which is not available for the HTML plugin now,
2. remove the color of the pasted text, this also using plain text option, or with a setting [see suggestion here](https://github.com/samclarke/SCEditor/issues/329)

With current version, only the BBCode plugin provides a plaintext paste feature. 

The request for a plaintext-feature is already from Nov 2012: https://github.com/samclarke/SCEditor/issues/32 - not implemented yet. 

I would like to implement it myself, however, I cannot find a **paste event** in the [sceditor docs](http://www.sceditor.com/api/sceditor/). 

To filter all HTML tags you can use jquery for this, here [an example](http://stackoverflow.com/a/2876633/1066234) how to clean word styles from the pasted content: 

```
function cleanWordPaste( in_word_text ) {
 var tmp = document.createElement("DIV");
 tmp.innerHTML = in_word_text;
 var newString = tmp.textContent||tmp.innerText;
 // this next piece converts line breaks into break tags
 // and removes the seemingly endless crap code
 newString  = newString.replace(/\n\n/g, "<br />").replace(/.*<!--.*-->/g,"");
 // this next piece removes any break tags (up to 10) at beginning
 for ( i=0; i<10; i++ ) {
  if ( newString.substr(0,6)=="<br />" ) { 
   newString = newString.replace("<br />", ""); 
  }
 }
 return newString;
}
```

Also helpful, how to [remove tags](http://stackoverflow.com/a/12110097/1066234): 

```
var removeElements = function(text, selector) {
    var wrapped = $("<div>" + text + "</div>");
    wrapped.find(selector).remove();
    return wrapped.html();
}
// USAGE
var removedSpanString = removeElements("<span>Some Text</span> Some other Text", "span");
```

---

And this is [another finding](http://codereview.stackexchange.com/a/26162), with plain Javascript used: 

```
// simply use a disposable DOM element to convert the HTML to plaintext:
var message = "..."; // Contains HTML markup
var tmp = document.createElement("DIV");
tmp.innerHTML = message;
var message = tmp.textContent||tmp.innerText;
// message now contains plaintext, and tmp can be disposed of
```

And this is [a regex](http://css-tricks.com/snippets/javascript/strip-html-tags-in-javascript/) that is supposed to clean all tags: 

```
var StrippedString = OriginalString.replace(/(<([^>]+)>)/ig,"");
```

---

Why am I so concerned? 

In my math forum people of course write answers in text editors and else where and copy paste them into sceditor. And sometimes they copy from sceditor within and paste text to the next line. Unfortunately, as soon as any color is in there (the evil - i already call it - bug `<span style="color: rgb(0, 0, 0);">`), the color gets pasted with the copied text (it will also hold span color black). 

Problem now: I am parsing my text with another javascript library that superscripts a^x to a<sup>x</sup>, however, having the span now inside breaks everything. This is what my users reported and what I have experienced too. 

---

Conclusion: 
So either we need a plaintext option or we unset the colors (i.e. remove the span tags) of the entire text when pasting.

**Comment by q2apro** [comment]
I really hope, @samclarke can find a quick solution here. There is too much *html tag noise* that gets produced.

**Comment by brunoais** [comment]
The text paste is already in the latest version.
All those repeated HTML tags is not specific to SCE and it is not easy to solve with fast code in a flawless fashion. All solutions I can think at the moment require doing work that can show itself as slow working.
Do you want me to try anyway?

**Comment by q2apro** [comment]
I think we could force kind of plain text for many cases. My "custom paste filter when I was using CKEditor" (see above) was quite efficient. Maybe this we can use as a starter?

**Comment by brunoais** [comment]
Why force it?

**Comment by KenorFR** [comment]
Hi,
You can juste add in SCeditor.js in function "handlePasteData()" before `rangeHelper.restoreRange();`
this : 

```
if (options.pasteTreatment !== null && typeof options.pasteTreatment === 'function') {
        pasteddata = options.pasteTreatment(pasteddata);
}

```

and add "pasteTreatment: null" in "defaultOptions.js"

Then, you can use : 
```

$textarea.sceditor({
      pasteTreatment: function(data) {
           // treatment data
           return data;
      }
});

```
