### ISSUE TITLE
IE10 text falls outside of table cells

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#338]
When you add a new table into a blank document and right away after adding it start typing then the text starts to appear outside any cell but text is still inside the table somehow. This is reproduceable in the SCEditor demo too.

![text_outside_tablecells](https://cloud.githubusercontent.com/assets/6572543/4232632/780ef79a-399f-11e4-9185-e8f3373b4619.png)

**Comment by samclarke** [comment]
Thanks for reporting. It should be fixed in 1.4.7 when it's released.
