### ISSUE TITLE
maximum content size option

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#339]
We in our company wish that we could tell SCEditor the maximum amount input user can put into the editor.

Maybe you could have a cached bbcode string in the SCEditor instances which you could update when the content changes so that checking the length would be very fast.

At the moment we use the valuechanged callback and check the length ourselves but this gets very slow with long documents. Especially when using IE, in other browsers the performance is acceptable.

**Comment by samclarke** [comment]
Closing as isn't much else that can be done about this.
