### ISSUE TITLE
Formatting of custom self-closing BBCode tags

### ISSUE THREAD

**Issue by rnilsen75** [samclarke/SCEditor#355]
Hi,
I have an issue where I am unable to apply e.g. bold to a custom BBCode tag in the WYSIWYG editor in IE8-11. The custom tag is impemented as a span, one of many available merge fields, like "Sender name". In BBCode this will simply be [sender_name]. In WYSIWYG mode, If I mark more then that custom tag and hit bold, it will first apply bold to the prefix text, then apply bold to the inner text of the span (Sender name), and then apply bold to the suffix text. 
When converted to BBCode, since the tag [sender_name] has no content and is self closing, the bold will be gone. The result could be:
```
[b]Some text before [/b][sender_name][b] and some text after.[/b]
```
However, if I edit it in source mode and manually do [b][sender_name][/b] it works. But this is not so easy to explain this to the end users. It seems to be working fine in Chrome and Firefox, but being an enterprise application, IE dominates as target browser.

This is the BBCode object I use (I reuse the same on multiple different merge fields). The fields variable is just hoding a list of all the merge fields with a tag, like [sender_name] and a label, "Sender name":

```javascript
	var mergeFieldBBCodeFormatter =
		{
			tags : { 'span' : { 'class' : ['bbcode-mergefield'], '_field' : null } },
			
			format:  
				function(element, content)
				{
					var field = element.attr("_field");
				
					return '[' + field + ']';
				}, 

			html: 
				function(token, attrs, content)
				{
					var fields = TextEditPlugin.currentTextEdit.mergeFields;
					var label = token.name;
					
					for (var i = 0; i < fields.length; i++)
					{
						if (fields[i].tag == token.name)
						{
							label = fields[i].label;
							break;
						}
					}
				
					return '<span class="bbcode-mergefield" _field="' + token.name + '">' + label + '</span>';
				},
				
			isSelfClosing: true,
			allowsEmpty: true,
			excludeClosing: true,
			allowedChildren: null
			
		};
```

I would appreciate any help on how to solve this, if even possible. I tried a lot of different combinations, both in type of HTML tag to represent it (a, div, quote etc.) and different options to the BBCode object.
As a side note, I see that IE7 is not working well at all when it comes to custom tags, and on some occasions I run into issues with IE and text range within the SCEditor script. But I can report that separately when I see it again.

**Comment by brunoais** [comment]
Closing as unanswered for too long
