### ISSUE TITLE
Copy/Paste Undo editor bug

### ISSUE THREAD

**Issue by martec** [samclarke/SCEditor#357]
Original Post: http://community.mybb.com/thread-158872.html

Copy and paste something, paste it in to your editor. Continue typing. Then control+Z back so the editor is empty. What you pasted will stay regardless of it's place. 

Steps to reproduce:

Type sentence.

Copy this post and paste it into your post.

Attempt to undo.

I've not tried any other browsers or OS.

Windows 7, Chrome Version 37.0.2062.103.

Thank you.

https://www.youtube.com/watch?v=TroE9Edwzhc

**Comment by samclarke** [comment]
Closing as this is fixed by undo plugin.
