### ISSUE TITLE
SUB bug: When subbing and then un-subbing, sub is still active

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#360]
Obviously there is a bug when unsubbing in certain situations, please see videoclip:

![vorschau](https://cloud.githubusercontent.com/assets/6764548/4959406/1771edde-66b8-11e4-86ce-96e761833660.gif)

The HTML that was shown after clicking the source button - from the test above: 

	<p>
		Test per Maus: x<sub>1</sub> = richtig
	</p>
	<p>
		x<sub>2 = falsch</sub> = war noch mal geklickt
	</p>
	<p>
		x<sub>3</sub> = richtig
	</p>
	<p>
		Nun per Tastatuturkürzel: x4 -- geht nicht mehr. Jap, ein Bug....<br />
	</p>

With another test, I had always the subbing in the last line, that was the HTML source: 

	<p>
		 x<sub>1</sub> = test 
	</p>
	 
	<p>
		 x<sub>1</sub> = test 
	</p>
	 
	<p>
		 x<sub>2 = test</sub> 
	</p>
	 
	<p>
		 <br /> 
	</p>

Even though, there is only a `<br />` element in the end, it sub'ed the input in the new line. However, when loading the editor anew and pasting the HTML directly in source mode, and then writing into the last line, the sub was gone. 

Cannot understand where the bug is coming from. 

System: Win 7, Firefox 33.0.3

**Comment by q2apro** [comment]
I think I found the source of the problem. 

I am using a preview field below the editor. To enable the preview I use some extra code: 

	$('textarea[name=\"".$fieldname."\"]').sceditor('instance').keyUp(function(e) {
		doPreview();
	});

	function doPreview() {
		delay(function(){
			edcontent = $('textarea[name=\"".$fieldname."\"]').sceditor('instance').val();
			// only render if value has changed
			if(edcontent == edcontent_former) {
				return;
			}
			
			edcontent_former = edcontent;
			
			// assign to preview
			$('#textpreview_".$fieldname."').html( edcontent );
			
		}, 600 ); // end delay function
	} // end doPreview

	// jquery keyup() delay
	var delay = ( function() {
		var timer = 0;
		return function(callback, ms) {
			clearTimeout (timer);
			timer = setTimeout(callback, ms);
		};
	})();

I assume somehow the delay function interferes with the buttons of SCEditor.

@samclarke Maybe you can think of something?

**Comment by brunoais** [comment]
Does it seem correct if you remove the delay?
Try using other values for the delay: 10ms, 100ms, 400ms, 1000ms, 2000ms.
Does it still happen on those delays?
Make a function return after SCE's .val() (your preview will stop working). Does the issue continue?

**Comment by q2apro** [comment]
I have solved it by setting the delay from `600` to `1500`.

**Comment by brunoais** [comment]
A return after this:
`edcontent = $('textarea[name="test"]').sceditor('instance').val();`

**Comment by brunoais** [comment]
That was the objective. To see if it was breaking before it tried the preview

**Comment by samclarke** [comment]
@q2apro could you check this fixes your issue? It fixes it for me but as it's quite tricky to reproduce I just want to make sure it's the same issue.

**Comment by q2apro** [comment]
@samclarke Could you provide the fully built jquery.sceditor.xhtml.min.js ? I am not using Grunt, I am using the available production files on.y

**Comment by samclarke** [comment]
@q2apro I've uploaded it [here](https://dl.dropboxusercontent.com/u/56830471/jquery.sceditor.xhtml.min.js).

**Comment by q2apro** [comment]
![vorschau](https://cloud.githubusercontent.com/assets/6764548/7088548/2751646a-df9d-11e4-9e3f-9905fec01bf6.gif)

:+1:
