### ISSUE TITLE
IE table cell text formatting issue - Bug

### ISSUE THREAD

**Issue by AlbertPraveen** [samclarke/SCEditor#378]
Add new table.
Type some text inside the cell.
Select the text using mouse not by double click.
Try to format the text.
This happens only in IE. Mozilla and chrome works fine. 
This seems the selection range is not proper in IE.

**Comment by jetand** [comment]
I think this is the same issue we noticed in our company. Here https://github.com/samclarke/SCEditor/issues/337

**Comment by AlbertPraveen** [comment]
Hi I found another scenario related to this issue which happens only in IE

Type some text inside the cell.
Select the text using mouse not by double click.
After selection click somewhere else inside the editor.
Try to format the text. It formats the previous selection even though nothing is selected.

**Comment by samclarke** [comment]
Thanks for reporting. It should be fixed in 1.4.7 when it's released.
