### ISSUE TITLE
Paste image from clipboard (Chrome) - Firefox and IE works fine

### ISSUE THREAD

**Issue by richardsonvix** [samclarke/SCEditor#386]
It´s possible paste an image directly from clipboard???

In the worst case paste from Word (argh!).

Thanks.

**Comment by CylonSK** [comment]
probably not, because it has to be uploaded somewhere first

**Comment by brunoais** [comment]
That's not SCE's work. That's the work of an uploading code.
Some editors include such thing but SCE doesn't and I think that's for best. It prevents it from becoming a bloat.

**Comment by richardsonvix** [comment]
I did some further testing ...

In Firefox and IE you can paste an image, it will be embedded in the HTML converted to a string in base64 in the IMG tag.

In Chrome it does not work. There is some type of lock that after I paste a picture nothing happens.

But I got around this problem by intercepting the "paste" and doing the same image conversion to base64.

**Comment by brunoais** [comment]
That's the browser's implementation. There's no reason to block it :).

**Comment by richardsonvix** [comment]
Yes, I thought so too, if it works in a browser work at all.

Not SCEditor's fault, I saw in all WYSIWYG editors the same problem.
The characteristic is that IE and FF paste image, but not in Chrome.

I will summarize, Internet Explorer and Firefox, when I paste an image from the clipboard it will generate an embedded image with base64 encoding (ex .: <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAB4AAAAQ4CAIAAABnsVYUAAAgAElEQVR4nOydeVxO6f//z/fz+fxmo+y7GWNpQSmULUv...), Chrome nothing happens.

We're going to a famous editor, http://ckeditor.com/demo, try to capture the screen (printscreen or otherwise) and then paste the image in Chrome, will not work, try now in Firefox, work, try Internet Explorer, also work. ;)
Do the same on www.sceditor.com and see the same behavior.

As I adopted SCEditor I integrated a solution as explained before. I could even modify it to upload the pasted image and then embed the IMG tag with the URL of the image on the server, but this is not the default behavior for other browsers.

If you search a bit you will see that it is a fact there is a problem of image paste in Chrome.

**Comment by samclarke** [comment]
It's possible to make Chrome behave the same way via the clipboard API: http://jsfiddle.net/6yocdszm/

I'm planning to improve the paste support so I could normalise this behaviour when I do that. It might be useful as a way of allowing images to be uploaded by pasting.

**Comment by richardsonvix** [comment]
Very nice post, Sam.

Thank you.

**Comment by brunoais** [comment]
@samclarke Looks nice, then. I can't wait to see it working.
On another note. Is it possible to try checking the current dev for bugs? I think it is about time to release another stable version.
I'm not sure but I feel like that the current dev version is stable to be considered stable but I think some extra testing should be made to make sure of that.

**Comment by samclarke** [comment]
@brunoais Yes I'm testing it right now.

**Comment by richardsonvix** [comment]
I´ve test in Chrome, Firefox and IE, and works fine.

**Comment by odungern** [comment]
If you permit that we participate in the discussion: 

Pasting an image from the clipboard to HTML is a very nice idea, but in our case we would not allow it, except for very small icons, perhaps. 

We are planning to offer a new action with a modal dialog letting a user select an image (or any other) file from the disk, upload it and insert `<a href=".."><object src=".." >title</object></a>` into the SCEditor area. Even nicer to offer some drag'n'drop like in GitHub and other applications, but one step after the other ;-).

No changes to SCEditor are needed for this approach, as far as we can see, now.

**Comment by odungern** [comment]
I just saw #391 ... it is just the same approach we are envisioning ... we would only use the option to upload the file.

**Comment by brunoais** [comment]
I still believe that file uploading is not an editor's job. At worst case, it can be a plugin.
But still, if people become happy with just the code sam suggested, I accept it.

**Comment by odungern** [comment]
Bruno, absolutely: we would upload the file with some other library (we are using jQuery-File-Upload already for uploading templates containing a project's data-model) .. and others may opt for something else.

**Comment by samclarke** [comment]
@odungern the plan is to add a paste event which will normalise the paste behaviour across all browsers (most embed the image), then you can filter the pasted data how you wish. Strip images, strip any formatting, etc.

The plan with the drag and drop plugin is it will extract any pasted images and create an event with the image data. It will also do the same for files dropped onto the editor. It's then up to the event handler to upload or discard them.

@brunoais it won't be uploading the file, just providing an event which says someone pasted something and normalising the behaviour. Even the planned drag & drop plugin will only create an an event saying a file has been pasted/dropped, it won't actually do any uploading as that's way out of scope and would require server side code.

**Comment by dandv** [comment]
Whether it's the editor's job or not, the fact is that [most editors](http://socialcompare.com/en/comparison/javascript-online-rich-text-editors) do handle pasting images from clipboard.

Also, [Summernote](http://summernote.org) includes the image encoded in the HTML, so the developer doesn't have to deal with the upload/storage.

**Comment by brunoais** [comment]
@samclarke Sounds OK to me. It shouldn't require much code so I'm perfectly fine.
@dandv Just because they do, it doesn't mean all should do. IMO, that's bloat, ultimately. It is also one major reason why I don't like using CKE. Too much damn bloat.

**Comment by odungern** [comment]
I agree with @brunoais - image upload is not the responsibility of an editor. The editor is part of the view and the uploader is part of the controller (in MVC terms), so don't mix it.
@samclarke original proposal to just normalize the event sounds optimal to me. Different projects may have different needs for the uploading process as servers differ. Perhaps a coding example would help developers to implement a fully functional solution with both image upload and text insertion.

**Comment by odungern** [comment]
By the way, the html-section to insert the image in the text must be easy to adapt. Some projects may have preference to take an image tag and others an object tag; some must add a css-class to influence the rendering, which is the case with us.  
We are happy to share the results of our investigation on the cross-browser rendering of PNG, JPG, SVG and PDF. Did cost us a couple of days ...

**Comment by brunoais** [comment]
Not only that, Some may even require it as BBCode while others don't want anything uploaded but text (either encoded or not)
