### ISSUE TITLE
Adding of extra line breaks each time you switch between WYSIWYG / Source windows

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#388]
Doing some more testing with SCEditor and noticed that it strangely adds another line break to a number of areas each time you switch between the WYSIWYG editor and the source window.

It doesn't seem to affect every single situation, but many.... check the example images:

![sceditor1](https://cloud.githubusercontent.com/assets/9627036/6372992/bba36a14-bd42-11e4-8e1f-b2b7f43e023e.png)
![sceditor2](https://cloud.githubusercontent.com/assets/9627036/6372999/c2aa9d96-bd42-11e4-89aa-c6dda625affd.png)

In the source window it doesn't seem to add any more code, just line breaks like in the WYSIWYG window. It's strange though as it doesn't seem to affect the first few elements at the top of the first image.

This was in Firefox 35.01.

Side note: The Source button doesn't currently show as "pressed/active" when you go to the window like the other buttons do when active.

**Comment by brunoais** [comment]
It seems to be related to the "idle" <br> tag that firefox places on all elements.
I'm not fully sure of it, though...

Can you get us a set of example source BBCode?

**Comment by cyphix333** [comment]
Sure. here is the full bbcode output I have been testing with:

```
[b]bold text[/b]
[i][b]bold italic[/b][/i]
[u][b]bold underline[/b][/u]
[i][u][b]bold underline italic[/b][/u][/i]
[b]bold striked[/b]
[i][u][b]bold italic underlined striked[/b][/u]

italic text[/i]
[u][i]italic underlined[/i][/u]

[u]underlined text[/u]

[s]striked text[/s]

align left

[center]align center[/center]

[right][u][b]align right bold underline[/b][/u]

[left][url=http://moo.com]a text link[/url][/left]
[left][url=http://moo.com][color=#9966ff]a colored text link[/color][/url]
[color=#6699ff][url=http://moo.com][b]a bold text link[/b][/url][/color]
[color=#333333]
[size=4][b]My List[/b][/size][/color]

[ul]
[li]Cat[/li]
[li]Dog[/li]
[li]Fish[/li]
[li]Duck[/li]
[/ul]

[size=4][b]My List 2[/b][/size]

[ol]
[li][b][color=#666633]Car[/color][/b][/li]
[li][b][color=#666633]Bike[/color][/b][/li]
[li][b][color=#666633]Tram[/color][/b][/li]
[li][b][color=#666633]Bus[/color][/b][/li]
[/ol]
[size=4][b]
My List 3[/b][/size]

[ol]
[li][url=http://moo.com]Moo[/url][/li]
[li][url=http://quack.com]Quack[/url][/li]
[li][url=http://woof.com]Woof[/url][/li]
[li][url=http://meow.com]Meow[/url][/li]
[/ol]
[/left]
[/right]
```

**Comment by brunoais** [comment]
The markup structure you are using is weird... That's good for testing.

**Comment by cyphix333** [comment]
Haha...... it's what was generated by SCEditor. :)

**Comment by samclarke** [comment]
Thanks for reporting! Should now be fixed.

**Comment by cyphix333** [comment]
Excellent - thanks!

**Comment by cyphix333** [comment]
I'm not sure if it's something I am doing wrong here, but I noticed this issue reappear when I was doing something else and it does it in FF & Chrome.

I overrode the default *quote* bbcode with a custom one with the below code:

```javascript
var quote_bbcode =
	{
        tags: {
            "blockquote": null,
        },
        isInline: false,
		quoteType: $.sceditor.BBCodeParser.QuoteType.auto,
		format: function (element, content) {
			var	author = '';
			var $elm  = $(element);
			var $cite = $elm.children('cite').first();

			console.log(element);
			
			if ($cite.length === 1 || $elm.data('author')) {
				author = $cite.text() || $elm.data('author');
				
				author = author.replace(' said:', '');
				
				$elm.data('author', author);
				$cite.remove();

				content	= this.elementToBbcode($(element));
				author  = '=' + author.replace(/(^\s+|\s+$)/g, '');

				$elm.prepend($cite);
			}

			return '[quote' + author + ']' + content + '[/quote]';
		},
		html: function (token, attrs, content) {
			if (attrs.defaultattr) {
				content = '<cite>' + $.sceditor.escapeEntities(attrs.defaultattr) +
					' said:</cite>' + content;
			}

			return '<blockquote>' + content + '</blockquote>';
		},
    };
```

However I wanted a line break after each blockquote and using `breakAfter: true` didn't seem to work for some reason, so I changed the `return` on the `html` parameter to:

```javascript
return '<blockquote>' + content + '</blockquote>>br />';
```

...and now whenever I toggle between source and wysiwyg mode it appends an extra line break under each quote.

**Comment by cyphix333** [comment]
Actually, thinking about it, I think it's my bad.... as when the `<br>` is first loaded in it loads in fine, then you switch too bbcode mode and then it takes the line break in as content, and then when you switch back it appends another `<br>` as that's what you're telling it to do........ so I guess this isn't the way to do it.

**Comment by brunoais** [comment]
`breakAfter` is for BBCode in the text mode, not in the WYSIWYG mode.
The current SCE adds a 0-width character after blocks (when it finds them >_>). To allow editing after them.
Are you being unable to edit text after such block?

**Comment by cyphix333** [comment]
It's alright, I handled it another way by inserting extra line breaks via the backend when the quote code is created and loaded into the editor.

Without doing that there would be issues when adding more than one quote at a time as they would sit directly under each other with no space between.

**Comment by mhiemstrapodiumtv** [comment]
Unfortunately this is still an issue in the latest version. When I switch back and forth from source to appearance more and more break lines appear in between the paragraphs.

**Comment by mhiemstrapodiumtv** [comment]
I found out what is causing the extra lines in the editor. After I switched back and fourth a couple of times I see this in the iframe:

<div>
  <br></br>
</div>
<div>
  <br></br>
</div>
<div>
  <br></br>
</div>

This is causing the extra lines. This looks like a bug in the code.

**Comment by alexiswbr** [comment]
Same here, extra `<br>` tag are added  each time I switch between the WYSIWYG and the source editor, or when I just populate the editor with the text I retrieved from the database (which is even more problematic).
ping @samclarke
