### ISSUE TITLE
First line not in a html tag

### ISSUE THREAD

**Issue by Heart1010** [samclarke/SCEditor#390]
I'm using latest SCEditor (v1.4.6) with the xhtml plugin.
When I write the following in the editor 
```
that's
a
test
```
![auswahl_556](https://cloud.githubusercontent.com/assets/1481680/6412132/3caf4630-be80-11e4-8b87-bf2e68ae4fe4.png)

(after "that's" pressing return key, after "a" pressing return key and so on)

The source code is looking like shown in the picture

![auswahl_557](https://cloud.githubusercontent.com/assets/1481680/6412102/00edcf18-be80-11e4-8a02-7cc47637752c.png)

Why the first line isn't in a div tag like all other lines?

And can this behaviour be changed so that per default text goes inside ```<p>...</p>``` and not inside ```<div>...</div>```?

**Comment by samclarke** [comment]
Thanks for reporting.

It should now wrap adjacent inlines children of the root node in `<p>` tags and default to using `<p>` tags.
