### ISSUE TITLE
getBody return type

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#392]
Should the getBody return a jQuery or a DOM object? Documentation here http://www.sceditor.com/api/sceditor/getbody/ says it returns a DOM object but it actually returns a jQuery object.

Personally I would pick the jQuery as return type because I don't like checking against nulls. But I want the docs to be consistant with the code.

**Comment by samclarke** [comment]
Ah that's a bug with the documentation. It returns the DOM body node wrapped in a jQuery object.

**Comment by samclarke** [comment]
Fixed. Thanks for reporting!
