### ISSUE TITLE
The example SCE on the website is faulty in source mode

### ISSUE THREAD

**Issue by brunoais** [samclarke/SCEditor#394]
When going to the website http://www.sceditor.com/, there's an example SCE with BBCode for use.
In the current example, multiple buttons are not available in source more.
Buttons not available include:
Bold, Italic, underline, subscript, superscript, align (left, middle, right, justify) and the list controls.

**Comment by samclarke** [comment]
After all that testing I still managed to miss this...

I'll try get a couple more bugs fixed then retest the whole thing and release as 1.4.7.
