### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by sochka** [samclarke/SCEditor#396]
Hi, when I install this package through bower - I don't have `minified` directory after `1.4.6` version and therefore cannot use it. Could you add bower support please?

**Comment by brunoais** [comment]
What does it fail when you try to use bower?

**Comment by sochka** [comment]
When I use bower I receive raw github repo sources, which do not contain built files. I have to build them manually.

**Comment by brunoais** [comment]
Ah, OK... I c...

**Comment by brettz9** [comment]
What's going on with Bower? I don't see a `bower.json` in the repo

**Comment by brettz9** [comment]
What's going on with Bower? I don't even see a `bower.json` in the repo

**Comment by sochka** [comment]
brettz9, I think it was directly published to bower index, but bower support is completely broken... I use older version of sceditor like this: ` "SCEditor": "1.4.4",1
