### ISSUE TITLE
unwanted HTML named "markers"

### ISSUE THREAD

**Issue by eness** [samclarke/SCEditor#397]
hey there,

I've just installed and gave a try, it's an awesome and simple text editor exactly as I wanted.

I don't know if it's a bug (probably not) but I'm having a nonsense problem with the editor. When I write any text into the editor, it creates two <span> elements with IDs of sceditor-end-marker and sceditor-start-marker.

As soon as I hit submit button of the parent form and write these data into the database or else, these unwanted and looks redundant marker spans come with the editor's HTML data and get saved into my database. So when I limit the chars of that column in db (such as 64 chars) these unstripped HTML tags fill out the character space and therefore cause other problems.

I tried removeMarkers() method of rangeHelper (on just before form submit() ) but I suppose it didn't work.

How can I get rid of these tags? What am I missing?

**Comment by samclarke** [comment]
Without a plugin the editor just returns the raw contentEditable HTML which is useful if you want that. If you want it filtered you need to use either the XHTML or BBCode plugin to filter them.

**Comment by puroossosinistro** [comment]
I have the same problem. Please how I do that?

**Comment by myfonj** [comment]
Check if you have `<script src="./formats/xhtml.js"></script>` actually loaded.

> If you want it filtered you need to use either the XHTML or BBCode plugin to filter them.

In other words, you have to both load the plugin JS file into document and set it in options (see https://www.sceditor.com/documentation/getting-started/).

If you started from "example.html" that uses bbcode, it is easy to forget adding the script tag loading `xhtml.js` along changing `format: 'xhtml'` in options (been there) and you got no warning besides those strange elements in the code.
