### ISSUE TITLE
Fullscreen mode - Firefox scrollbar on the left - overlap

### ISSUE THREAD

**Issue by trismarck** [samclarke/SCEditor#400]
Hello,

when in Fullscreen mode, if Firefox scrollbar is on the left, the scrollbar overlaps the BBCode Editor window:
![20150312-sceditor-bbcode editor-fullscreen-firefox-scrollbar on left](https://cloud.githubusercontent.com/assets/4901124/6618484/86f1d85a-c8c3-11e4-948d-420d76fc7597.png)

Thanks.

**Comment by samclarke** [comment]
I think this might be a bug in FF. It looks like it's including the scrollbar width during layout but isn't accounting for the scrollbar being on the left when rendering.

**Comment by trismarck** [comment]
I've found a similar bug report on FF bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=941020
Thanks for looking into it.

**Comment by samclarke** [comment]
I'm closing this as it's a FF bug and there isn't really anything that can be done to fix it. Thanks for reporting it.
