### ISSUE TITLE
When breakBeforeBlock is set to true, the line breaks keep getting added on every run

### ISSUE THREAD

**Issue by bhutaninitin** [samclarke/SCEditor#404]
When breakBeforeBlock is set to true, the line breaks keep getting added on every run. For example,  [ul]  [li] becomes 

[ul] 

[li]
I wonder if there is a way to ensure that breakBeforeBlock inserts only one linebreak between two blocks. 

Thanks,
Nitin

**Comment by brunoais** [comment]
Which of those two has breakBeforeBlock set to true?

**Comment by bhutaninitin** [comment]
Here are my parseOptions: 

parserOptions: {
                        breakBeforeBlock: false,
                        breakStartBlock: false,
                        removeEmptyTags: false,
                        fixInvalidNesting: false,
                        fixInvalidChildren: false,
                        disableBlockRemove: true

                }


When I set breakBeforeBlock to true, I get one additional line break between [ul] [li] after saving data.

**Comment by brunoais** [comment]
According to that, you have it set to false...

**Comment by bhutaninitin** [comment]
Ya. I set it to false after the multiple line break issue. When I set it to true, multiple line breaks keep getting added on every open and save.

**Comment by brunoais** [comment]
Why don't you keep it at false?

**Comment by bhutaninitin** [comment]
The bbcode seems more readable with true.

**Comment by brunoais** [comment]
When?

**Comment by bhutaninitin** [comment]
I didn't understand your question. 

[ul]
[li] First item [/li]
[li] Second item [/li]
[/ul]

is more readable than:
[ul][li] First item [/li][li] Second item [/li][/ul]

and ...

[ul]


[li] First item [/li]




[li] Second item [/li]


[/ul]

**Comment by bhutaninitin** [comment]
I am wondering whether this made it to the latest.

**Comment by samclarke** [comment]
Closing as this looks to have already been fixed.
