### ISSUE TITLE
How to trigger a button click in SCEditor?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#406]
I need to trigger a click on the source code button (using xhtml plugin). 

Trying it directly: 

	$('. sceditor-button-source').trigger('click');

does not work. 

I guess I need to use ExecCommand() http://www.sceditor.com/api/sceditor/execcommand/

instance.execCommand(command, param);

I have tried: 

	$('#sce_sourcebtn').click( function() { 
		$('textarea[name="test"]').sceditor('instance').execCommand('source');
	});

Unfortunately, it does not work.

**Comment by brunoais** [comment]
http://www.sceditor.com/api/sceditor/insourcemode/
+
http://www.sceditor.com/api/sceditor/togglesourcemode/
?

Besides, that's to execute a command for the browser to execute, not SCE.

**Comment by q2apro** [comment]
Thanks a lot, that worked: 

	$('#sce_sourcebtn').click( function() { 
		$('textarea[name="test"]').sceditor('instance').toggleSourceMode();
	});

In case someone reads this here and needs to trigger any other button, how would he do it?

**Comment by brunoais** [comment]
There's no direct way to trigger any button. What is your objective in that sense? Maybe what you want is not to trigger a button.

**Comment by q2apro** [comment]
Currently I have no scenario. Lucky me there was the source toggle mode method. However, it could happen that I need to trigger another button from outside the editor. In this case it would be great to know how to do it. 

But for now: My "source button" problem solved, and your "There's no direct way to trigger any button." accepted.
