### ISSUE TITLE
How to confirm the link dialog with Enter key?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#407]
How can we tell SCEditor that the link dialog should close and accept the input, when the field is shown and the enter key gets pressed: 

![capture](https://cloud.githubusercontent.com/assets/6764548/6960761/0730c97a-d92e-11e4-9bae-e39c80c40a09.PNG)

In other words, how can we listen for the enter key and then trigger the input button of the link dialog?

**Comment by q2apro** [comment]
+1 Would be great.

**Comment by q2apro** [comment]
Is there any news or progress on this issue?

**Comment by q2apro** [comment]
It obviously does not seem that easy for me or for others to implement that. 

I think we have to start here: 
https://github.com/samclarke/SCEditor/blob/master/src/plugins/xhtml.js#L184

But I have no idea how I get the key event included into the source :(

That actually also reminds me of the bug that we need to add a `http://` if the user only enters `www...`

**Comment by brunoais** [comment]
My RL work has been overwhelming and Sam hasn't been answering... I'll see when I can allocate time to this. I've been pushed around a lot.

**Comment by q2apro** [comment]
I have also sent @samclarke an email but he has not replied. I hope he is fine and nothing has happened to him.

**Comment by samclarke** [comment]
Fixed. Will be available in version 2.0.0.

**Comment by q2apro** [comment]
Can this be rolled out in the next release already? Guess it will be sceditor v. 1.5.3?

**Comment by samclarke** [comment]
The next release will be version 2 (unless a really bad bug is found in v1.5 that needs to be fixed).

You can use this in older versions by overriding the default link command, something like:

```js
$.sceditor.command.set('link', {
	exec: function (caller) {
		var	url, text;
		var	editor  = this;
		var content = '<div>' +
				'<label for="link">' + editor._('URL:') + '</label> ' +
				'<input type="text" id="link" placeholder="http://" />' +
			'</div>' +
			'<div>' +
				'<label for="des">' + editor._('Description (optional):') + '</label> ' +
				'<input type="text" id="des" />' +
			'</div>' +
			'<div>' +
				'<input type="button" class="button" value="' + editor._('Insert') + '" />' +
			'</div>';
		var $link = content.find('#link');
		var $description = content.find('#des');

		function insertUrl(e) {
			url  = $link.val();
			text = $description.val();

			if (url) {
				// needed for IE to restore the last range
				editor.focus();

				// If there is no selected text then must set the URL as
				// the text. Most browsers do this automatically, sadly
				// IE doesn't.
				if (!editor.getRangeHelper().selectedHtml() || text) {
					text = text || url;

					editor.wysiwygEditorInsertHtml(
						'<a href="' + url + '">' + text + '</a>'
					);
				} else {
					editor.execCommand('createlink', url);
				}
			}

			editor.closeDropDown(true);
			e.preventDefault();
		}

		content.find('.button').click(insertUrl);

		$link.add($description).keypress(function (e) {
			// 13 = enter key
			if (e.which === 13 && $link.val()) {
				insertUrl(e);
			}
		});

		editor.createDropDown(caller, 'insertlink', content);
	}
});
```

**Comment by q2apro** [comment]
When about is the new release planned?

**Comment by samclarke** [comment]
A beta version of it has already been released: https://github.com/samclarke/SCEditor/releases/tag/v2.0.0-beta1

The final release will be when it's fully tested and the new website is fully updated to reflect the changes.
