### ISSUE TITLE
Cut, Copy, Paste

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#408]
> This only works in IE because of security permissions. It’s disabled in other browsers.

What about hiding the buttons altogether (based on browser) if they're never going to be enabled?

**Comment by brunoais** [comment]
Do show a way of doing feature detection on that and I'll implement it :)

**Comment by OlafvdSpek** [comment]
As keyboard shortcuts and popup menus are available for these commands perhaps it's best to just exclude them entirely?

**Comment by samclarke** [comment]
Cut and copy are now supported in FF and Chrome so only paste is IE specific.

I don't really want to have commands that only show up depending on what browser the user is using as someone might not want the paste command and not realise it's there unless they check in IE. It might make sense to either remove the paste command or remove it from the default toolbar though.
