### ISSUE TITLE
Cancel @ Insert Email

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#409]
Click Insert Email, Click Cancel. It pops up another dialog asking for Displayed Text, IMO it shouldn't.

**Comment by brunoais** [comment]
I can't find the cancel button

**Comment by OlafvdSpek** [comment]
I'd swear the dialog was different earlier today.
Escape doesn't work in the current one though.

**Comment by Destroy666x** [comment]
Dialogs are different is full/source mode. Source mode was meant here.

**Comment by OlafvdSpek** [comment]
Ah, thx! Should they be different?

**Comment by brunoais** [comment]
Seems reasonable. I'll deal with that when I'm done what I'm doing.
