### ISSUE TITLE
Break Quote button 

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#410]
A button to insert 
[/quote]\n
\n
[quote]\n

would be nice.

**Comment by brunoais** [comment]
How is that different from the current one?

**Comment by OlafvdSpek** [comment]
Current one inserts [q][/q], I'd like [/q][q] instead.

**Comment by brunoais** [comment]
Oh, I misread it...
Imo, denied. Do one yourself.
