### ISSUE TITLE
Out-of-band smily conf

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#411]
We've got too many smilies (1300), the conf is about 48KB uncompressed. Is it possible to move the smily conf out-of-band?

**Comment by brunoais** [comment]
What is "out-of-band"?

**Comment by OlafvdSpek** [comment]
Perhaps via a separate cachable request.

**Comment by brunoais** [comment]
It is cacheable.

**Comment by OlafvdSpek** [comment]
Right, I should just move the editor conf to a separate file..
