### ISSUE TITLE
Can't click to focus on empty parts of textarea

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#412]
It seems one can't click on space after the last line to set focus to the editor.. (in Chrome)

**Comment by brunoais** [comment]
I've tried in the latest Chrome and it worked correctly.

**Comment by OlafvdSpek** [comment]
At http://www.sceditor.com/ it seems to work fine.

But at my site I get the normal arrow pointer until I go to the text at
which point I get the | pointer..

**Comment by brunoais** [comment]
Which version are you using?

**Comment by OlafvdSpek** [comment]
1.4.7

**Comment by brunoais** [comment]
I still can't.
Could you please place that available online somewhere for me to access?

**Comment by rishabhdev** [comment]
just make sure jquery.sceditor.default.min.css file is  included in the page..
or you can manually set the height of the body in iframe to 100%.

**Comment by OlafvdSpek** [comment]
Console is showing a failed request for
http://xxx/minified/jquery.sceditor.default.min.css while the file is at
http://s.xxx/minified/jquery.sceditor.default.min.css
Is the JS code trying to add the CSS too?

**Comment by brunoais** [comment]
No.
That's the HTML code of the iframe which has to be generated on the fly.

**Comment by OlafvdSpek** [comment]
Where do I set the location of that file? Can't find the option @
http://www.sceditor.com/documentation/options/

**Comment by OlafvdSpek** [comment]
Ah, it's the style option..

Shouldn't the URLs at http://www.sceditor.com/ start with a slash?

Having them relative to the current file doesn't seem to make sense.

**Comment by OlafvdSpek** [comment]
If the CSS link is dynamically generated does it also have to be
written 'manually'?

2015-04-08 14:49 GMT+02:00 Olaf van der Spek <olafvdspek@gmail.com>:
> Ah, it's the style option..
>
> Shouldn't the URLs at http://www.sceditor.com/ start with a slash?
>
> Having them relative to the current file doesn't seem to make sense.



-- 
Olaf

**Comment by brunoais** [comment]
I did not understand the question

**Comment by brunoais** [comment]
I did not understand the question

**Comment by OlafvdSpek** [comment]
http://www.sceditor.com/  already has the CSS link under "Include the JS & CSS:" Is that necessary?

**Comment by brunoais** [comment]
You need the a stylesheet for SCE's elements

**Comment by OlafvdSpek** [comment]
Above it was said that was inserted dynamically..

**Comment by brunoais** [comment]
That is the stylesheet for the contents inside the iframe

**Comment by marcondag** [comment]
I had this issue today. Not going to try to reproduce it in codepen or anything because I think it's pretty specific to our environment, but here's a solution that worked for me:

```javascript
instance.getBody().style.height = window.getComputedStyle(instance.getContentAreaContainer()).height;
```

The problem for me was that the body was not filling the height of the editable area, but the iframe was. So you could click the first "line" of the editor but not any other. All this does is set the height of the body to the height of the iframe. We have this running right when the editor is initialized inside of a react component and it works create. 

BTW: We do have the stylesheet getting injected in. If that's supposed to fix it, then it doesn't for us. The above, however, works consistently.

**Comment by dpatou** [comment]
The above comment fixed it for me. Thanks a lot.

I had to slightly modify it to account for the height of the toolbar and avoid scrollbars on empty editors. What i did was 
`var adjusted = (parseInt((window.getComputedStyle(sceditor.instance(el).getContentAreaContainer()).height).replace('px',''))-37)+'px';`
`sceditor.instance(el).getBody().style.height = adjusted;`

**Comment by ArabGenius** [comment]
Hello
I have the same problem,, yet I could not understand the solution 
where to put the code ?
or how to specify the height for the iframe body

**Comment by dpatou** [comment]
Hi,

You put the code where you instanciate the module on your page.

Like 
```
<script>
    $(document).ready(function() {
        $(".sceditor").each(function(idx,el){
            sceditor.create(el,{
                format:'xhtml',
                style:'css/sceditor-default.min.css',
                toolbar:'bold,italic,underline,strike,color,removeformat|bulletlist,orderedlist|link|source',
                emoticonsEnabled:false,
                height: 200,
                width: '100%',
                language:'fr'
            });
            var adjusted = (parseInt((window.getComputedStyle(sceditor.instance(el).getContentAreaContainer()).height).replace('px',''))-37)+'px';
            sceditor.instance(el).getBody().style.height = adjusted;
        });
    });
</script>
```

**Comment by ArabGenius** [comment]
@dpatou thank you
it worked like a charm
