### ISSUE TITLE
Bug in Internet Explorer 11 when inserting a link (xhtml plugin)

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#415]
Beforehand I would like to ask @samclarke to add a xhtml demo to http://www.sceditor.com/ so that users and developers can try the editor in xhtml mode as well, and reproduce their own bugs with the default editor.

I found a bug with IE11, after I upgraded from v1.4.6 to the latest sceditor v1.4.7: 

![vorschau](https://cloud.githubusercontent.com/assets/6764548/7004291/dd67f5a4-dc71-11e4-9f27-c69e8e8f61c4.gif)

As I wrote, would be nice to countercheck with a sceditor-xhtml-demo on http://www.sceditor.com/

**Comment by brunoais** [comment]
This seems to be related to the caret positioning. It is not being properly handled.
That's weird. I didn't expect IE11 to lose the caret position if it is ordered to ignore all clicks in the buttons.
Which changes did you make to SCE? Did you just remove toolbar buttons?

**Comment by brunoais** [comment]
I was able to reproduce the bug in http://www.sceditor.com/ .
This is not related to any plugin.

**Comment by q2apro** [comment]
Mhh, seems not fix the problem. With the first link it works nicely. Writing more text then, and adding the next link, the same issue occurs.

**Comment by samclarke** [comment]
This fix seems to be working for me. Could you check if I'm doing something differently: [video](https://dl.dropboxusercontent.com/u/56830471/out.ogv).

**Comment by q2apro** [comment]
I emptied the cache of IE11 beforehand to load the new js file... before I added the code change, within the minified jquery.sceditor.xhtml.min.js file it is: `ub.closeDropDown(true)`. Here is what I am doing on my site: 

![vorschau](https://cloud.githubusercontent.com/assets/6764548/7067143/b7d8dde6-ded1-11e4-9b10-1cdc9de9de1e.gif)

Maybe you like to test it yourself: http://www.gute-mathe-fragen.de/ask

<br />
PS: I would love to test the editor directly on www.sceditor.com (please can you also add the xhtml demo?).

**Comment by brunoais** [comment]
@q2apro Please show the 2nd part a bit slower. I didn't quite get what you did after you clicked the link button.

**Comment by q2apro** [comment]
After I clicked the link button the 2nd time. I pasted the URL and hit the dialog button "Insert". Nothing more. Then I added a space after the inserted link.

**Comment by brunoais** [comment]
So it lost the selection again...

**Comment by samclarke** [comment]
I've just tried copying as closely as I can and seems [to work](https://dl.dropboxusercontent.com/u/56830471/out-2.ogv).

**Comment by q2apro** [comment]
Clicked the button, reloaded the page, tried and still the same. I have the feeling that it could be related to the "preview bug" of mine: https://github.com/samclarke/SCEditor/issues/360#issuecomment-88827291

Otherwise I don't know. Once again, would be nice to have an xhtml demo on sceditor.com
Thanks.

**Comment by samclarke** [comment]
That could be it, I'll have a look at the preview bug and see if I can reproduce it.

I've uploaded the debug test page [here](https://dl.dropboxusercontent.com/u/56830471/tmp9415/tests/manual/debug/index.html). Could see if you can reproduce this bug with that?

You're right there should really be an XHTML demo on the website. It wouldn't help with this though as this fix isn't released yet.

**Comment by samclarke** [comment]
I've tested it and I think you're right, the other bug is caused by the same issue as the preview bug.

**Comment by q2apro** [comment]
Yep, the demo on the test page works in IE11. 

Sorry for the hassle, I really need to find a solution for this preview issue on my site...
