### ISSUE TITLE
Wrong button state with autofocus

### ISSUE THREAD

**Issue by OlafvdSpek** [samclarke/SCEditor#424]
The button state (B and U enabled) appears to be for the top line while autofocus sets the cursor to the bottom line. I think the button state doesn't get updated after autofocus does it's thing.

BTW, why isn't it autoFocus?

**Comment by brunoais** [comment]
Which browser. If IE, what version?

**Comment by samclarke** [comment]
Thanks for reporting!

It's called `autofocus` because it was added a long time ago and fixing it would require having both `autoFocus` and `autofocus`. I would like to tidy the API up but fixing any bugs is the main priority at the moment.
