### ISSUE TITLE
SCEditor.overlay.css ??

### ISSUE THREAD

**Issue by odungern** [samclarke/SCEditor#426]
We have evaluated several  XHTML wysiwyg editor plugins for js ... and are considering SCEditor as first choice.
It is not yet integrated in our web app to gather requirements and manage system specifications, we are hesitant to just add the css to our bootstrap-3.3.0.css plus other component and custom css.

Is it worthwhile trying to derive an sceditor.overlay.css that omits all general definitions (such as html, body etc .... even though we like them as they are simple and make sense) and to define the others so as to apply only in textareas carrying a self-defined class="formatted" (supposing that all textareas under control of SCEditor would get that class) ?? 
So
```
table, td {
	border: 1px dotted #000;
	empty-cells: show;
 }
```
would become:
```
textarea.formatted table, 
textarea.formatted td {
	border: 1px dotted #000;
	empty-cells: show;
}
```
??
.. we just could try ... but perhaps there is someone out there who has a similar challenge and perhaps has some better ideas ...

Thanks a lot in advance.

**Comment by brunoais** [comment]
I didn't understand...
What is wrong with adding CSS to your current CSS?
What is wrong to edit SCE's original CSS into your integration?

**Comment by odungern** [comment]
There's nothing wrong with your solution.  Thanks for getting into discussion with us!
Just we are hesitant to paste the sceditor.*.css over what we've got and thus override a lot of standard tags and classes (beginning with html, body, ....).  I suppose we are understanding CSS correctly ;-)

So we consider changing the sceditor.*.css in the following way
* remove the definitions for standard classes
* add context selectors to all sceditor.*.css definitions so that they apply only within textareas under control of SCEditor (see table example above).

This would allow us to have separate and independent definitions for tables within textareas under control of SCEditor (the user data) and outside of it (the app).

Did we overlook something or have a mis-conception ??

**Comment by brunoais** [comment]
You could just edit SCE's CSS using a preprocessor.
For example, prefix all CSS with
`textarea.formatted {`, suffix with:
`}`
use LESS or SASS to recompile into CSS and you get what you want.
If you use gulp or grunt, it should be easy to setup such that they apply those suffixes and prefixes before the compilation stage.

**Comment by odungern** [comment]
Thanks.
The question was not so much how to do it, but whether goal and idea are a valid approach, whether the are side-effects on the SCEditor implementation we don't see and whether there are better ideas.
I interpret your answer that you don't see a problem in general ... and so we will give it a try. 
We'll share the results, here, once (and if ;-) proven.

**Comment by brunoais** [comment]
Anyway, I don't really get it why all that is required. The CSS related to how everything is displayed for the WYSIWYG formatting is inside the iframe sandbox. The only CSS that could bother is the the one used outside the iframe but that is done with the rest of the page's CSS taken into account (as long as they don't reuse the "SCEditor" name.

**Comment by odungern** [comment]
Sorry for pulling you into a basic discussion such as this - very probably we are talking from different perspectives. And also very probably we haven't understood SCEditor fully.  It would be great help, if you just say 'right' or 'wrong' to the following statements, which illustrate our current understanding:

1. when integrating one of the SCEditor themes, such as 'default.css' the naming is such that there is no conflict with other modules.
2. when integrating sceditor.default.min.css in the main document as proposed in your documentation (http://www.sceditor.com/posts/html-demo/), the definitions apply to the whole document.
3. When it is referenced before any other CSS, many of it's definitions will be overwritten. By all likelyhood, your table definition with dotted frames will not be available in a textarea under control of SCEditor.
4. When referencing it after any other CSS, sceditor.default.min.css will overwrite the others. Among others, it's html, body, h1, h2 etc definitions will prevail.
5. Omitting sceditor.default.min.css means we would lose for example the table definition with dotted frames within textareas under control of SCEditor.

From that understanding our idea was to take all definitions from sceditor.default.min.css we need (table, td, code, blockquote, ..) and confine them to textareas under control of SCEditor as described in earlier posts.

I do not understand (and neither my collaborators) when you are saying that all your CSS is active only inside an iframe sandbox.

**Comment by brunoais** [comment]
*tsk* Sam messedup in there...
The file to include in the page is:
`minified/themes/default.min.css`, not `jquery.sceditor.default.min.css`.
`jquery.sceditor.default.min.css` is the CSS to include inside the iframe.

**Comment by odungern** [comment]
OK!
Another observation on that page (http://www.sceditor.com/posts/html-demo/), line 7 and 8 should be:
```
<!-- Include SCEditor's JS -->
<script type="text/javascript" src="minified/jquery.sceditor.xhtml.min.js"></script>
```

**Comment by samclarke** [comment]
Sorry about that. Should all be fixed now.

**Comment by odungern** [comment]
... no reason to be sorry.  A german saying: Who doesn't work, doesn't make errors.  ("Wer nicht arbeitet, macht keine Fehler"). Thanks a lot for Bruno's and your quick help. Hope we can contribute at some point. 
Currently evaluating how to overload command functions, we need different tags for images. Should be straight forward with command.set(). We like the software design, and that was the reason why SCEditor came up first from our evaluation.
