### ISSUE TITLE
How to load SCEditor 'on demand' ('lazy loading') ?

### ISSUE THREAD

**Issue by odungern** [samclarke/SCEditor#433]
We've successfully integrated SCEditor in our app for publishing and reviewing model based system specifications. It is working very reliably. Thank you very much for your work, it is a nice piece of software.
We have a question: 
Even though rather small when compared to other wysiwyg editor plugins, we would like to load the plugin only in case a user has edit rights and actually wants to edit a piece of formatted text (not all object types have formatted text attributes and especially the attributes intended for reviewer's feedback are most often just enumerated or simple text).
SCEditor is working just fine if we include the script in the html header as proposed by the docu. It is initialized when the page is processed on document.ready. Obviously it is possible to load the script file at some later point. But how to initialize the plugin, so that the editor instances can again be created using
```
$('#id').sceditor(sceditorOpts);
```
Is there any way to use the plugin that way?  (Didn't find anything related in the docs ....)
Thanks a lot in advance!

**Comment by brunoais** [comment]
That's how they are initialized...
What is the issue you have?

**Comment by odungern** [comment]
When we load the file with:
```
<script type="text/javascript" id="xhtmlEditor" ></script>
<script type="text/javascript">
..
$( "#xhtmlEditor" ).load( "./lib/jquery.sceditor.xhtml.min.js", 
    function() { .... } );
...
// once loaded:
$('#id').sceditor(sceditorOpts);
```
</script>
it says "TypeError: $(...).sceditor is not a function".
The source is loaded, but the DOM does not show jQuery.sceditor(); the initialization is missing which in the documented case takes place when the code is executed when the page is ready. 
We think it should be possible to extend jQuery at some point on demand, not just after page load ....

If there is a misconception on our part, just say it can't be done.

**Comment by brunoais** [comment]
Fix your javascript. With just an excerpt like that, I can't help you besides stating the obvious.

**Comment by samclarke** [comment]
The jQuery `load()` method is meant for getting HTML from the server and inserting it into the matched elements, not really for loading JS.

The `$.getScript()` method should do what you want. Something like:

    $.getScript('./lib/jquery.sceditor.xhtml.min.js', function() {
        $('#id').sceditor(sceditorOpts);
    });

**Comment by odungern** [comment]
This does the job, indeed. An experienced programmer in the team should have had the idea, himself ;-)
We will do it this way.
Just to explain: In our case we have a tiny module-manager and module files consisting of HTML and corresponding viewModels within script-tags. These are loaded with $().load() and all methods are called explicitly, as there is no auto-execute. Works fine, as well.  
Thanks a lot for your help!
