### ISSUE TITLE
getOuterText() doesn't always get all the text

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#434]
If the caret is at the start of a TextNode and `startContainer` is the node that contains the TextNode, `getOuterText()` incorrectly treats the range `startOffset` as the character offset when it is in fact the node offset which contains the caret.

Also if the `startContainer` is a TextNode, `getOuterText()` should treat any adjacent TextNode as being part of the same node.

Should be something like:

    startContainer := range.startContainer;
    startOffset := range.startOffset;
    text := ""

    if startContainer != TextNode
        startContainer = startContainer.childNodes[startOffset]
        startOffset := 0
    
    while text.length < len && startContainer == TextNode
        text := text + startContainer.text.substr(startOffset, len)
        startOffset := 0 or len depending on direction
        startContainer := previous/next sibling depending on direction

    return text.substr(len)

**Comment by brunoais** [comment]
Check my code on #414. It has a way of dealing with that that should work. You'll need to make an extra way for IE8, though.

**Comment by samclarke** [comment]
I didn't notice that I'll have a look, thanks! I'm really starting to think how long to support IE 8 for as it's such a pain.
