### ISSUE TITLE
Change default active button to "align right" instead "align left"

### ISSUE THREAD

**Issue by RezaRamezanpour** [samclarke/SCEditor#435]
How i can set default active button for align buttons to "align right" instead of "align left"?
I using SCEditor in a Persian website that is a right-to-left language, so "align right" button should be active by default.
thanks.
## UPDATE

Maybe it's a Firefox bug, Google chrome correctly show "align right" when I'm in right-to-left.

**Comment by samclarke** [comment]
If you set the [`rtl` option](http://www.sceditor.com/documentation/options/#rtl) to true it will put the editor into right-to-left mode mode.

For example:

    $("textarea").sceditor({
        rtl: true,
        /* other opts */
    });

**Comment by reza-irdev** [comment]
![screenshot from 2015-05-04 20 09 58](https://cloud.githubusercontent.com/assets/12220097/7456431/b9c73180-f299-11e4-8e3a-ba6edc6c6b80.png)
I already do that but "align left" still active, See screenshot.
