### ISSUE TITLE
Remnant dialog after instance.destroy()

### ISSUE THREAD

**Issue by odungern** [samclarke/SCEditor#438]
An inexpected behavior - perhaps we have not set up the SCEditor instance properly, perhaps it is a bug .. the issue is not particularly important, it wouldn't let us postpone a delivery.

Environment: jQuery, Bootstrap, Knockout - all recent.
* In edit mode, SCEditor is opened (OK)
* Entering text, links, tables and images using the action buttons all works nicely when used properly (OK), but
* When pressing an action button, a dialog appears (OK: screenshot 1/3)
![sce-remnantdialog-1](https://cloud.githubusercontent.com/assets/8947971/7539493/a4ee4d8c-f5a7-11e4-8806-0f80ccb9fdfa.png)
* When leaving the edit mode ('cancel' on main page), the SCEditor instance is destroyed, but the dialog sticks to the browser tab (NOK: screenshot 2/3).
![sce-remnantdialog-2](https://cloud.githubusercontent.com/assets/8947971/7539494/a9e79550-f5a7-11e4-9994-91b8b29e9aa6.png)
* Even if changing the window content, the dialog continues to stick to the browser tab (NOK: screenshot 3/3).
![sce-remnantdialog-3](https://cloud.githubusercontent.com/assets/8947971/7539496/adcc8bc6-f5a7-11e4-88ba-12a824ee80ef.png)
* Only page reload lets it disappear.
* Expected: When the instance is destroyed, all open dialogs are closed.

**Comment by brunoais** [comment]
First thing's first:
1. You are **not** changing pages. All those are the same page.
2. Which cancel button did you press?

**Comment by brunoais** [comment]
I still think this contained incomplete information. Sam disagrees. I'll just move on, then.

**Comment by samclarke** [comment]
Thanks for reporting!

@brunoais the `destroy()` method was missing a check to remove the open dropdown which caused it to be left when the editor was destroyed.

**Comment by brunoais** [comment]
He didn't mention he used SCE's `destroy()` method. He mentioned he destroys SCE but it can also be just deleting the HTML associated to most of the editor without actually calling the `destroy()` method. Although you did fix something, it's not clear whether or not your changes are a fix to what is mentioned in this issue.

**Comment by samclarke** [comment]
It's not mentioned in the description but it is in the title and `destroy()` does have the bug so seems likely.

**Comment by brunoais** [comment]
"likely" or "most likely" is not enough for me in these situations, that's why. I have to be fully certain or be as certain as I can get with the information available or reproducible in order to conclude such things.

**Comment by odungern** [comment]
Thank you very much, Sam and Bruno, for giving this your attention.

Bruno is right:
* we do not change the page, this would of course make the remant dialog disappear. We are using knockout() to change the modified content depending on various conditions (such as selected tab, edit-mode on/off, etc) 

Sam's assumptions are fully in line with what we do:
* we do destroy the SCEditor instance when leaving edit mode (cancel or save / Abbrechen or Speichern) - and I am sorry for giving the german screens - should have changed the browser language, first.
* Thanks for fixing it right away!
