### ISSUE TITLE
chrome freezes when removing formatting from bullets

### ISSUE THREAD

**Issue by taekvideo** [samclarke/SCEditor#442]
To reproduce: in chrome (latest version) select multiple lines of text, click bullets on toolbar. The lines stay selected and bullets appear, but if you click the bullets button on the toolbar again to remove them, it freezes.

Code used to initialize:
```
        $("#editplayfootnotes").sceditor({
            plugins: 'bbcode',
            style: 'lib/SCEditor/minified/jquery.sceditor.default.min.css',
            toolbar: 'bold,italic,underline,size|left,center,right|bulletlist,orderedlist|link,unlink',
            resizeEnabled: false,
            enablePasteFiltering: true
        });
```

You also need an event listener on the "blur" event which accesses the current value from sceditor (in our app we need to do something with the data as soon as the editing box loses focus).

```
$("#editplayfootnotes").sceditor('instance').unbind("blur", playFootnotesListener).bind("blur", playFootnotesListener);

function playFootnotesListener(e){
    var test = $("#editplayfootnotes").sceditor('instance').val();
}
```
Edit:
With further testing I've determined that calling the .val() function (to read the value) after the list already exists in the editor will cause it to freeze when trying to remove it. You don't actually need it on a blur event.

happens in chrome on pc, and chrome/safari on mac... but firefox and internet explorer on pc work fine. Might be related to webkit then?
Removing bullets one line at a time doesn't cause the freeze, it only happens when trying to remove bullets from multiple lines at once.

task manager shows the chrome process for that tab stuck at 25% (infinite loop on a single core out of 4?).

**Comment by brunoais** [comment]
Does it happen in both source mode and WYSIWYG mode?
Does it happen without the bbcode plugin?
If you do not set both `resizeEnabled` and `enablePasteFiltering`, does it still happen? If not, in which combinations can you reproduce?
Do you have to unbind and bind for it to happen? Does it happen if you don't unbind before you bind?
What if you don't search the DOM every time to want to get the value? Does it work if it is done that way?

**Comment by taekvideo** [comment]
Hmm I decided to make the simplest possible example I could.. and it seems the .val() part isn't even necessary for the freeze to happen if the bullets are already there when the sceditor is initialized.

```
<!DOCTYPE html>
<html>
    <head>
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/jquery.sceditor.min.css" media="all" />
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/themes/default.min.css" media="all" />
		
		<script type="text/javascript" src="lib/jquery-1.11.1.js"></script>
		<script type="text/javascript" src="lib/SCEditor/minified/jquery.sceditor.bbcode.min.js"></script>
    </head>
    <body>
		<textarea id="test" style="width: 500px; height: 250px;"><ul><li>test1</li><li>test2</li><li>test3</li></ul></textarea>
        <script>
			$(function(){
				$("#test").sceditor({
					style: 'lib/SCEditor/minified/jquery.sceditor.default.min.css',
					toolbar: 'bulletlist',
				});
			});
        </script>
    </body>
</html>
```
If you run that in chrome (after adjusting the paths for jquery/etc) and select the whole list and click the bullet button on the toolbar to try to remove the bullets, chrome will freeze up.

It's only a problem with wysiwyg not the source mode.
It still happens when I remove the plugin: bbcode and use <li> etc in the textarea.
The settings for resizeEnabled and enablePasteFiltering don't seem to make a difference.

**Comment by brunoais** [comment]
I'm trying to reproduce in `SCEditor/tests/manual/debug/index.html` using 42.0.2311.135 and nothing happens.
Oh wait. Chrome is updating... Please wait.

**Comment by taekvideo** [comment]
I have 42.0.2311.152 too and no extensions... and another guy is having it happen on his mac with both safari and chrome too so I don't think it's computer/browser settings that's the problem.
Using the latest 1.4.7 release of sceditor so I don't have any of the development commits since then if any of those would affect it.
Tried different versions of jquery and all freeze the same.

Are you sure you're selecting the whole list and then clicking the bullet button? It doesn't freeze if you just do one row at a time.

**Comment by samclarke** [comment]
I can't reproduce this either. Does it happen with the editor on sceditor.com?

**Comment by taekvideo** [comment]
No it doesn't happen on there and I think I figured out why... it's the whitespace.
In my example I have the text area:
```
<textarea id="test" style="width: 500px; height: 250px;"><ul><li>test1</li><li>test2</li><li>test3</li></ul></textarea>
```
which I give to the sceditor to initialize. But If I add some extra whitespace like...
```
		<textarea id="test" style="width: 500px; height: 250px;">
			<ul>
				<li>test1</li><li>test2</li><li>test3</li>
			</ul>
		</textarea>
```
Then it no longer freezes when I remove bullets from the whole list at once.

**Comment by taekvideo** [comment]
More specifically it seems it's just the whitespace after the < ul > tag that's needed, even adding a single space works
```
<textarea id="test" style="width: 500px; height: 250px;"><ul> <li>test1</li><li>test2</li><li>test3</li></ul></textarea>
```

**Comment by samclarke** [comment]
I've just tried without spaces and still can't get it to happen.

[This](https://dl.dropboxusercontent.com/u/56830471/bulletlist.ogv) is what I'm doing, am I doing anything differently? Also do you have any event handlers or any settings that are different from mine?

**Comment by taekvideo** [comment]
That's the right procedure but I'm not using the /tests/manual/debug thing, not sure what that is.

I uploaded it to a live server if you want to try it there.
http://drawtest.breakthroughbasketball.com/test.html
http://drawtest.breakthroughbasketball.com/test3.html

The first one freezes in chrome when you select the list and click the button, but the second one has the space added so it doesn't freeze.

**Comment by taekvideo** [comment]
Here's another example showing how the .val() breaks it... I'm guessing it removes the spacing after the < ul > or something like that.

http://drawtest.breakthroughbasketball.com/test4.html
```
<!DOCTYPE html>
<html>
    <head>
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/jquery.sceditor.min.css" media="all" />
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/themes/default.min.css" media="all" />
		
		<script type="text/javascript" src="lib/jquery-1.11.1.js"></script>
		<script type="text/javascript" src="lib/SCEditor/minified/jquery.sceditor.min.js"></script>
    </head>
    <body>
		<a href="#" onclick="getSceditorVal()">Break Me</a> <br /><br />
		<textarea id="test" style="width: 500px; height: 250px;">
			<ul>
				<li>test1</li>
				<li>test2</li>
				<li>test3</li>
			</ul>
		</textarea>
        <script>
			$(function(){
				$("#test").sceditor({
					style: 'lib/SCEditor/minified/jquery.sceditor.default.min.css',
					toolbar: 'bulletlist',
				});
			});
			
			function getSceditorVal(){
				var test = $("#test").sceditor('instance').val(); //just read the val, don't even do anything with it.
			}
        </script>
    </body>
</html>
```

If you just select the list and keep clicking the toolbar button it works fine, but if you click "break me" when there's a list in the box... that calls a function which just reads the .val(), and then clicking the toolbar button with the list selected will freeze it.

**Comment by samclarke** [comment]
Got it, removing the BBCode plugin causes it to happen.

**Comment by brunoais** [comment]
@taekvideo Try doing again without searching the DOM in the "break me" callback

**Comment by taekvideo** [comment]
With bbcode it works the same, if you don't have spacing between the [ul] and first [li] tag it freezes.

And do you mean storing the instance when you initialize the sceditor?
```
<!DOCTYPE html>
<html>
    <head>
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/jquery.sceditor.min.css" media="all" />
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/themes/default.min.css" media="all" />
		
		<script type="text/javascript" src="lib/jquery-1.11.1.js"></script>
		<script type="text/javascript" src="lib/SCEditor/minified/jquery.sceditor.min.js"></script>
    </head>
    <body>
		<a href="#" onclick="getSceditorVal()">Break Me</a> <br /><br />
		<textarea id="test" style="width: 500px; height: 250px;">
			<ul>
				<li>test1</li>
				<li>test2</li>
				<li>test3</li>
			</ul>
		</textarea>
        <script>
			var instance = null;
			$(function(){
				instance = $("#test").sceditor({
					style: 'lib/SCEditor/minified/jquery.sceditor.default.min.css',
					toolbar: 'bulletlist',
				}).sceditor('instance');
			});
			
			function getSceditorVal(){
				console.log(instance.val());
			}
        </script>
    </body>
</html>
```
I tried like that and still happens.

**Comment by samclarke** [comment]
I can't reproduce it with the BBCode plugin but I can without it. I'm still trying to work out what's causing it.

**Comment by taekvideo** [comment]
```
<!DOCTYPE html>
<html>
    <head>
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/jquery.sceditor.min.css" media="all" />
		<link rel="stylesheet" type="text/css" href="lib/SCEditor/minified/themes/default.min.css" media="all" />
		
		<script type="text/javascript" src="lib/jquery-1.11.1.js"></script>
		<script type="text/javascript" src="lib/SCEditor/minified/jquery.sceditor.bbcode.min.js"></script>
    </head>
    <body>
		<textarea id="test" style="width: 500px; height: 250px;">[ul][li]test1[/li][li]test2[/li][li]test3[/li][/ul]</textarea>
        <script>
			$(function(){
				$("#test").sceditor({
					style: 'lib/SCEditor/minified/jquery.sceditor.default.min.css',
					toolbar: 'bulletlist',
					plugins: 'bbcode'
				});
			});
        </script>
    </body>
</html>
```

That's the code I used to reproduce it with the bbcode plugin
http://drawtest.breakthroughbasketball.com/test5.html

**Comment by samclarke** [comment]
Disabling emoticons by setting the `emoticonsEnabled` option to false seems to prevent the infinite loop for me. Could you check and see if that prevents it for you?

**Comment by taekvideo** [comment]
Yes it does!

**Comment by brunoais** [comment]
https://github.com/samclarke/SCEditor/issues/442#issuecomment-102002787
^ Please try it.

**Comment by taekvideo** [comment]
Hmm it fixes it for the ones which lacked the space between <ul><li>.... but it still freezes on the ones that call .val() (with the "break me" link

**Comment by taekvideo** [comment]
@brunoais I tried that in the comment below yours, with the instance stored, and just doing instance.val()

**Comment by brunoais** [comment]
Same result?

**Comment by taekvideo** [comment]
Yeah didn't change anything.
http://drawtest.breakthroughbasketball.com/test6.html
Also disabling emoticons doesn't help on these either, though it did fix the earlier tests which didn't have space betweeen < ul > and < li >

**Comment by samclarke** [comment]
I think I've managed to simplify the bug down to this: http://jsfiddle.net/b6L24wos/

Could you see if that causes an infinite loop for you?

**Comment by brunoais** [comment]
It doesn't for me. The formatting breaks but it works correctly

**Comment by taekvideo** [comment]
Yeah if I select the list and click crash it freezes up

**Comment by brunoais** [comment]
Now I know how to crash a Chrome when I don't want one on my website :D

**Comment by samclarke** [comment]
Yes, this is a WebKit bug. I think I've found a way to work around it though, could you see if [this fixes](http://jsfiddle.net/d4atm62e/) it for you.

**Comment by taekvideo** [comment]
crashing chrome is a lot easier than that, just do 
```
while(window.chrome);
```


lol and yeah it doesn't seem to freeze but what's different on it?

**Comment by samclarke** [comment]
Great! I think I'll have to release a new version as it's quite a bad bug if it happens.

**Comment by brunoais** [comment]
@taekvideo Except that code is insuspicious
