### ISSUE TITLE
No proper checks are being made to load SCE into source mode only

### ISSUE THREAD

**Issue by brunoais** [samclarke/SCEditor#444]
If `runWithoutWysiwygSupport` or `isWysiwygSupported` states that WYSIWYG is not supported, it shouldn't assume that both modes are not supported.
Instead, it should lockdown on source mode and not allow switching to WYSIWYG mode.

**Comment by samclarke** [comment]
That's what it does. If `isWysiwygSupported` is `false` then it will lock the editor into source mode if `runWithoutWysiwygSupport` is `true` or disable the editor if `runWithoutWysiwygSupport` is `false`.

If `isWysiwygSupported` is `true` then the value of `runWithoutWysiwygSupport` is ignored..

**Comment by brunoais** [comment]
Found it!
It is still a bug because it is not properly implemented... There's code removal missing :S... I'll patch it up.

**Comment by samclarke** [comment]
Fixed by PR #446
