### ISSUE TITLE
How to validate an empty textarea?

### ISSUE THREAD

**Issue by cborchmann** [samclarke/SCEditor#447]
Hallo,

i try to validate a filled textbox. I found a strange behavior comparing the empty sceditor textarea between Firefox and Chrome. When switching to source mode the following html code is in the box:

Firefox

```
<span class="sceditor-selection sceditor-ignore" style="line-height: 0; display: none;" id="sceditor-end-marker"> </span><span class="sceditor-selection sceditor-ignore" style="line-height: 0; display: none;" id="sceditor-start-marker"> </span><p><br></p>
```

Chrome

```
<p><br></br></p>
```

It´s difficult to validate before submitting the form, using https://github.com/victorjonsson/jQuery-Form-Validator or to do it serverside after submitting.

Any hints or ideas ?

Thank you

Christian

**Comment by brunoais** [comment]
Are you using SCE without plugins?
SCE's own textarea is not for you to read as having the correct value. The one for you to read is the textarea that is yours and to which SCE was directed to enhance.

**Comment by cborchmann** [comment]
Hallo,

i only use the xhtml plugin...

**Comment by brunoais** [comment]
On which textarea are you getting the value on?

**Comment by CanRau** [comment]
I'm getting this line of code when switching to source mode on an empty editor

**Comment by brunoais** [comment]
Correct. HTML makes no sense in BBCode, so in that mode, empty no text means empty contents.
I think that should be the way to validate. Just do a `textareaNode.textContent.trim()`. If it is empty, it is empty.

**Comment by CanRau** [comment]
Thanks but I switched back to bbcode, feels cleaner for the users

**Comment by rodrigofolco** [comment]
ok
