### ISSUE TITLE
Better support for custom emoticons location

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#449]
It seems currently when you set your emoticons root the script automatically appends the "emoticons" word onto the end, so if I do this:

`$(".sceditor").sceditor({
	emoticonsRoot: '../../images/'
});`

Then the directory will end up being: `../../images/emoticons/`

Can this be changed (or at least an option added) where you can provide the full path yourself and not have this append anything?

I'm trying to set a situation where there can be multiple smiley "sets" and having this append like this makes it very difficult as I cannot then do something like this:

images/emoticons/
    /deafult/
    /set2/
    /set3/

I would have to do..

images/default/emoticons/
....

OR

images/emoticons/default/emoticons/
.......

both of which don't make much sense.

Cheers!

**Comment by cyphix333** [comment]
I guess this is only an issue when using the default emoticons as I noticed it appends the 'emoticons' term at the start of each smiley. I have now set my own custom emoticons and hence can easily set them up how I like :)

**Comment by ITwrx** [comment]
IMHO, this behavior is still counter-intuitive. the docs say "Root URL of all emoticons. This string will be prepended to all emoticon URLs." it doesn't say "the root url for the emoticons directory". it says "all emoticons". that means the images/emoticons themselves, which means the user should add the emoticons directory to their supplied url. furthermore, it is more usual when adding paths like this to supply the full path, not stop one directory before the end of the path and expect the script to add the last directory. either the behavior or the docs should change, imo. i would change the behavior.
thanks
