### ISSUE TITLE
iPad Typing Issue

### ISSUE THREAD

**Issue by techpulse** [samclarke/SCEditor#450]
When I type it creates lag and delay which confuses my auto correct and makes it difficult to type. Deleting is worse because I hit delete a few times and it keeps deleting backwards longer than expected...sometimes deleting several words back.

**Comment by brunoais** [comment]
Is that in both WYSIWYG mode and source mode?
Does that happen also in http://www.sceditor.com/ ?

**Comment by brunoais** [comment]
No answer in 7 days, closing.
