### ISSUE TITLE
Smilies - "More" shown even if there are no more smilies to display

### ISSUE THREAD

**Issue by Destroy666x** [samclarke/SCEditor#453]
As the title says, would be nice to hide it when it's not needed.

**Comment by brunoais** [comment]
How are you setting up the smilies?

**Comment by Destroy666x** [comment]
By just using the `emoticons` option object.
1. If `more` is blank:
`more: {

}`
the "More" button is shown.
2. If `more` is completely skipped in the `emoticons` option, the "More" button is still shown. 

`emoticonsCompat` is on, if that matters, but it most likely doesn't. 1.4.7.
