### ISSUE TITLE
Setting new height of editor via API doesn't change height of iframe

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#455]
I wanted to change the height of the editor on focus so I did this:

`$('.sceditor').sceditor('instance').focus(function(event) {
    $(this).height(225);
});`

Height _appears_ to change fine, that is until you enter in too much content and notice the scroll hasn't extended. It seems it changes the height of the container, but not the iframe and hence you still get scrolling at the normal height.

**Comment by cyphix333** [comment]
Just wanted to update that I got this working correctly by paying attention to what the `expandToContent` does and the following worked for me:

`
$('.sceditor').sceditor('instance').focus(function(event) {
	$(this).children('iframe').first().height(200);
	$(this).children('textarea').first().height(200);
});
`

**Comment by samclarke** [comment]
This has been fixed by the style update (24959709f94c3a31b173b0247e03c65f66c0ea81) which will be in v2.0.

**Comment by cyphix333** [comment]
Excellent - V2 is sounding like a beauty! 👍
