### ISSUE TITLE
.focus() causes firefox page to scroll on loading

### ISSUE THREAD

**Issue by martec** [samclarke/SCEditor#456]
Samething of #245 
Issue above returned in 1.4.7 in FF.

I checked code here and because of this line https://github.com/samclarke/SCEditor/blob/master/src/lib/SCEditor.js#L1785 when i remove this line, all ok here.

And what minifier tool used in SCEditor?

**Comment by brunoais** [comment]
Ah yeah... That instruction is meant to solve a different bug related to the caret itself... I'm still not sure if to use it or not use it...

[UglifyJs](https://github.com/samclarke/SCEditor/blob/master/Gruntfile.js#L373)

**Comment by martec** [comment]
Thanks @brunoais

it is quite annoying. I hope it is resolved as soon as possible.

**Comment by samclarke** [comment]
I think that line is only needed for IE so it should be able to be moved to the other IE code. I'll test it tomorrow to check.

**Comment by martec** [comment]
@samclarke 
thanks for fast reply...
if only need for IE... so almost resolved.

**Comment by samclarke** [comment]
Closing as this appears to have already been fixed.
