### ISSUE TITLE
No info about jquery version required

### ISSUE THREAD

**Issue by danilychen** [samclarke/SCEditor#458]
I use jquery version 1.7, upgrade sceditor from 1.4.3 to 1.4.7 version. Some features of sceditor is broken with jquery 1.7.

Did not find any information about required jquery version. Can you please write it in source file or readme?

**Comment by brunoais** [comment]
Which features broke?

**Comment by live627** [comment]
The example uses 1.11

https://github.com/samclarke/SCEditor/blob/master/example/example.html#L10

**Comment by samclarke** [comment]
Currently the minimum jQuery version is 1.8.0.
