### ISSUE TITLE
Copy Paste issue In sceditor.

### ISSUE THREAD

**Issue by GouriSancroj** [samclarke/SCEditor#461]
Firstly When I try to copy bulleted content in sceditor , only content used to display in the editor without the bullets. So , to resolve this I have set "enablePasteFiltering to true" and "runWithoutWysiwygSupport to true". It worked fine.

But When I set "enablePasteFiltering to true" and "runWithoutWysiwygSupport : true" , Copy paste from word is not working. The formatted content which is in word , I tried to paste in sceditor only content is displaying without the formatted styles. 

Please help me out so that both should work .
Help would be appreciated. 
Thank you in Advance.

**Comment by brunoais** [comment]
If you deactivate the WYSIWYG mode, it won't be available so you can't use it.
What is your objective? You write a lot of information but I can't get what you want with all of that.

**Comment by samclarke** [comment]
Closing as needs info.
