### ISSUE TITLE
Appending "said:" to cite tag within blockquote whilst supporting i8ln

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#462]
I noticed when you use the `quote` tag such as:

`[quote=username]some text[/quote]`

That it will create a `blockquote` with a `cite` within it, where the cite will just contain the username. However I was wanting to extend this so it would be like: `<cite>username said:</cite>`; sure, this is easy enough as I can just replace the default implementation with a new bbcode with the same name so as to override the default one, however I need to support internationalization and I'm not sure how to write the code so the word `said` will be translated.

How can this be done? ... either that or I would love to see the default implementation add this.

Thanks!

**Comment by cyphix333** [comment]
Ok I understand I would need to use the `_()` function, but just not sure how to correctly call it within a new custom bbcode object.

**Comment by brunoais** [comment]
Why not do that in CSS?

**Comment by cyphix333** [comment]
You mean using `:after` in CSS to input content? Well, because it really doesn't belong there tbh and secondly because I need to support internationalization; ScEditor supports that out of the box, so why not take advantage of it?
