### ISSUE TITLE
Can i use it without bbcode plugin ?

### ISSUE THREAD

**Issue by carles9000** [samclarke/SCEditor#463]
Hi,

First of all congratulate the author of this plugin, i like it !!!

I will try to summarize as short as possible. I tried to create an example from example.html to explain the problem

I put

			$(document).ready(function() {
			
				var initEditor = function() {
					$("textarea").sceditor({
						style: "./minified/jquery.sceditor.default.min.css"
					});
				};			

				initEditor();
				
				alert( $("textarea").sceditor("instance").val() );
				
			});

without using the plugin bbcode.

In the definition of the textarea, simply i write

           <textarea name="bbcode_field" style="height:300px;width:600px;">Hello without bbcode</textarea>

and finally run the alert () shows me the textarea and content:

       <span class="sceditor-selection sceditor-ignore" style="line-height: 0; display: none;" id="sceditor-end-marker"> </span><span class="sceditor-selection sceditor-ignore" style="line-height: 0; display: none;" id="sceditor-start-marker"> </span>Hello without bbcode

It shows me a dirty content. I'm thinking I would have to see only "Hello without bbcode". Maybe I need to initialize or put something?

Thanks for advance four your help.

Carles

**Comment by brunoais** [comment]
Try using the xhtml plugin, then.

**Comment by carles9000** [comment]
brunoais,

Now it's ok, thanks !

Carles
