### ISSUE TITLE
Can we add a CSS class for inserted smileys?

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#467]
Situation: 
1. I have a forum where all images get a border and 5px padding to make them more visible.
2. Some users want to use emoticons.
3. All emoticons are rendered with border and 5px padding as well, since they are images. 

Is there the chance to give thg img of emoticons an extra class, such as `.sc-emoticons`? This way I could assign other CSS to them.

Thx in advance.

**Comment by Destroy666x** [comment]
This would be nice to have indeed. Either a predefined class or a class configurable in options.

**Comment by brunoais** [comment]
Why not use the `[data-sceditor-emoticon]` selector?

**Comment by Destroy666x** [comment]
That attribute isn't applied to smilies in the selector and a class is always better for styling (more comfortable at least).

**Comment by q2apro** [comment]
@Destroy666x +1 absolutely correct from my POV.

**Comment by brunoais** [comment]
> That attribute isn't applied to smilies in the selector

I didn't understand that part of the sentence.

> a class is always better for styling (more comfortable at least)

I don't get why. Both are equally valid ways...

**Comment by Destroy666x** [comment]
> I didn't understand that part of the sentence.

There's a dropdown smilie selector in SCEditor's toolbar.. Listed smilies don't have the mentioned HTML attribute if you inspect them.

**Comment by brunoais** [comment]
Oh! I get it... SO you want it in the smilies not only in the WYSIWYG document but also in the toolbar... OK.

**Comment by Destroy666x** [comment]
One class is usually more practical than few comma separated selectors (one of them being based on HTML attribute) indeed.

**Comment by samclarke** [comment]
Given the use case I'm not sure this is worth adding as I can't see it being used much.

The CSS to remove borders is:
```css
.sceditor-container img, img[data-sceditor-emoticon] {
    border: 0;
}
```
Which looks clean enough to me versus adding extra classes to the HTML output. For targeting individual emoticons using `img[src="emoticon-url.jpg"]` seems simple enough too.

Feel free to re-open if you think I've missed something.
