### ISSUE TITLE
resize issue with <fieldset>

### ISSUE THREAD

**Issue by KN4CK3R** [samclarke/SCEditor#468]
First the code: http://pastebin.com/BNph21si

If you resize the browser window the editor doesn't resize properly. It always grows even if you make the window smaller. If you change the fieldset tag to div all works like it should.

See screenshot for details: http://abload.de/img/testgqudp.jpg

**Comment by brunoais** [comment]
`.fail` is not resizing. SCE is following it accordingly.
Make sure that the `<body>` and `<html>` are not being larger than the screen.

**Comment by KN4CK3R** [comment]
What do you mean by ".fail is not resizing"? The fieldset resizes properly if text is involved:
http://abload.de/img/testavsn3.jpg
or a textarea with width:100%
http://abload.de/img/testtrsgx.jpg

It only doesn't work if you use the sceditor on that field. Have you seen the first screenshot? The sceditor grows bigger and bigger even if you make the window smaller.

**Comment by brunoais** [comment]
There you go, nothing to do with SCE :).
