### ISSUE TITLE
xhtml-plugin: deletion of empty cells in table

### ISSUE THREAD

**Issue by derplakatankleber** [samclarke/SCEditor#470]
The issue is that the xhtml plugin removes empty cells in tables, when I try to get the html content of the textarea.

Setting: The normal SCEditor with xhtml plugin. I create a table with multiple rows and columns. I add some content in some cells. The last step is, to call the val-function from the sceditor to get the content of the textarea.

see testcase in github or fiddle: 
http://derplakatankleber.github.io/bugfix/testpage.htm
http://jsfiddle.net/smjmLap5/4/
=> click on "Click to see textarea sourcecode"

Env: IE 10 with Win7

Problem: In the method "signalToSource" is a call to "removeTags", where the plugin removes blacklisted, not whitelisted or empty elements. The problem is, that this time the plugin should not remove the empty "td"-elements in my table, because the IE 10 creates a table with empty cells (without "br" elements, see IE_BR_FIX).

Possible fixes that a see:
1. Allow an exception to the "remove empty elements" rule for some elements like table cells.
2. The problem does not exist in chrome or firefox or IE 11, because the editor creates a "br"-Tag in every cell, when the table is created (see IE_BR_FIX for create table). So the "td"-element is not empty and the plugin don't delete the cell. A workaround could be to write a non visible element in the cell. 
for example: (IE_BR_FIX ? '' : '<br />')

Better solution to the problem are welcome.

PS: To deactivate the filter of the plugin is also a solution, but that would also deactivate some useful feature of the xhtml plugin.

**Comment by derplakatankleber** [comment]
The feature from ticket #475 would be sufficient to solve the issue.
The problem with that solution is to define a useful default value.

**Comment by samclarke** [comment]
Should be fixed in v2. Thanks for reporting!
