### ISSUE TITLE
Move cursor to start of editor?

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#471]
I'm creating an editor and filling it with content, but when the editor shows the cursor is placed at the end of the content - is there any way to get to the start of the editor?

**Comment by brunoais** [comment]
I don't think there's an API for it...

**Comment by marksyzm** [comment]
There's a property for it in the options: `autofocusEnd`
http://www.sceditor.com/documentation/options/

**Comment by samclarke** [comment]
There's no API to do this. The range helper can set cursor position based on html markers though.

If you insert this HTML where you want the cursor to be:

```html
<span id="sceditor-start-marker" style="line-height: 0; display: none;"> </span><span id="sceditor-end-marker" style="line-height: 0; display: none;"> </span>
```

and then call:

```js
instance.getRangeHelper().restoreRange();
```

It will set the selection start and end to the markers position.
