### ISSUE TITLE
IndexSizeError on init in IE11

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#472]
When you put [img] tag in IE11 as content you get on IndexSizeError in base.selectedRange at if(isW3C) range = sel.getRangeAt(0);. This stops execution of scripts and Sceditor is not able to do the callback binding for submit event and updating of textarea on submit event will not be done and the original content goes back to the server and new user input is lost.

So the use case was:
User is using IE11 and version 1.4.6 of Sceditor.
1. User takes a printscreen of a website with Alt+PtrScn
2. User pastes the image into Sceditor and writes his/her message
3. User clicks save
4. Server complains to the user that his/her message was too long
5. User deletes the image
6. User clicks save again
7. Server complains to the user that his/her message was too long with the same length as the first message on first save attempt.
8. Repeat point 5 until frustration...
 
HTML content on page reload:
<textarea>[img]data:image/png;base64,iVBORw0KGgoAAAAN...[/img]</textarea> 

Currently we are using 1.4.6 version of Sceditor. The same error occurred with dev-sources as well as minified scripts. This is only an IE11 problem but it's a tricky problem because you really can't disable copy/paste from IE. You could do some trickery with javascript but the user can disable javascript, so what can we do. Here's a screenrecord on how to replicate the problem. 

![ie11indexerror](https://cloud.githubusercontent.com/assets/6572543/9324199/c0d8221e-4590-11e5-8f8e-3c26a19cc7dd.gif)

**Comment by Destroy666x** [comment]
https://github.com/samclarke/SCEditor/issues/361
Also, there was a fix for a similar range issue here: 
https://github.com/samclarke/SCEditor/issues/451

**Comment by brunoais** [comment]
Sounds like the checks it does in the script some instructions before are not being executed properly for some reason.
I have no idea if I have time for this in the near future btw... I'll see what I can do if Sam doesn't come.

**Comment by jetand** [comment]
Changing if(isW3C) to if(isW3C && sel.rangeCount > 0) like what is done in here https://github.com/samclarke/SCEditor/issues/361
seems to fix the problem. No more errors in IE11 and now the textarea updates on submit and the user can get rid of the large image that prevents him/her from sending the message.

**Comment by brunoais** [comment]
Send a PR and I'll merge it ^^.

**Comment by jetand** [comment]
My branch is very much out of date sorry... Can you cherry pick my commit?

**Comment by jetand** [comment]
I updated my branch to samclarkes master branch I hope my pull requests is OK and my master is now up to date. Sorry, I'm quite new to github and I haven't done many commits.

I used to do on local machine
$ git fetch upstream
$ git merge upstream/master
but I think that was wrong and only updated my local from my server branch which were of course the same...
$ git pull https://github.com/samclarke/SCEditor.git
seemed to do better job updating :)
