### ISSUE TITLE
Code vanishes

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#475]
After inserting the following HTML code into source and toggle back to view it completely vanishes. Like if SCEditor strips it completely.

```
      <div class="icon-wrapper">
        <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x" style="color: #128bae;"></i>
          <i class="fa fa-briefcase fa-stack-1x" style="color: #fff;"></i>
        </span>
      </div>
```

**Comment by brunoais** [comment]
Which plugins do you have activated?

**Comment by timint** [comment]
<script src="/ext/sceditor/jquery.sceditor.xhtml.min.js"></script>
<script src="/ext/sceditor/plugins/format.js"></script>
<script src="/ext/sceditor/languages/sv.js"></script>
<link href="/ext/sceditor/themes/square.min.css" rel="stylesheet" />
<script>
  $("textarea[name='content[sv]']").sceditor({
    "plugins": "xhtml,format",
    "width": 1024,
    "resizeEnabled": true,
    "style": "/ext/sceditor/jquery.sceditor.default.min.css",
    "locale": "sv",
    "emoticons": false,
    "toolbar": "format|font,size,bold,italic,underline,strike,subscript,superscript|left,center,right,justify|color,removeformat|bulletlist,orderedlist,table|code,quote|horizontalrule,image,email,link,unlink|youtube,date,time|ltr,rtl|print,maximize,source"
  });
</script>

**Comment by brunoais** [comment]
Any errors in the console?
What about if you remove the format plugin? Does it seem to solve it?

**Comment by timint** [comment]
No errors in console. Happens even without format loaded and defined.

**Comment by brunoais** [comment]
How about if you remove both plugins?
I guess it is removing those `<i>` because they are inline tags and they empty... I do want to make sure, though.

**Comment by timint** [comment]
The problem seems to be in the xhtml plugin. Without it no trouble.

**Comment by brunoais** [comment]
https://github.com/samclarke/SCEditor/blob/master/src/plugins/xhtml.js#L716
https://github.com/samclarke/SCEditor/blob/master/src/plugins/xhtml.js#L779

Yep. If the tag has no content, it is removed by default... I believe I can change that so that tags can be configured somehow... I'll think on how to do it right... Warn me back if I don't reply anything in 2-3 weeks (just to make sure I don't forget)

**Comment by hammat** [comment]
Hi, I know this is an old issue but still opened. 

Did you found a solution to avoid empty tags to be removed ?

**Comment by samclarke** [comment]
Should be fixed in v2. Thanks for reporting!
