### ISSUE TITLE
Windows10 Edge browser Return key problem

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#477]
In the new Windows10 Edge browser hitting Return does not seem to create a new paragraph. When you hit Return key the cursor goes to the start of the paragraph and looks like it had no effect. But if after hitting the Return key you move down with the arrow down key you see start to see the new paragraph. This can be reproduced in the sceditor.com demo.

Most probably the fault is with the Edge browser but sadly that's not how the users see it so we need to create a workaround if Microsoft doesn't fix their browser soon enough or at all.

**Comment by brunoais** [comment]
Any errors in the browser's console?
I don't have Edge yet. I have no means to test it.

**Comment by jetand** [comment]
No errors in console. This is the DOM when I type "laaa laaa laaa" and Return.
![edge_dom](https://cloud.githubusercontent.com/assets/6572543/9513571/325fb5ae-4c9a-11e5-80bf-a537c0f1c631.png)

**Comment by jetand** [comment]
Any update on this. We've been getting more and more of these reports.

**Comment by brunoais** [comment]
It seems like the dummy `<br>` is not being inserted, for some reason.
If Sam has Edge, he should be of a much better help than me. I don't have/use it.

**Comment by jetand** [comment]
Ok thanks. Can you give the expected HTML-structure of "laaa laaa laaa" and Return key and some pointers where in the code the <br> is supposed to come from?

Chrome gives different DOM:
![body](https://cloud.githubusercontent.com/assets/6572543/9897703/3816ec64-5c54-11e5-9c30-f2e281dea15f.png)

**Comment by brunoais** [comment]
That `<br>` is meant to force the caret to display in the right place. It is also required by chrome, otherwise it is unselectable.

**Comment by jetand** [comment]
I see. And then the br tag is removed when the user types in more stuff in the new paragraph. Correct?

**Comment by jetand** [comment]
I don't know if this is related to this but. But first in chrome there are p-tags and if you select all hit backspace two times and start typing then the elements that appear in the body are divs.
![recording](https://cloud.githubusercontent.com/assets/6572543/9926143/88d5cd7e-5d1b-11e5-8547-c220f844e1d9.gif)

**Comment by bfmarkymark** [comment]
i have this Problems too on my fanpage. IE is going (can use it) but the original one in Windows 10 edge has Problem with return key.
