### ISSUE TITLE
Sc Editor image Pasting not working in ie10

### ISSUE THREAD

**Issue by Vigneshwarnatarajan** [samclarke/SCEditor#478]
For Example, i'm taking the printscreen, pasting it in mspaint and then tried to paste that in sceditor textarea but it is not working. 

Is there any option to do that. pls explain to me.

thanks

**Comment by jetand** [comment]
You could try pasting directly to the sceditor after taking the screenshot. No need to go through mspaint unless you need to edit your screenshot.

**Comment by Vigneshwarnatarajan** [comment]
Yes i tried that directly in www.sceditor.com from ie10  but the image is not pasted in the website also.
i even tried with chrome version 44.0.2403.157.

**Comment by jetand** [comment]
Now that I think about this. Have you checked in the sceditor documents is the pasting of images a supported feature? I think that is not even supported.

**Comment by Vigneshwarnatarajan** [comment]
So far i have used Mozila Firefox and IE11 in  my application. in this two browsers i can able to copy paste the image from mspaint. Now i tested my application in chrome ,IE10 and in windows  10 Microsoft Edge,it is not working. In the sceditor documents, it is not specified whether it supports 
pasting of images or not.

**Comment by brunoais** [comment]
This is a feature that the browser has, not the editor. Currently, the editor does nothing to prevent browser's native features to be usable.
Regardless...
See: #391

**Comment by Vigneshwarnatarajan** [comment]
Thanks for your Replies
