### ISSUE TITLE
3 Small Questions

### ISSUE THREAD

**Issue by engineertdog** [samclarke/SCEditor#479]
URL for an example of the issues:
https://www.dota2reborn.net/test/editor.php

1) When you click on view source, it makes all of the text bold for some reason (it works as it should, but this is peculiar).

2) I can't get the user to focus on the editor by clicking anywhere in the editor. They have to click near the top. I have a jQuery event that puts focus to the field when the editor's parent TR is hovered, but that's not the best solution.

3) The background highlighting of the toolbar items does not work. I haven't edited the CSS other than to make it readable.

I'm not sure if they're problems being caused by conflicting scripts / CSS or what the deal is. But the editor itself works as it should. It just has these 3 flaws for some reason.

**Comment by brunoais** [comment]
1. Unrelated to SCE. Read your CSS.
2. Remove that quirk first, then I'll look at it in your environment.
3. I don't know what is that "background highlighting" :S. Please send a print screen showing what you mean.

**Comment by engineertdog** [comment]
1) Fixed this CSS issue. Opened the CSS file (which I've already done to re-organize the content), uploaded it, and it was fine.

2) I'd like for users to click on the textarea and focus it, like what the forums do. Not sure why it's not.

3) Notice how active (and hovered) buttons on the toolbar have a different background color, to show they're active / being hovered?
http://www.sceditor.com/

It's not doing that with any of my editors for some reason.

4) Try to use cite / quote on my editor. In the editor itself, it's not showing the CSS for it. But it renders with PHP just fine.

**Comment by brunoais** [comment]
1. OK
2. First remove the hover quirk, then I can test your case.
3. It is working for me. On which browser(s) is it not working?
4. There's no CSS defined for `<blockquote>` in that SCE instance's stylesheet. What are you trying?

**Comment by samclarke** [comment]
Closing as needs info.
