### ISSUE TITLE
Feature Request: base64 encoded images

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#481]
LiteCart users repeatingly contact me asking if it's possible to 'upload' images via the SCEDitor. As uploading requires server side coding I'm thinking it would be convenient to implement support for base64 encoded images.

Simply:
1. Click a button for a new image. 
2. Browse for the file and click ok.
Done.

Example result:

    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

Resource:
http://stackoverflow.com/questions/17710147/image-convert-to-base64

**Comment by brunoais** [comment]
#391 <- Thereby; closing.
