### ISSUE TITLE
How to move the margin on SCEDITOR when in full screen mode?

### ISSUE THREAD

**Issue by ollie007** [samclarke/SCEditor#483]
How do i move the margin on SCEDITOR down when in full screen mode?

My header is getting in the way of the editor, SO I would like to move the RTE down a little, BUT ONLY when in fullscreen

thanks

**Comment by samclarke** [comment]
The class `sceditor-maximize` is added when in fullscreen mode.

To move SCE down would be something like:
```css
.sceditor-maximize {
    top: 100px;
}
```
