### ISSUE TITLE
Parsing smileys with descendent lenght?

### ISSUE THREAD

**Issue by margarett** [samclarke/SCEditor#492]
Hi.

If we have smileys with similar codes, where one is part of another, the lengthier one fails to render properly when switching from code to WYSIWYG mode. Example:
:(  >:( 

When switching in and out of code mode, it becomes
![img1](https://cloud.githubusercontent.com/assets/5584935/11601944/9ff01c94-9ace-11e5-8bd9-602a07f7514c.png)

**Comment by brunoais** [comment]
Try [emoticonsCompat](http://www.sceditor.com/documentation/options/) option and give feedback please.
If it works, it is a temp workaround while a solution is thought and it is also a good starting step to get a solution.

**Comment by margarett** [comment]
Thank you for your reply. However ,emoticonsCompat was already set to true. Tried with false just in case, the behavior is the same.

**Comment by brunoais** [comment]
OK, got it. I've been **super** busy but if Sam doesn't solve this, I'll work on it. Please do not expect a quick solution, though.
