### ISSUE TITLE
Error on setValue

### ISSUE THREAD

**Issue by stefanhi** [samclarke/SCEditor#494]
There's a bug in the SCEditor. If you try to setValue to the wysiwyg-editor, the body-field is empty and no longer editable.

You can check this in the example provided in the jdorn json editor example "wysiwyg.html". 

<img width="499" alt="bildschirmfoto 2015-12-14 um 12 41 42" src="https://cloud.githubusercontent.com/assets/16288461/11780149/26ec59c2-a260-11e5-956f-900544f1402e.png">

If you click on "Edit JSON" in this example, then change value of "title" and "body"

<img width="483" alt="bildschirmfoto 2015-12-14 um 12 42 01" src="https://cloud.githubusercontent.com/assets/16288461/11780159/36c81e80-a260-11e5-9026-e050fc56c756.png">

 click on "save" and the value for "title" will be printed. But there's no value for body in the editor. 

<img width="477" alt="bildschirmfoto 2015-12-14 um 12 42 10" src="https://cloud.githubusercontent.com/assets/16288461/11780164/4191c6b8-a260-11e5-9bc4-3e332f1d35fe.png">

If you try to click on the body-field, no longer the curser will appear.

Thanks in advance and feel free to ask if you've further question.

**Comment by brunoais** [comment]
What is this example? I can't find that file in the project

**Comment by stefanhi** [comment]
You'll find the example here: https://github.com/jdorn/json-editor/tree/master/examples

**Comment by brunoais** [comment]
That is using a very old SCE version. Do try it again on an updated version.

**Comment by stefanhi** [comment]
We use the latest SCE version from www.sceditor.com.

**Comment by brunoais** [comment]
@samclarke Please update the zip file with the latest SCE. There has been many updates since January!

**Comment by brettz9** [comment]
FYI, In migrating JSON Editor 0.7.22 to 0.7.28, I'm now seeing problems with `editor.getValue()` not working with SCEditor fields (though they do show up as such).

**Comment by brettz9** [comment]
Also, after adding a field via "Object Properties", other SCEditor fields no longer work.

**Comment by brettz9** [comment]
Sorry, my comments were mistaken (the problem was with jQuery). But I am indeed still seeing a problem with JSONEditor and "Object Properties".

**Comment by brettz9** [comment]
Also, FWIW, I'm getting many errors on load after this line 437 of `src/lib/SCEditor.js`:

```js
doc = getWysiwygDoc();
doc.open(); // doc is undefined
```

**Comment by samclarke** [comment]
Thanks for reporting! I'm closing as this appears to have been fixed a while ago. If you're still getting the error please reopen it or create a new issue.
