### ISSUE TITLE
Sceditor doesn't invoke updateOriginal() in selenium tests

### ISSUE THREAD

**Issue by mhiemstrapodiumtv** [samclarke/SCEditor#495]
I am using sceditor to edit BBCode. When I visit the website I can edit the bbcode, post the data and everything works fine. When I use selenium the sceditor doesn't invoke updateOriginal()!

In my selenium tests I need to insert raw data so I click on the view source button, insert the raw bbcode and then click on the view source button again. This works fine. 

Then when I click on the button that posts the data the inserted bbcode isn't posted! To fix this I now execute javascript in my selenium tests. I execute the following command:

```
$('mySceditor').each( function() { $(this).sceditor('instance').updateOriginal(); });
```
mySceditor is a class I give to all textarea's that are initialized with sceditor. 

I don't get a javascript error in my browser so updateOriginal has been called. Yet when I post the data by clicking on the send button the original textarea hasn't been updated!! This only happens in selenium tests.

**Comment by marksyzm** [comment]
`$('mySceditor')` - that's not a class?

**Comment by mhiemstrapodiumtv** [comment]
That did it :+1: 

For people wanting to do selenium tests using sceditor you can use the following code to make sure that the sceditor is updated.

```
( (JavascriptExecutor) SeleniumTest.driver ).executeScript ( "$('.sceditor').each( function() { $(this).sceditor('instance').updateOriginal(); });" ); 
```
Replace SeleniumTest.driver with the path to your selenium driver
Replace '.sceditor' with your jquery selector that points to the textarea that used as editor.

**Comment by marksyzm** [comment]
Close?

**Comment by mhiemstrapodiumtv** [comment]
Yes you may close it. I left my last reply so that if other people having this issue know how to solve it.

**Comment by marksyzm** [comment]
Ah I think it's up to the owner to be able to do that. I didn't realise your issue was still open either.

**Comment by brunoais** [comment]
Just got here. There you go :)
