### ISSUE TITLE
Editor is removing pasted code indentation

### ISSUE THREAD

**Issue by Spuds** [samclarke/SCEditor#497]
This is in the latest master, **not** in 1.4.7
- Start in source mode ... use [code][/code] tags and past in some formatted code.
- Toggle to Wizzy mode, looks OK
- Toggle back to source mode, all leading indentation has been stripped.

Tested in palemoon 25.8.1 fwiw

Seems to be a result of this commit, https://github.com/samclarke/SCEditor/commit/5df244b6f188327a3c8f8ac78b09ea0147e75d0a

**Comment by Spuds** [comment]
Just to update ... as noted above the problem starts in  ```base.getWysiwygEditorValue``` and specifically

```
				var $tmp = $('<div>')
					.appendTo(document.body)
					.append($wysiwygBody.clone());
```

This works fine, it makes the clone/copy, but as it progress through its steps and gets to ```removeWhiteSpace``` which does a ```cssWhiteSpace = $(node).css('whiteSpace');``` check to see if the whitespace is "pre" or not, it returns "normal" for all the nodes of the cloned $tmp,  code and pre nodes included.

No idea if that's just a pale moon / Firefox issue or not ... the easy fix is to add some ```$(node).is('code')``` checks in addition to the cssWhiteSpace sniff.  Anyway just wanted to provide some details of what I found in case they help.

**Comment by brunoais** [comment]
@samclarke 
After commit 22904cd, When I paste code with tabs, they become spaces. Then, when people copy the code, they don't copy with the right size.

**Comment by samclarke** [comment]
I converted them to spaces as when outside of code blocks they get displayed as a single space which didn't seem very user friendly. You're right though, converting tabs to spaces isn't ideal inside of code blocks.

As there's no non-breaking space equivalent for tabs I guess the only choice is for them to be collapsed outside of code blocks.
