### ISSUE TITLE
Calling window.sceditorInstance.focus() will not set the cursor correctly

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#500]
Calling window.sceditorInstance.focus() will not set the cursor into the default `<p>|</p>` tag but instead in the very beginning of the body tag.

Any way to tell sceditor to correctly set the cursor into the first p tag?

**Comment by brunoais** [comment]
I don't think there's a way. IIRC, the only way to get that result is to call the `.focus()` method on the `<p>` tag.

**Comment by q2apro** [comment]
Thanks, but how to do this from the instance?

	window.sceditorInstance_c247079_content = $('textarea[name="c247079_content"]').sceditor('instance');
	window.sceditorInstance_c247079_content.focus(); // alternative?

?

**Comment by q2apro** [comment]
I have tried to use a `range` with without any effect: 

	var instance = $('textarea[name="c247084_content"]').sceditor('instance');
	var firstel = window.sceditorInstance_c247084_content.getBody().context.firstElementChild;
	var rangeHelper = instance.getRangeHelper();
	// console.log(rangeHelper);
	range = document.createRange();
	range.setStart(firstel, 0);
	range.setEnd(firstel, 0);
	rangeHelper.selectRange(range);

I guess that `firstel` is not really the DOM element... 

- http://www.sceditor.com/api/sceditor/getrangehelper/
- http://www.sceditor.com/api/rangehelper/

**Comment by q2apro** [comment]
I also tried: 

	instance.wysiwygEditorInsertHtml(" ");

and 

	instance.WysiwygEditorInsertText(" ");

which also focus in the editor - BUT also just in the very beginning before the p tags :(

**Comment by brunoais** [comment]
Try this:
`$("p", $(SCEditorTextareaNode).parent().find('iframe')[0].contentDocument.body).focus()`
Where
SCEditorTextareaNode is either a jQuery object where you called something of sorts:
    var SCEditorTextareaNode = $("textarea").first()
    SCEditorTextareaNode.sceditor()

Or a reference to the `<textarea>` node

**Comment by samclarke** [comment]
Thanks for reporting! Should be fixed in V2.
