### ISSUE TITLE
Leading whitespace added

### ISSUE THREAD

**Issue by JasonRaby** [samclarke/SCEditor#509]
Using xhtml plugin. When you click source, as well as in the underlying textarea, whitespace is added after the opening p tag. As a result, when I save the content of the textarea and reload the page, a space appears at the beginning of the editor.

**Comment by samclarke** [comment]
Thanks for reporting! I'm closing this as it seems to have been fixed in v2. If you're still getting the issue in v2 please re-open or create a new issue.
