### ISSUE TITLE
[Feature Request] Remove format on paste

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#511]
I am having a hard time both myself and my users with the copy pasting the slightest piece of text. Formatting tags are copied as well.

I would love to see an option like Trumbowyg has to strip formatting upon copy paste.

`removeFormatOnPaste: true`

**Comment by anglewgc** [comment]
This is a problem. How do you solve? I want to know. thank you

**Comment by brunoais** [comment]
You can copy to notepad before pasting, you can paste in simple text mode.
Sam is working on the unformatted text pasting, anyway.

**Comment by q2apro** [comment]
There is now a plugin for plaintext pasting: https://www.sceditor.com/documentation/plugins/plaintext/

**Comment by litecart** [comment]
Not sure why this thread was closed a year ago without a comment. Basically this feature is available in most WYSIWYG editors.

Happy to hear there is a plugin now. Appreciate your effort in replying.

**Comment by timint** [comment]
Not sure why this thread was closed a year ago without a comment. Basically this feature is available in most WYSIWYG editors.

Happy to hear there is a plugin now. Appreciate your effort in replying.
