### ISSUE TITLE
[Feature Request] Allowed bbcode tags

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#512]
For the bbcode plugin it would be great to control which tags are allowed/kept.

Currently if I wanna quote a forum user and copy paste text I get:
`[color=#333333][size=2][font family=Helvetica Neue, Helvetica, Arial, sans-serif]`

As I have disallowed font families I need to strip the font tag when parsing the bbcode.

So simply allowing or denying tags would be great:

```
Allow: 'size,color,format,...'
```

or

```
Deny: 'font',
```

Or as we already are able to pick components in the button panel perhaps it would be natural that those tags not available in the panel will be stripped from content.

**Comment by Destroy666x** [comment]
Just use something like `$.sceditor.command.remove('font')` and `$.sceditor.plugins.bbcode.bbcode.remove('font')`

**Comment by timint** [comment]
Thanks, that will probably help my case particulary.

You didn't think mirroring the allowance of the enabled panel tags was a good idea?

**Comment by Destroy666x** [comment]
If you're asking me (I'm not a dev), then no, it would be a step back considering you may want to have hidden BBCodes not available in panel.

**Comment by samclarke** [comment]
If you only allow certain font values, updating the font tag to only convert from HTML when the value is allowed should also work.

E.g.:
```js
$.sceditor.plugins.bbcode.bbcode.set('font', {
	format: function ($element, content) {
		var font;

		if (!$element.is('font') || !(font = $element.attr('face'))) {
			font = $element.css('font-family');
		}

		// Ignore font unless value is allowed
		if (!isFontAllowed(font)) {
			return content;
		}

		return '[font=' + font + ']' + content + '[/font]';
	}
});
```

**Comment by timint** [comment]
@samclarke Welcome back from the grave! ;)
