### ISSUE TITLE
Creating a custom bbcode that is active on first click and inactive on next click

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#515]
I'm trying to create a custom bbcode that works just like several others such as the bold option that when you click it in the toolbar it shows as "pressed down" and when you type it goes bold; and then when you hit it again it goes back to normal text.

I have created a custom bbcode and have it showing up in the toolbar fine, but I'm not sure how to get it to act like I want?

Here is an example of what I have:

```javascript
var mytag =
{
	exec: function() {
		this.insert("[mytag][/mytag]")
	},
    txtExec: ['[mytag]', '[/mytag]'],
    tooltip: "Insert mytag"
};
```

The `exec` doesn't seem to insert anything at all unless I place some content between the tags; the `txtExec` works well though.

Thanks!

**Comment by brunoais** [comment]
The "keep pressed" only works when in WYSIWYG mode. It is made using the `state` parameter in the command.
Here's an example:
https://github.com/samclarke/SCEditor/blob/master/src/lib/defaultCommands.js#L308

**Comment by cyphix333** [comment]
Great - thank you!
