### ISSUE TITLE
Strips divs out of custom bbcodes but allows spans?

### ISSUE THREAD

**Issue by cyphix333** [samclarke/SCEditor#516]
I have created a custom bbcode and it seems it won't allow the html format to contain div's.

For example if I did this inside my bbcode object:

`html: <span class="bbcode_foo">{0}</span>`

It would work when switching back and forth between the wysiswig and source screens.

However if I did this:

`html: <div class="bbcode_foo">{0}</div>`

Whilst it would work fine on the source screen, if you switch to the wysiswig editor and back to the source editor the bbcode tags would now be removed.

**Comment by brunoais** [comment]
Please show me the configuration you used for the BBCode.

**Comment by cyphix333** [comment]
It's alright, I worked it out. I forgot to change the `span` to a `div` in the `tags` parameter in the bbcode object.
