### ISSUE TITLE
Dysfunctional autoExpand vs maximize

### ISSUE THREAD

**Issue by mjau-mjau** [samclarke/SCEditor#523]
Im trying to use the autoExpand feature so that the input expands vertically when required, while input is added. Problem is, scroll gets messed up in maximized mode when autoexpand is enabled. Sometimes cursor ends up below visible stage, and the scroll starts jumping up and down.

Hard to take a screenshot of this. When autoExpand is disabled, maximized mode works perfectly. Is it possible to disable autoExpand by API as a way to avoid this issue?

**Comment by mjau-mjau** [comment]
I did some further research, and when `autoExpand: true`, it seems SCEditor is trying to set the height of the `iframe` also in maximized view, which make the input buggy. I have implemented a simple CSS fix for this behavior:
```
.sceditor-container.sceditor-maximize iframe {
  height: 90vh !important;
}
```
It's not perfect, as it leaves a tiny gap at bottom of screen on large screens in maximized view. It would require a javascript hack to apply height by pixel, but that would be more complicated, because you can't apply `!important` with javascript, so it would not be able to overwrite the CSS applied by SCEditor on keyup. Good enough.

**Comment by Somnium7** [comment]
Same here!

**Comment by samclarke** [comment]
Thanks for reporting. This will be fixed when v2 is released.
