### ISSUE TITLE
How to disable preload for emoticons?

### ISSUE THREAD

**Issue by POPSuL** [samclarke/SCEditor#534]
I've add list of emoji-emoticons (1.8k images) and sceditor begins load them all!

How I can make lazy-load for emoticons?

**Comment by samclarke** [comment]
Currently it's not supported as the emoticons toolbar item isn't really up to displaying that many emoticons. 

If you really wanted to, you could set the [emoticonsEnabled](http://www.sceditor.com/documentation/options/#emoticonsEnabled) option to `false` when creating the editor and then call [`instance.emoticons(true);`](http://www.sceditor.com/api/sceditor/emoticons/#emoticons-en) to enable them. That way they won't be preloaded but will still be enabled.

**Comment by POPSuL** [comment]
@samclarke thanks! Its working!
