### ISSUE TITLE
Dropping IE 8 and below after v1.5.0

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#537]
Since Microsoft no longer supports IE <= 8 it's probably time to drop it. The current usage statistics for IE 8 are:
- [StatCounter](http://gs.statcounter.com/#browser_version_partially_combined-ww-monthly-201508-201608-bar) - 1.57%
- [data.gov.uk](https://data.gov.uk/data/site-usage?month=2016-08#browsers_versions) - 0.61%
- [Netmarketshare](https://www.netmarketshare.com/report.aspx?qprid=3&qpaf=&qpcustom=Microsoft+Internet+Explorer+8.0&qpcustomb=0&qpsp=200&qpnp=13&qptimeframe=M) - 4.16% ?!?!
- [Wikimedia](https://stats.wikimedia.org/wikimedia/squids/SquidReportClients.htm) 1.28% - 1.31%

A big plus of dropping IE <= 8 is that it uses a none standard selection API which adds overhead and is just generally a pain to deal with. Dropping support for it should reduce the file size and make the code a little bit nicer to deal with.

If anyone thinks that support shouldn't be removed for IE 8 and below then feel free to add a comment otherwise it'll be removed after 1.5.0.

**Comment by cyphix333** [comment]
Great idea IMO! +1
