### ISSUE TITLE
Add composer.json for project

### ISSUE THREAD

**Issue by jinnguyen** [samclarke/SCEditor#539]
Hi, 

Can u pls add composer.json file to your project, it will be great to use your project as a package in composer.

**Comment by samclarke** [comment]
I've added one to the samclarke/SCEditor-bower repository and [added it to packagist](https://packagist.org/packages/sceditor/sceditor).

**Comment by jinnguyen** [comment]
Tks

**Comment by reloxx13** [comment]
@samclarke can you please add v3 to packagist? only 2.x is available.

https://packagist.org/packages/sceditor/sceditor
