### ISSUE TITLE
Inserting hr sometimes splits quotes in chrome

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#545]
When inserting a `<hr />` between lines inside a quote it sometimes splits the quote in chrome.

Source: https://community.mybb.com/thread-173071.html

**Comment by TwinFuture** [comment]
I can't seem to produce this bug in SMF v 2.1.2. I have modified the source some time ago, but dunno how you produce that error.

**Comment by samclarke** [comment]
From my testing it seems to only happen when a quote is contained within a `<p>`.

**Comment by TwinFuture** [comment]
@samclarke 
I just managed to produce the bug, its when you start a new post in the editor untouched and not pressed delete or anything.
Can't we just remove the initial <p> that is loaded if you hit del and backspace a few times, the <p> will be deleted and when you type something you will have "TEXT1" hit enter to create a new line then they are wrapped in <div>TEXT2</div>
So you end up with TEXT1<DIV>TEST2</DIV>

If you don't manage to delete the <p> which will be a hit and miss for some posts then your text is all wrapped up in <p>

It just seems to be a little off point how it can remove the initial <p> then switch to <div>

So couldn't we just replace the <p> with <div>
Would solve 2 problems for me

one is the fact I sometimes delete the <p> by accident then everything is wrapped up in <div>
Also the quotes won't get split.
