### ISSUE TITLE
Change to ES6 modules

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#547]
Since ES6 modules are now standardised it might make sense to switch to using them at some point.

**Pros**:

- ES6 modules are the future
- Can split the code up much more cleanly without adding to the output size
- Should make it easier to test more of the code once it's split up more
- Should reduce the file size a little bit as won't have the AMD boiler plate and internal modules should be able to minified more

**Cons**:

- Requires a build step see any changes (at least until browsers support ES6 modules)
- Will break backwards compatibility with any code using the source directly from package although it could be built into a lib folder to handle that if required

If any one has any thoughts feel free to add them.

**Comment by brunoais** [comment]
Some browsers still do not support it... And I'm not talking about 
outdated browsers.

**Comment by samclarke** [comment]
Currently only Edge supports them (and even then it's behind a flag) so testing changes would require a build step. Because of that it might be worth waiting until FF or Chrome support them as having a build step to see changes isn't ideal. Having said that it could be done with something like webpack's dev server which isn't too bad.

For the released version it won't make any difference as that's already built with webpack to remove the AMD modules. Using ES6 modules with either rollup or webpack2 should allow slightly better minification. It should also remove the overhead of AMD modules meaning the code can be split up better without adding to the final size.

**Comment by live627** [comment]
Does this mean you will finally drop jQuery as a dependency?

> Some browsers still do not support it... And I'm not talking about outdated browsers.

That's what [Babel](https://babeljs.io/) is for.

**Comment by samclarke** [comment]
Switching to ES6 modules wouldn't affect the jQuery dependency but now that IE < 9 has been dropped it should be possible to make jQuery optional. I've created an issue for it #548

**Comment by samclarke** [comment]
I've been testing this and with webpack2 the size stays the same (there's some overhead for es6 modules). With rollup it reduces the size by around 2kb and makes cost of splitting code into modules very cheap / free size wise.

I think switching to rollup would be worth it. The only issue is how to make it easy to test when using ES6 modules.

**Comment by samclarke** [comment]
I've created a new branch to experiment with ES modules. Testing requires using the webpack dev server which IMO is slightly better than AMD modules as there's no HTTP server required.

It also generates a bundle (`http://localhost:9000/webpack-server/main.js`) which can be injected in other pages while developing without needing an AMD module loader. The bundle works exactly like a normal build and it will regenerate whenever the code changes.

So far I think it's worth changing. Just need to investigate adding code coverage to make sure that works OK.
