### ISSUE TITLE
Make jQuery optional

### ISSUE THREAD

**Issue by samclarke** [samclarke/SCEditor#548]
Now that [IE < 9 has been dropped](https://github.com/samclarke/SCEditor/issues/537) the jQuery requirement could also be made optional. SCEditor would still hook into jQuery if it's loaded as it does now but it would also allow using SCE without jQuery.

I've tried to make a complete list of the bits that are currently used by SCE:
```
$(selector)
$(html)
.find()
.is() .closest()
.parents()
.on() .off()
.css()
.keypress()
.val()
.each()
.contents()
.children()
.contains()
.camelCase()
.isArray()
.attr() .removeAttr()
.addClass() .removeClass() .toggleClass() .hasClass()
.extend()
.trim()
.data() - Used the same as attr('data-' + name)
.merge()
.isEmptyObject()
.height()
.width()
.first()
.isFunction()
```
Nearly all of which have native equivalents now meaning jQuery should be able to be replaced with a minimal wrapper. The main ones without a native equivalents are `$.extend` and the class manipulation methods (IE 9 doesn't support classList annoyingly) which isn't too bad.

If any one has any thoughts about this either for or against please add them.

**Comment by live627** [comment]
`$.extend` and `classList ` already have polyfills. I use

https://www.npmjs.com/package/xtend
https://www.npmjs.com/package/domtokenlist-shim

**Comment by TwinFuture** [comment]
Please remove the requirement for jqeury. The only reason I am using the jquery plugin is for this editor. I actually want to strip jquery out of it myself but would require some time to study the code. I'm not a fan of plugins here plugins there.. People are ramming plugins into something that requires one line of code. I understand back when this was in its baby stages jquery was all the noise. Now the noise needs to be removed. Please do!

**Comment by brunoais** [comment]
@TwinFuture SCE uses jQuery quite extensively. There are still quite some bugs that jQuery seamlessly solves that SCE depends on.
Why don't you use one of those much lighter packages (I'm not remembering their names) that provide the same interface but a much lighter code in both processing and size.
Have you tried any of those?

**Comment by samclarke** [comment]
@brunoais are you thinking of [Zepto](http://zeptojs.com)? Not actually sure if SCE is compatible with it but might be if you define the `jQuery` variable.

**Comment by brunoais** [comment]
I don't have time now to update, make sure it is working and then try zepto but yeah, I was thinking a lib like that one.

**Comment by TwinFuture** [comment]
I don't want any frameworks lol. After some study of the code, jquery is really not needed or dependant on any of it. I see you use jquery listeners and also append elements with it. It would require a good sieve through the code and  to transform it to plain javascript but it surely does not depend on it. It would add to your file size by a little, but it wouldn't be dependant on jquery so you would save overall.

**Comment by martec** [comment]
appear that Zepto not will increase performance
https://github.com/mybb/mybb2/issues/264#issuecomment-257112564

**Comment by samclarke** [comment]
I've been thinking about this and I think if this is going to be done it should be done as part of v2 as it would be slightly backwards incompatible. There are a few methods that currently return jQuery objects which would have to return plain DOM nodes.

So I'm going to create a test branch to try it out and see if it's worth it or not.

**Comment by samclarke** [comment]
So far I've managed to remove jQuery from everything other than the plugins (0598d76dd49b35d7227a80a41f10973cc3d0701d).

Size wise it's a little smaller when just uglified and about the same size when uglified and gzipped. I suspect removing jQuery from the plugins might increase the size a little bit but not much.

So it looks like removing jQuery as a dependency is doable but it'll need a lot of manual testing. Switching to ES6 modules might help a little as it allows splitting the code up without increasing size which should make it easier to make the code more unit test friendly.

### Backwards incompatibilities

Currently they are:

-  The `nodechanged` event now stores newNode and oldNode in the detail property
- The `valuechanged` event now stores rawValue in the detail property
- `getContentAreaContainer() `now returns a plain DOM element
- `getBody()` now returns a DOM node
- `dom.parseHTML()` now returns a fragment
- The caller argument for commands `exec` and `txtExec` functions is now a HTMLDivElement

**Comment by samclarke** [comment]
I've removed jQuerty from the BBCode and XHTML plugins in the [remove-jquery branch](https://github.com/samclarke/SCEditor/tree/remove-jquery) to see how that affects things. The file sizes for SCEditor with the BBCode plugin are:

- Previous release: `70.5kb (23.9kb gzipped)`
- V2 with jQuery: `67.9kb (23.8kb gzipped)`
- V2 without jQuery: `68.4kb (24.1kb gzipped)`

So file size wise removing jQuery shouldn't negatively affect jQuery users.

### Backwards incompatible changes

- `elementToBbcode()` now takes a DOM node
- Removed deprecated `jQuery.fn.sceditorBBCodePlugin()` method
- Removed deprecated `$.sceditorBBCodePlugin` variable
- The first element parameter to the BBCode `format:` function is now a plain DOM node
- The second jQuery param to XHTML `conv:` function is no longer supplied

The BBCode format one is quite bad but should be able to create a backwards compatibility script to create the old behaviour. Something like:

```js
var bbcodes = $.sceditor.bbcode.bbcodes;
Object.keys(bbcodes).forEach(function (key) {
    var oldFormat = bbcodes[key].format;

    if (typeof oldFormat === 'function') {
        bbcodes[key].format = function (element, content) {
            oldFormat(jQuery(element), content);
        };
    } 
});
```

I think this is worth doing despite the backward incompatibles as most of them can be fixed with a backwards compatibility script and it removes the jQuery dependency which is larger than the whole editor! If any one has any thoughts on this please add them.
