### ISSUE TITLE
autoExpand doesn't work always

### ISSUE THREAD

**Issue by Somnium7** [samclarke/SCEditor#552]
`autoExpand` is totally broken. It doesn't resize when `val('...')` is called manually, when image is inserted and when source mode toggled. It doesn't resize if it has image which didn't load immediately. Also it doesn't not shrink (will be good to add another option for this). Also it does something crazy in fullscreen mode.

**Comment by samclarke** [comment]
Thanks for reporting. This will be fixed when v2 is released.

**Comment by Somnium7** [comment]
I see you have used setTimeout. I guess it's for slow-loading images. What if image is big and loads longer that 200ms? It is better to add onload event listener to images when they are created.

**Comment by samclarke** [comment]
The delay is for the key press and input events so it doesn't waste CPU time by checking at most 5 times a second.

It's called in the initial load event for images but I missed the image loading after initial load case. I've added a fix for that: (4a3544b0d73be317aa5805e97903be013c2c8c8b).

**Comment by Somnium7** [comment]
Sorry, for disturbing, but when approximately v2 will be released? I need to provide info to my customers about when fixes will be available.

**Comment by samclarke** [comment]
Not for a while yet. If it was a more serious bug I'd create another 1.5.x released but it takes a lot of time so I only want to do that for really bad bugs.

As a workaround you can monkey patch old version to use the fix with this:

```js
(function ($) {
	function patchAutoExpand(sceditor) {
		var autoExpandThrottle, autoExpandBounds;
		var $wysiwygBody = sceditor.getBody();
		var $wysiwygDoc = $($wysiwygBody[0].ownerDocument);

		function expandToContent(ignoreMaxHeight) {
			if (sceditor.maximize() || !('createRange' in document)) {
				return;
			}

			autoExpandThrottle = false;

			if (!autoExpandBounds) {
				var height = sceditor.opts.resizeMinHeight ||
					sceditor.opts.height || sceditor.height();

				autoExpandBounds = {
					min: height,
					max: sceditor.opts.resizeMaxHeight || (height * 2)
				};
			}

			var range = $wysiwygDoc[0].createRange();
			range.selectNodeContents($wysiwygBody[0]);

			var rect = range.getBoundingClientRect();
			var current = $wysiwygDoc[0].documentElement.clientHeight;
			var spaceNeeded = rect.bottom - rect.top;
			var newHeight = sceditor.height() + (spaceNeeded - current);

			if (!ignoreMaxHeight && autoExpandBounds.max !== -1) {
				newHeight = Math.min(newHeight, autoExpandBounds.max);
			}

			sceditor.height(Math.ceil(Math.max(newHeight, autoExpandBounds.min)));
		};

		function autoExpand() {
			if (sceditor.opts.autoExpand && !autoExpandThrottle) {
				setTimeout(sceditor.expandToContent, 200);
			}
		};

		// Add new event listeners
		$wysiwygBody[0].addEventListener('load', autoExpand, true);
		$wysiwygDoc.on('input keyup', autoExpand);

		// Remove old event listener
		$wysiwygDoc.off('keyup', sceditor.expandToContent);

		// Monkey patch SCEditor methods
		sceditor.expandToContent = expandToContent;

		var maximize = sceditor.maximize;
		sceditor.maximize = function (val) {
			maximize(val);
			autoExpand();
		};

		var setWysiwygEditorValue = sceditor.setWysiwygEditorValue;
		sceditor.setWysiwygEditorValue = function (value) {
			setWysiwygEditorValue(value);
			autoExpand();
		};
	}

	// Patch jQuery method to automatically apply the fix
	var sceditor = $.fn.sceditor;
	$.fn.sceditor = function (options) {
		var	ret = sceditor.call(this, options);

		this.each(function () {
			var instance = $(this).data('sceditor');

			if (instance) {
				patchAutoExpand(instance);
			}
		});

		return ret;
	};
}(jQuery));
```

Just concatenate it onto the end of the SCEditor JS (`jquery.sceditor.bbcode.min.js`, `jquery.sceditor.min.js` or `jquery.sceditor.xhtml.min.js`) and it should patch it. I haven't tested it thoroughly so you'll need to test it but it should work.
