### ISSUE TITLE
nested BBCode lists are entirely broken

### ISSUE THREAD

**Issue by naturalgeek** [samclarke/SCEditor#553]
when you create a nested list, the output BB Code is wrong!

**Output is:**

[ul]
[li]eins[/li]
[ul]
[li]zwei[/li]
[ul]
[li]drei[/li]
[/ul]
[/ul]
[/ul]

**Instead of:**

[ul]
[li]eins
[ul]
[li]zwei
[ul]
[li]drei[/li]
[/ul]
[/li]
[/ul]
[/li]
[/ul]

Which are not parseable by at least phpBB 3.1.10 and 3.2

Issue found by using a WYSIWYG Editor using SCE for phpBB :
https://github.com/cYbercOsmOnauT/wysiwygsceditorphpbb/issues/21

**Comment by samclarke** [comment]
I've looked into this and it's caused by the browser content editable creating the invalid lists which SCEditor is then converting to BBCode.

I'll add a fix to place any nested list in either the previous li tag or in their own li tag if there isn't one.

**Comment by samclarke** [comment]
Fixed in the master branch which will be released as v2.

If you want to apply the fix to previous versions you can monkey patch the `fixNesting()` method to do it by doing:

```js
$.sceditor.dom.fixNesting = function (node) {
	var dom = $.sceditor.dom;
	var	getLastInlineParent = function (node) {
		while (dom.isInline(node.parentNode, true)) {
			node = node.parentNode;
		}

		return node;
	};

	dom.traverse(node, function (node) {
		var list = 'ul,ol',
			isBlock = !dom.isInline(node, true),
			$node = $(node);

		// Any blocklevel element inside an inline element needs fixing.
		if (isBlock && dom.isInline(node.parentNode, true)) {
			var	parent  = getLastInlineParent(node),
				rParent = parent.parentNode,
				before  = dom.extractContents(parent, node),
				middle  = node;

			// copy current styling so when moved out of the parent
			// it still has the same styling
			dom.copyCSS(parent, middle);

			rParent.insertBefore(before, parent);
			rParent.insertBefore(middle, parent);
		}

		// Fix invalid nested lists which should be wrapped in an li tag
		if (isBlock && $node.is(list) && $node.parent().is(list)) {
			var $li = $node.prev('li');

			if ($li.length) {
				$li.append($node);
			} else {
				$node.wrap('<li />');
			}
		}
	});
};
```

**Comment by naturalgeek** [comment]
Nice, thank you!
