### ISSUE TITLE
i want insert images with Text Input 2 File Input

### ISSUE THREAD

**Issue by hiepdung** [samclarke/SCEditor#554]
hi admin

i want insert images with Text Input 2 File Input

Code buy here
   https://codecanyon.net/item/jquery-file-manager-popup/9744246
SCEditor edit buy here line
   <input class="file-manager" type="text" id="image">
But when click it not work, please help me
Thank so much

**Comment by samclarke** [comment]
SCEditor isn't a native text input so it's unlikely to work with scripts like that without special support being added.
