### ISSUE TITLE
Deactivate some commands

### ISSUE THREAD

**Issue by sugo23** [samclarke/SCEditor#556]
I have these commands in my toolbar:

toolbar: 'bold,italic,underline,strike|left,center,right|font,size,color|bulletlist,orderedlist,quote|link,unlink|emoticon|removeformat,source',

I want to deactivate all others (especially the image embed). How can I do this?

**Comment by samclarke** [comment]
You can remove BBCodes with the bbcode.remove() method:

```js
$.sceditor.plugins.bbcode.bbcode.remove('img');
```

and commands with:

```js
$.sceditor.command.remove('img');
```
