### ISSUE TITLE
Starting with empty lines

### ISSUE THREAD

**Issue by Conver** [samclarke/SCEditor#559]
When sceditor is not activated, then I can make empty starte lines in the textarea, but when activated it strips out the starting empty lines and goes right to the text.

Is there a workaround for this?

**Comment by samclarke** [comment]
I've just tried and can't seem to reproduce this issue with either loading or setting with `val()`. Could you take a look and see what I'm doing differently: https://jsfiddle.net/xemcmpsm/2/

**Comment by Conver** [comment]
Hmm.. I can see it's working on your end.. Wonder what Im doing wrong them.. 

I'll paste my version later today.

**Comment by samclarke** [comment]
Closing as can't reproduce. Feel free to re-open or create another issue if you're able to reproduce the issue.
