### ISSUE TITLE
Need to retain the same format when we paste

### ISSUE THREAD

**Issue by libbiteja** [samclarke/SCEditor#560]
It should retain the color, font, underline and all the other formats supported by MS Word.

**Comment by samclarke** [comment]
Could you paste some examples here: https://jsfiddle.net/bquqpq83/show/ and copy the HTML from the textarea to this issue?

**Comment by libbiteja** [comment]
Take a word doc write some text and format it to header1 and change its style and append other text and underline it and change its color , now when you paste header 1 style applies instead of changed style and the color of underline is not retained...It will be helpful if you could add them:) Thanks in advance
![capture](https://cloud.githubusercontent.com/assets/25007354/23691751/64ab4a1e-03f0-11e7-84e4-b1df97279186.JPG)(refer the pic...The same format is not retained)

**Comment by samclarke** [comment]
I don't currently have a copy of word to try this with so I'd need to see an example of the HTML that Word is generating to fix it.

If you could you paste an example into: https://jsfiddle.net/bquqpq83/show/ and copy the HTML from the textarea to here it would be really helpful.

**Comment by libbiteja** [comment]
Part Name Part Number   National Stock Number Work Unit Code 

EEC106-80 P&W P/N:    4088029D02 2995-01-520-3563NZ  23KC0    Vendor P/N: 1002300H02D04 


Problem Definition/Root Cause Assessment 

Engine Control & Diagnostics: 

An update to the existing PW-229 software is required to allow the recording of engine streaming data for enhanced troubleshooting, to address high frequency faults driving unnecessary maintenance and LRU removal / replacement and to enhance safety with modified RCVV open loop criteria to extend primary mode for over-speed temperature protection.   


This task would implement an approved list of software changes baselined off of the latest PW-229 Software Version 8.1.1.  Software Version 8.1.1 addressed take-off stalls due to hot temp / high humidity.  The changes below have known solutions that have been presented or will be presented and approved by the customer prior to implementation. 

* CR 842 - SW solution for EEPROM timing  

* CR 890 – Remove ITADS logic 

* CR 948 – Address FTIT nuisance faults (FC 4076 & FC 4077) 

* CR 958 – Update PB vibrating cylinder heater fault limits 

* CR 957 – Update Synchro test voltage lower range limit 

* CR 959 – Collect Streaming Data 

* CR 953 – Add alternate accommodation for RCVV open loop failures 

* CR 856 – Address “Phantom MFL” occurrences 

* CR 972 – LOD Self-Test improvements 

* CR 986 – FTIT fault detection improvements (FC 4070) 

* CR 987 – PHM changes to improve data analysis capability (the changes identified under this CR will be broken up between this CR and CR 988 based on functionality for efficiency of design) 

These changes will be implemented into the existing Group VI DEECs, resulting in a new DEEC software package designated as 8.2.0 with the accompanying update to the Program ID and checksums to reflect 8.2.0. 

Support Equipment:  

Support for the USAF update of WinCEDS6 S/W and DEFTReport6 (DLL) and update of other support equipment (HHCEDS6 S/W, PAT Rigs) is required to include all compatibility changes driven by the control as well as to address any requested customer approved enhancements.  Compatibility testing with ACT and DEFT is also required. 

Field Impact/Reliability Metrics 

* Identified software improvements have the potential to improve safety / mission readiness and to reduce ETOC/auto transfer to SEC rates.

**Comment by libbiteja** [comment]
See the difference between the text in image and the text pasted after copying it from the textarea of jsfiddle.

**Comment by samclarke** [comment]
That appears to be plain text with no formatting. Did you paste it into the textarea or where it says "Paste here..."?

If you pasted the text where it says "Paste here..." then either Word isn't copying the formatting or the browser/some other program is stripping the formatting which means there isn't anything SCEditor can do.

**Comment by libbiteja** [comment]
I have pasted in the text area which says paste here.

**Comment by samclarke** [comment]
In that case it looks like the formatting isn't being copied or it's being stripped before being pasted into the browser.

I think Word should be copy some formatting at least. Just to make 100% sure, I've updated the jsfiddle so it can only be pasted into the contenteditable. Could you check it still produces the same output: https://jsfiddle.net/bquqpq83/2/show/

If it does then there isn't anything SCEditor can do as the formatting isn't being copied.
