### ISSUE TITLE
How disable paste from Micr Office Word.

### ISSUE THREAD

**Issue by jrails-net** [samclarke/SCEditor#561]
About the title.

Thanks.

**Comment by samclarke** [comment]
Currently there isn't a way to do this easily. The nest version will have a plain text plugin which could be used to strip all formatting from Word. I'm also hoping to add a paste filter to fix some of the strange Word HTML in the next version (issue #346).

The only solution right now would be to add a paste event handler to the editor's body (`getBody()`) and then cancel/fix it if it looks like it's from Word.
