### ISSUE TITLE
Editor pre-defined URL update needed

### ISSUE THREAD

**Issue by MyBB-Andro** [samclarke/SCEditor#562]
Hi,

Text Editor pre-defined link needs to be updated, currently it shows _http://_ by default, its good time to change it to _https://_

![1](https://cloud.githubusercontent.com/assets/24277403/24469294/a96b6028-14d8-11e7-8b2a-76309f893047.png)
![2](https://cloud.githubusercontent.com/assets/24277403/24469295/a9a3085c-14d8-11e7-99f9-4f4f9b5cd17a.png)

**Comment by samclarke** [comment]
Thanks for reporting! I've updated the placeholders in the master branch which will be in the next release.
