### ISSUE TITLE
Paste plain text - not HTML by default (not by pressing the toolbar button)

### ISSUE THREAD

**Issue by vladrusu** [samclarke/SCEditor#564]
Hello !
I want an option to be able to force SCEditor into using plain-text by default when the user pastes code in editor (CTRL+V).
I don't want my users to be able to paste HTML content including images (they are a hassle, as they are encoded in b64) - just plain text.

I know there is a plain text button, but honestly, it relies on the user being aware of that and actually using it... I want to enforce it, like being pushed on by default. :)

Is there such an option/roadmap? I am not using SCEditor ATM just because the lack of this feature.
Thanks!

**Comment by samclarke** [comment]
The plaintext plugin does exactly what you describe. Its not released yet but it's in the master branch (added by ec0cb7637933465207ccc41f695d6807392d92dc) and will be in the next release.
