### ISSUE TITLE
Passed emoticons object is merged with the default emoticons

### ISSUE THREAD

**Issue by compojoom** [samclarke/SCEditor#565]
I have my emoticons object that is formatted according to the docs:

```
{
        // Emoticons to be included in the dropdown
        dropdown: {
            ":)": "emoticons/smile.png",
            ":angel:": "emoticons/angel.png"
        },
        // Emoticons to be included in the more section
        more: {
            ":alien:": "emoticons/alien.png",
            ":blink:": "emoticons/blink.png"
        },
        // Emoticons that are not shown in the dropdown but will still
        // be converted. Can be used for things like aliases
        hidden: {
            ":aliasforalien:": "emoticons/alien.png",
            ":aliasforblink:": "emoticons/blink.png"
        }
    }
```

But when I pass my emoticons object, it's beein merged with the default icons. I don't have definitions for all the default icons so I end up with :angry etc in the emoticons dropdown. 
Right now I just went ahead and replaced emoticons in the source code with:
```
		emoticons: {
			dropdown: {
			},
			more: {

			},
			hidden: {
			}
		},
```

But it would be better if instead of extend we just replace the emoticons object. I think that if you are passing emoticons then, it's the users responsibility to have every single icon he needs in there.

**Comment by samclarke** [comment]
Thanks for reporting! Should be fixed in the next release (v2.0.0) which will hopefully be soon.
