### ISSUE TITLE
Conflict with mootools

### ISSUE THREAD

**Issue by compojoom** [samclarke/SCEditor#567]
I'm working on a Joomla extension called CComment https://extensions.joomla.org/extension/ccomment-core/ and in the newest version I'm integrating SCEditor. 
Everything works great, but I ran into an issue when Mootools is included on the page(I cannot control what libraries a user might have on his website). 
Basically the issue boils down to the fact that Mootools is overriding the get method on an element. 
And over here https://github.com/samclarke/SCEditor/blob/master/src/lib/SCEditor.js#L71 when we call get on the method with 0, the mootools method kicks in and we are left with a fatal error. 

I have a method that inits the editor:
```
textarea = jQuery(this.$el).find('textarea.js-ccomment-textarea'),
sce = textarea.sceditor({
				toolbar: toolbar,
				style: "/media/com_comment/js/vendor/sceditor/jquery.sceditor.default.min.css",
				height: 100,
				width: '100%',
				autofocus: true,
				autoExpand: true,
				autoUpdate: true,
				resizeEnabled: false,
				resizeMaxHeight: 300,
				plugins: "bbcode",
				emoticonsCompat: true,
				emoticonsRoot: config.baseUrl,
				emoticons: config.emoticons_pack,
				emoticonsEnabled: config.support_emoticons
			});
```

I'm using the jquery bbcode plugin. 

If I override 		var original  = el.get ? el.get(0) : el; with
		var original  = $(el).get ? $(el).get(0) : el;

Then the issue is fixed for me. However I don't have the global picture and I don't know if the fix is valid or not? @samclarke - what do you think? You want a pull request with that?

**Comment by samclarke** [comment]
I see what you mean, mootools adds it's own `get()` method to the element prototype.

I think that line can be removed now as it shouldn't be needed any more. In the next version jQuery will be an optional dependency and the only method to create an instance with a jQuery object is via the `sceditor()` method in [jquery.sceditor.js](https://github.com/samclarke/SCEditor/blob/master/src/jquery.sceditor.js#L57) which already passes plain DOM nodes.

If you want to make a pull request removing that line and renaming the `el` parameter to `original` that would be great!
