### ISSUE TITLE
Entering source mode places extra span in the content

### ISSUE THREAD

**Issue by BOTPaul** [samclarke/SCEditor#568]
In HTML mode when you enter the 'source' view via the toolbar, a span is placed into the content which seems to be a placeholder for the cursor.

JS fiddle below demonstrating.
https://jsfiddle.net/sct7woup/1/

**Comment by samclarke** [comment]
The JSFiddle isn't including the XHTML plugin, only including the `jquery.sceditor.bbcode.min.js` file, so there is nothing filtering the HTML.

Changing it to `jquery.sceditor.xhtml.min.js` fixes the issue: https://jsfiddle.net/sct7woup/2/
