### ISSUE TITLE
Pasted content appears at top of editor

### ISSUE THREAD

**Issue by lhaatveit** [samclarke/SCEditor#572]
**Browser:** Chrome 59

**Steps to reproduce:**
1. Initialize SCEditor with the `enablePasteFiltering` setting enabled
2. Write a few lines
3. Copy any sentence
4. Position the caret at the end of the document
5. Press and hold `Ctrl + V` for a couple of seconds to repeatedly paste the sentence

**Result**
Parts of the paste appears at the top of the document.

**Expected result**
Paste should be inserted at the end of the document.

**Comment by samclarke** [comment]
Thanks for reporting! This seems to have been fixed in v2 for me so closing.
