### ISSUE TITLE
Edge does not add / insert highlighted text correctly

### ISSUE THREAD

**Issue by Spuds** [samclarke/SCEditor#573]
This occurs in the version on the sceditor site as well as the latetst dev version on github

0) using Edge v40 (Microsoft Edge 40.15063.0.0)
1) place editor in source mode
2) select some text in the editor
3) click on an editor command, for example Bold 
4) a blank  [b][/b] pair is placed at the start of the text in the editor and not around the selected text

This happens for all commands, including "form" commands such as links etc.  selectionStart and selectionEnd both return 0

**Comment by Spuds** [comment]
In the FWIW category, moving the toolbar commands to use mousedown vs click events allows Edge to perform correctly.  There is likely some event bubbling issue that Edge does wrong, but for now using mousedown with verification that the event is the left mouse button seems to get things to work.

**Comment by samclarke** [comment]
Thanks for reporting! Closing as this seems to have already been fixed in v2.
