### ISSUE TITLE
Problem with window resize when editor is in the table's cell

### ISSUE THREAD

**Issue by ImCheery** [samclarke/SCEditor#575]
Hi,
There is a problem with resize of the editor when it is inside of the table's cell or combination of divs with display: table-cell. It only grows with increasing window width, but won't reduce the size back with decreasing window width. Works only for regular div, but, for example, I need additional block to be placed to the left of the editor (do not want to use display: flex). Example - https://jsfiddle.net/jszr8rc2/ (top is in table, bottom - in div)
It works weirdly when width is set to less than 100%, but depends on how fast window width is changing - https://jsfiddle.net/jszr8rc2/1/

**Comment by samclarke** [comment]
Thanks for reporting! This has already be fixed along with some other related bugs in v2.0.0 which will hopefully be released soon.
