### ISSUE TITLE
Insert Adsense code

### ISSUE THREAD

**Issue by blackchineykh** [samclarke/SCEditor#579]
Hi Guys, I am trying to use this editor to save javascript code for adsense. It seems to keep removing the javascript before it gets store into the database. Can you guys advise how it can stop this behaviour and save the exact HTML with Javascript content?

**Comment by samclarke** [comment]
By default `script` tags shouldn't be stripped SCEditor. I'm guessing you're using the XHTML plugin, it should only remove `script` tags if they're added to the [disallowedTags](https://www.sceditor.com/documentation/plugins/xhtml/#disallowedTags) array or if some tags have been added to the [allowedTags](https://www.sceditor.com/documentation/plugins/xhtml/#allowedTags)  array without including `script`.
