### ISSUE TITLE
Switching to code mode strips valid spaces

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#582]
Hi,

In normal mode, write that text in the editor: "aa bb cc" (one space between the double letters).
Select "bb" and mark it bold, the result: "aa **bb** cc"
Switch to the code mode, the result will be: "aa [b]bb[/b]cc" <== notice that there is no space between bb and cc!

I've tried to debug it and came to the removeWhiteSpace function that strips the leading space of the " cc" since there is a node with a space before it, while there shouldn't be such node while looking on the string...

Diving deeper I came to that line in the _createMarker munction:
    marker.innerHTML = ' ';
It adds that extra node with the space since after the marker is deleted, the space is left there, but it's not generated since its not a text or element node...

Why do we need that space in innerHTML?
Remarking that line solves the problem, but I'm not sure what was the original purpose...

**Comment by samclarke** [comment]
Thanks for reporting! I've added a fix to the master branch.

The `marker.innerHTML = '  ';` line was originally added in a commit to fix an issue in Opera (080d067cc2197d1cf01c3b60dbd041eff5d43f63). As far as I can see it was needed to Opera 12 which is no longer supported and can be removed. Will need to do some testing to check though.
