### ISSUE TITLE
Youtube does not work until change view to 'source code' and back to WYSIWYG

### ISSUE THREAD

**Issue by zebroid** [samclarke/SCEditor#597]
Screencast http://recordit.co/AobGnhwfWw

Youtube does not work until change view to 'source code' and back to WYSIWYG

How to reproduce:
1. Go to https://www.sceditor.com
2. Insert via youtube button any youtube link
3. Change view to source code
4. Change view back to WYSIWYG

same one in last FireFox and Opera (don't test in Chrome)

**Comment by abetis** [comment]
There is a bug in templates.js, a missing space after allowfullscreen at the end of the line.
The bug was introduced by the a19703ff043ef8090fbc0d2ff86158c7f61d5541 change (Add time to YouTube links).
It is fixed in my YouTube tag enhancement PR.

**Comment by zebroid** [comment]
abetis, thanks a lot!
