### ISSUE TITLE
Small doc bug for plaintext plugin

### ISSUE THREAD

**Issue by brettz9** [samclarke/SCEditor#601]
I don't see that your docs are anywhere in version control, so I'm just reporting as an issue:

At https://www.sceditor.com/documentation/plugins/plaintext/ , the "initialise" section has:

    plugins: 'plugin'

which should be:

    plugins: 'plaintext'

The other plugin pages are ok.

**Comment by brunoais** [comment]
> I don't see that your docs are anywhere in version control, so I'm just reporting as an issue:

https://github.com/samclarke/sceditor.com

**Comment by brettz9** [comment]
Filed at https://github.com/samclarke/sceditor.com/pull/3
