### ISSUE TITLE
Getting SCEditor 2.1 running in jsFiddle

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#604]
It is always a great help to not only show the source code of the problem but a working "test environment" online. 

I have tried to setup two textareas with SCEditor, but cannot get it to work. My goal is to show a bug with the autosave plugin... 

Can somebody help and tell what is wrong with this fiddle: http://jsfiddle.net/7bue7ree/18/

Resources loaded via CDNjs: 

- default.min.css
- sceditor.min.js
- xhtml.js

Thanks, this will help others too. A readymade jsfiddle template would be handy.

**Comment by samclarke** [comment]
The jsfiddle is including the `/themes/content/default.min.css` in the `<head>`, it should be including `/themes/default.min.css` instead. The content one is for styling the WYSIWYG contents.

I've updated the jsfiddle: http://jsfiddle.net/7bue7ree/19/
You can also use the editor without jQuery now if desired: http://jsfiddle.net/7bue7ree/20/

**Comment by q2apro** [comment]
Thanks a lot! 

Pretty sure this tiny setup will also help others (in case they find it).
