### ISSUE TITLE
Bug with Autosave plugin: Only working with one instance

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#605]
File: https://github.com/samclarke/SCEditor/blob/master/src/plugins/autosave.js

Open jsfiddle and see console at page load (two sceditor instances): http://jsfiddle.net/nyvfgnto/3/ 

> Uncaught TypeError: Cannot read property 'time' of null
    at e (VM88 autosave.js:3)
    at ie.o.init (VM88 autosave.js:3)
    at Z.t.register (VM86 sceditor.min.js:3)
    at VM86 sceditor.min.js:3
    at Array.forEach (<anonymous>)
    at Oe (VM86 sceditor.min.js:3)
    at De (VM86 sceditor.min.js:3)
    at new ie (VM86 sceditor.min.js:3)
    at Object.create (VM86 sceditor.min.js:3)
    at VanillaRunOnDomReady ((index):67)

Doing the same with the non-minified [autosave.js](https://github.com/samclarke/SCEditor/blob/master/src/plugins/autosave.js) file from above: 

> Uncaught TypeError: Cannot read property 'time' of null
    at gc (VM6087 autosave.js:25)
    at re.base.init (VM6087 autosave.js:42)
    at ee.t.register (jquery.sceditor.xhtml.min.js:3)
    at jquery.sceditor.xhtml.min.js:3
    at Array.forEach (<anonymous>)
    at Oe (jquery.sceditor.xhtml.min.js:3)
    at Te (jquery.sceditor.xhtml.min.js:3)
    at new re (jquery.sceditor.xhtml.min.js:3)
    at Object.create (jquery.sceditor.xhtml.min.js:3)
    at HTMLDocument.<anonymous>

Hope that helps to find the issue. Maybe it can be fixed by using the `textarea name` as an identifier?

**Comment by q2apro** [comment]
To prevent the error message for null, this can be used.

	if ( localStorage.getItem(storageKey) !== null && JSON.parse(localStorage.getItem(storageKey)).time < Date.now() - expires) {
		localStorage.removeItem(key);
	}

**Comment by q2apro** [comment]
Found a solution:

1. Give each SCeditor instance an ID when initializing: 

	sceditor.create(textarea, {
		// ...
		id: "unique1",    // unique2 etc.
	});


2. Change autosave.js from: 

	storageKey = opts.storageKey || storageKey;

to: 

	storageKey = opts.storageKey || storageKey;
	storageKey += '/-'+editor.opts.id;

Done.

**Comment by samclarke** [comment]
Thanks for reporting, I've added a fix so it won't throw an error when there are multiple instances of the editor on a page.

I'm not keen on having the autosave plugin handle multiple instances or adding an id to the editor. Instead setting the `storageKey` would be the preferred way as it's more configurable. I'll update the docs to mention it.

**Comment by q2apro** [comment]
Well done! Awesome. Yes, to pass the option storageKey makes sense. 

And great that you have added the plugin to the docs!

Now the question is only open, how to clear the storage (using the saveHandler?). Related: https://github.com/samclarke/SCEditor/issues/608
