### ISSUE TITLE
Bug Autosave plugin: Not clearing storage after form submit

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#608]
After testing the autosave plugin on a forum, I saw that it does not clear after the sceditor textarea is submitted. When loading the page anew, the content appears again within the editor. 

Guess we need to call `localStorage.removeItem(key);` on submit, but I am not sure how this can be smartly implemented. Can we call a clear storage function provided by the plugin from outside at submit? For instance, `sceditor.instance(textarea).autosave.clear(key)` or alike.

**Comment by samclarke** [comment]
Thanks for reporting. I've updated the `autosave` plugin to clear on form submit and also added a `clear()` method too for manual removal.

**Comment by q2apro** [comment]
Genius! 👍 

How to call the plugin from another outside code spot? 

I tried `console.log( sceditor.instance(mytextarea) );` to find the function, but failed. 

`sceditor.instance(mytextarea).autosave` does not work etc.

**Comment by samclarke** [comment]
It can be accessed via `sceditor.plugins.autosave.clear()`. If using a custom storageKey then it needs to be passed as the first argument, e.g.:

```js
sceditor.plugins.autosave.clear('storage-key-string-here');
```

**Comment by q2apro** [comment]
That works! Thanks a thousand,
