### ISSUE TITLE
Bug with format:"xhtml" Always pastes into new line

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#611]
When using `format: "xhtml",` each paste goes into a new line: 

![2017-12-17](https://user-images.githubusercontent.com/6764548/34080465-376da7d6-e347-11e7-9f87-d6e1133a0ba9.gif)

I thought at first it is the plaintext plugin, but no, it happens when the xhtml format is set.

Fiddle: http://jsfiddle.net/tw0Lj3d6/1/

Not happening with bbcode: http://jsfiddle.net/tw0Lj3d6/2/

Severe bug since it is a non-standard behavior.

**Comment by samclarke** [comment]
Thanks for reporting! Fixed in master branch and will be in the next release (v2.1.2).
