### ISSUE TITLE
Can't get icons to load

### ISSUE THREAD

**Issue by JasonBarile** [samclarke/SCEditor#621]
Using the demo script, I couldn't get monocons to load. Stepping through the code, on line 4632 of development/sceditor.js, SCEditor.icons is empty/undefined at that point, so no icons are ever loaded. The default icons load since 'monocons' isn't found in SCEditor.icons[]. I finally figured out I have to load monocons.js explicitly as a script. It would be helpful for the docs to show that too.

**Comment by q2apro** [comment]
You probably need to load the monocon.js file beforehand in your HTML.

I also forgot that. Should be added to the documentation.

**Comment by JasonBarile** [comment]
That was definitely the fix, and having the docs mention this would be nice. Thanks!

**Comment by q2apro** [comment]
Sam will see this, and probably do. Enjoy the awesome editor!
