### ISSUE TITLE
i do not undestand how use sceditor

### ISSUE THREAD

**Issue by 221V** [samclarke/SCEditor#628]
i do not undestand how use sceditor

1]
i want use ajax/websockets --
what funcs i must exec for get -
1) bb-code
2) html from bb-code

i want send to server both - bb-code and html

2]
i want use more than one textareas with sceditor,
can i make fully hidden one of tham?

thanks)

**Comment by brunoais** [comment]
I can't get what you want to ask.

**Comment by 221V** [comment]
I not understand how get in js my text\my code that i write on page
