### ISSUE TITLE
base 64 encode

### ISSUE THREAD

**Issue by puroossosinistro** [samclarke/SCEditor#633]
It is possible to send the data (by FORM method POST) converting before to base 64 encode? This will possibly fix the ERR_BLOCKED_BY_XSS_AUDITOR error on Google Chrome and help to prevent XSS attacks. I am using xhtml version instead bbcode.

**Comment by puroossosinistro** [comment]
Ps. 1: The Header('X-XSS-Protection: 0'); solution on PHP works fine but I need a more elegant solution.
Ps. 2: In PHP I know how to decode.

Thanks all for your help!

**Comment by samclarke** [comment]
I could add a plugin to base64 encode the output but I'm not sure how many people would have a use for i. You could do it in the form submit handler, something like: https://jsfiddle.net/samc/4thrk7qL/3/
