### ISSUE TITLE
It is possible to BBCODE lists don't create \n when they are inserted? 

### ISSUE THREAD

**Issue by puroossosinistro** [samclarke/SCEditor#638]
They look like this:

```
[ul]
[li]aaa[/li]
[li]bbb[/li]
[/ul]
```

I need they look like this:

`[ul][li]aaa[/li][li]bbb[/li][/ul]`

I've tried to edit the js files removing the \n (ul, li, ol) but without sucess.

**Comment by brunoais** [comment]
Change the `isInline` to true. See:
https://github.com/samclarke/SCEditor/blob/master/src/formats/bbcode.js#L468

**Comment by samclarke** [comment]
You can also use the [breakAfterBlock](https://www.sceditor.com/documentation/formats/bbcode/#breakAfterBlock) BBCode parser option and set the UL and LI BBCodes to not break at the start.

Something like: https://jsfiddle.net/samc/4thrk7qL/2/
