### ISSUE TITLE
Add/Remove Indent Issues

### ISSUE THREAD

**Issue by mbiddle** [samclarke/SCEditor#639]
The Add and Remove Indent buttons are always inactive, regardless of if you are within a list. I can sometimes get it to activate the Add Indent button if I double click a few hundred pixels to the right of the top list item.

An example: https://drive.google.com/file/d/1wYlRTXQOgBk67hplrU576tbkSAIdDay6/view?usp=sharing 

I tried searching for a similar issue, but my only hit was #147. I believe #147 can/should be closed out.

**Comment by samclarke** [comment]
Thanks for reporting! Fix added to master branch.
