### ISSUE TITLE
imgmanager extension

### ISSUE THREAD

**Issue by utopszkij** [samclarke/SCEditor#655]
jquery,sceditor.bbcode.js  2.1.2
 Linux-mint/Firefox 58.02

1. If there are multiple images in a html tag then the sceditor "img" select  currentNode() is not good.
2. After using Sceditor's original source editor, img select does not work. 

Thanks for the excellent sceditor code.
I have created an img manager for you when you have time to look at it.

see: https://github.com/utopszkij/imgmanager

Fogler Tibor (utopszkij) tibor.fogler@gmail.com

**Comment by samclarke** [comment]
Thanks for sharing! I'll add a note about it in the next release notes.
