### ISSUE TITLE
Basic GitHub questions

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#671]
Hi, will appreciate your help with the GitHub basics, it looks like I miss something very basic and can't find an answer on the web...

I cloned the SCEditor repository, at that point my master == upstream master (samclarke/SCEditor).
I need to add 3 features (A, B, C) and I want to use them all together.
I create a separate branch for A, change whatever needed, commit the change.
Merge the change to master and repeat the same for B and C.
Now my master includes all 3 changes and I use it for my needs.

Here's the problem:
I want to create PR only with change C since change A and B are not mature enough or change things that upstream don't need at all.
If I create PR from C's branch, it will include all the changes (A+B+C).
I can't create a "clean" branch since my master also have all the changes in it.

What should I do?
Should I keep my master always clean so I could create clean branches that will include only the changes I want to deliver and keep all my combined changes on a separate "development" stream?
Something is off in that method...

Or maybe I should clone the upstream's master (samclarke/SCEditor) every time I want to send PR in order to have a clean baseline?

Thanks.

**Comment by brunoais** [comment]
This is more of a workflow for feature creation/contribution than github specifically.
When you make branch `B`, you should make on the same commit as branch `A`. Same for branch `C`.
One way you can do those is to make the 3 branches in 1 go and then checkout the right branch related to what you want to work with.
A tool I quite like using to give a visual work is [gitextensions](https://github.com/gitextensions/gitextensions) for windows (works on linux-based OS but mono has too many bugs)

**Comment by abetis** [comment]
I'm working on Ubuntu Linux, can't use any windows tools.
Actually I use git gui, which provides pretty good user experience.

I didn't understand your answer.
I work on the 3 branches, check them out when I need to change something on a specific feature.
All 3 merged to my master branch to have them all together.
How do I PR only the C change?

I figured out I can create a branch that will be based on upstream/master, so I'll have to move the changes there from my C's branch and PR that new branch. Is that the right flow?

**Comment by brunoais** [comment]
You need to push the 3 branches, not `master`

**Comment by abetis** [comment]
@brunoais , you don't understand what I ask...

I have 3 branches with 3 different features, all merged to my master.
I want to PR to @samclarke repository only the 3'rd feature.
If I RP the master, all the changes will be included in the PR.
If I PR only 3'rd change branch, it will include all the changes as well since it came out of my master while the first 2 changes were included there already...

**Comment by samclarke** [comment]
>If I PR only 3'rd change branch, it will include all the changes as well since it came out of my master while the first 2 changes were included there already...

If you create a branch based on the upstream master it won't have the extra changes. You can then merge that into your branch and send a pull request with that branch.

So if you created two features A and B but only wanted to send B upstream it would look like this: 
```
                                            Merged B
                                            upstream
Upstream Master +---+------+--------------------^-----
                |   |      |                    |  
      Feature A |   +-+    |                    |  
                |     |    |                    |  
      Feature B |     |    +-------+------------+  
                |     |            |               
    Your Master +-----v------------v------------------
                   A merged    B merged
                   no PR sent  PR sent
                   upstream    upstream
```

What you're currently doing is:

```
                                   Everything sent
                                      upstream
Upstream Master +------------------------^----
                |                        |
      Feature A |  +--+                  |
                |  |  |                  |
      Feature B |  |  |       +----+     |
                |  |  |       |    |     |
         Master +--+--v------------v-----+----
                 A merged    B merged
                 no PR sent  PR sent
                 upstream    upstream
```

**Comment by brunoais** [comment]
~~Do an interactive rebase onto "upstream/master" and delete all commits that should have belonged to other branches. Possibly:
`git rebase -i `
see: https://git-scm.com/docs/git-rebase~~
What Sam wrote.

**Comment by abetis** [comment]
ok, that was my conclusion so far as well to create branches that are based on upstream/master instead of local master, which is the default.

It's pretty much counter-intuitive for me, but will try to keep that in mind.

Thanks.

**Comment by brunoais** [comment]
@abetis Maybe you are confusing the concept of tag and the concept of branch, when thinking that.

**Comment by abetis** [comment]
Te confusion comes probably from the centralized and distributed code management concepts.
I'm used to the fact that "master" is always the same master for all in centralized concept.
In distributed concept every one have its own master after cloning the repository.

**Comment by brunoais** [comment]
When you contribute to an SVN project, the concept is actually the same, except you have to transform your changes into patches and send them so they are applied elsewhere.
