### ISSUE TITLE
Ctrl+Z doesn't work for all the code inserted not using execCommand

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#674]
I don't like the execCommnand, but it looks like it does have its good sides...
All the formatting done with execCommand can be undone (ctrl+z), while everything that is directly injected as a HTML code does not, so pressing Ctrl+z removes parts of the text, leaving the injected parts and creates a mess.

Example:
Write 3 lines of text, select a second line, mark it as a code block, go to the end of all the text and type few more words.
Now press ctrl+z few times to get to the initial position...

**Comment by brunoais** [comment]
Do you have the undo plugin turned on?

**Comment by abetis** [comment]
Hmmm... plugins again...
With the undo plugin it looks better. Why don't you enable that plugin by default?

BTW: the plugin records all the buttons pressed, including switch to code view and fullscreen, which is a bit strange, but as long as it handles the undo properly, I'm ok with it.

**Comment by brunoais** [comment]
> Why don't you enable that plugin by default?

Ask @samclarke
