### ISSUE TITLE
Missing feature for plugin development: access to bbcode handler array

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#680]
I'm trying to implement the inline code as a plugin.
Using the format plugin as an example.
I can override the default command called by the toolbar button click, which adds the tags in WYSIWYG or source view, but I can't find a way to override the `bbcodeHandlers` array to change the code entry:
```
		// START_COMMAND: Code
		code: {
			tags: {
				code: null
			},
			isInline: false,
			allowedChildren: ['#', '#newline'],
			format: '[code]{0}[/code]',
			html: '<code>{0}</code>'
		},
		// END_COMMAND

```

How it can be done on initialization of the plugin?
The `sceditor.formats` is null even in the `signalReady` callback.

**Comment by brunoais** [comment]
Why not use the public API?

**Comment by abetis** [comment]
As I wrote:
> The `sceditor.formats` is null even in the `signalReady` callback.

Is there another API?
The documentation says:

> signalReady
> Called after the editor is created.
>

**Comment by abetis** [comment]
I think I found the way... don't know why I saw `formats` as null, now its ok:
```
			sceditor.formats.bbcode.set('c', {
				tags: {
					c: null
				},
				isInline: true,
				allowedChildren: ['#'],
				format: '[c]{0}[/c]',
				html: '<code class="inline">{0}</code>'
			});

```
