### ISSUE TITLE
Copy&Paste in Chrome

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#708]
Hi guys,
Maybe someone knows how to override/solve that problem:
I had to switch to Chrome due to an extension that exist only for that browser, used FireFox before that and never had a problem with Copy&Paste.

Go to sceditor.com, copy the first line, paste it on the second line. Switch to <Source> view and see the result:
In FireFox:
```
Give it a try! :)
Give it a try! :)
```

In Chrome:
```
Give it a try! :)
[color=#111111][size=2][font=Verdana, Arial, Helvetica, sans-serif]Give it a try! [/font][/size][/color]:)
```

Any ideas?
Thanks.

**Comment by abetis** [comment]
Anyone?

Chrome is the most used browser and no one faced that problem yet?

**Comment by SayidJarrah** [comment]
I have the same issue. Could you please advise some workaround how to avoid this?
Thanks.

**Comment by abetis** [comment]
Very sad that @samclarke abandoned that great project...

I came to a point where I need a fix for that problem. Any hint, direction or a place in the code where I should look at will definitely help!

I've searched the repository a bit and came to issue #32 from 2012 where Sam mentioned "enablePasteFiltering" option, that suppose to do exactly what I need.
In the code there is only the configuration option left without any functionality that does the actual work.
Anyone know if there was a change that removed that logic?
How do I search in the history of the repository to see where that code might have been added and removed?

**Comment by abetis** [comment]
Small update:
Since the #32 issue refers to plaintext plugin and looking in the code it looks like it could help, I've loaded and enabled that plugin.
Now paste is done in plaintext, which is better than having tons of color and font tags in the bbcode.
It strips everything, including formatting such as bold and URLs, which is not good...

**Comment by DamithaPerera** [comment]
When i used pasted option i get  **Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead** .... any suggestion how to avoid this ?
