### ISSUE TITLE
undo plugin forces a focus

### ISSUE THREAD

**Issue by jdarwood007** [samclarke/SCEditor#711]
The undo plugin seems to cause the browser to focus on the textarea field unexpectedly.  This causes undesired results where the browser "jumps" to the textarea field on the page.

I traced this back:
at SCEditor.base.sourceEditorCaret (jquery.sceditor.bbcode.js?beta21:5751)
at SCEditor.base.signalReady (undo.js?beta21:138)
at callHandlers (jquery.sceditor.bbcode.js?beta21:2874)
at PluginManager.base.call (jquery.sceditor.bbcode.js?beta21:2893)
at loaded (jquery.sceditor.bbcode.js?beta21:4399)

The undo plugin calls this
```
				'caret': this.sourceEditorCaret(),
```

This call does this:
```
		base.sourceEditorCaret = function (position) {
			sourceEditor.focus();
```

This calls the focus() on the textarea element which causes the browser to jump to it.
Our original report: https://github.com/SimpleMachines/SMF2.1/issues/4749

**Comment by brunoais** [comment]
How did you activate the undo plugin while not interacting with the editor? 
What steps did you go through to achieve that?

**Comment by jdarwood007** [comment]
The editor is fully loaded on page load and the plugins and other options are loaded when the sceditor object is setup.  So the undo plugin is passed into sceditor.create under the options.plugins array.

**Comment by brunoais** [comment]
When did the jump to the editor happen?
Did you have to press any of the required keys (see above)?

**Comment by jdarwood007** [comment]
It jumps upon page load.  No keys are pressed.

**Comment by brunoais** [comment]
Ok, got it. The bug does exist. I guess the extension was not adapted when SCE's code changed.
I expect to fix that the weekend next week... Hope so...
