### ISSUE TITLE
Copy-Paste text with bbcode bug

### ISSUE THREAD

**Issue by SayidJarrah** [samclarke/SCEditor#717]
Hello, 
Could you please fix follow bug:
1) go to sceditor.com
2) write two words
3) apply bold to second word
4) copy all text
5) paste copied text
Expected result: first word without bold style, second one - with
Actual result: both words are bold
Reproduced not only for bold tag, the same story with italic, underlined and so on.

**Comment by brunoais** [comment]
https://github.com/samclarke/SCEditor/issues/708
