### ISSUE TITLE
[Add to README] Get Contents of Editor

### ISSUE THREAD

**Issue by SamJakob** [samclarke/SCEditor#725]
I think it's probably a good idea to mention that if you want to get the contents of the editor, you can use:

```javascript
let element = document.getElementById("editor");
sceditor.instance(element).val();
```

This also tells people who skim the documentation *cough* how to get the editor instance.

**Comment by brunoais** [comment]
Feel free to make a PR with such changes

**Comment by spreedated** [comment]
@SamJakob Thank you for opening this issue and resolving my problem, since I couldn't find any example of this simple usage.

This should really be in the basic 'usage' part on the site.

**Comment by NBTX** [comment]
Yeah, no problem! :)
I'll submit that PR when I get back home actually.

**Comment by SamJakob** [comment]
Yeah, no problem! :)
I'll submit that PR when I get back home actually.
