### ISSUE TITLE
Alignment removes line breaks

### ISSUE THREAD

**Issue by lucaslg** [samclarke/SCEditor#728]
Hi !

I noticed an issue with alignment removing line break.

Here are the steps to reproduce:
Using the www.sceditor.com example:
```
Give it a try! :)

[color=#ff00]Red text and [/color][color=#3399ff]blue text![/color]

[ul]
[li]A simple list[/li]
[li]With two items[/li]
[/ul]

Just type [b]:[/b]) and it will be converted into :) as you type.
```
1) Select all the text and select any alignement.
2) Go to source. The following displays (I centered the text):
```
[center]Give it a try! :)[/center]
[center][color=#ff00]Red text and [/color][color=#3399ff]blue text![/color][/center]
[center][ul]
[li]A simple list[/li]
[li]With two items[/li]
[/ul]
[/center]
[center]Just type [b]:[/b]) and it will be converted into :) as you type.[/center]
```
3) Go back to preview. Line breaks are gone.

These reproduction steps seems to point to an issue with the conversion from html text to bbcode as the line breaks are gone from the source at step 2 after applying the alignement.

Anybody encountered this issue ? Maybe found a fix ?
Would greatly appreciate the help :) 
Cheers !

**Comment by dclause** [comment]
Linking a PR with a working solution for help :)
https://github.com/samclarke/SCEditor/pull/729

**Comment by lucaslg** [comment]
Tested & approved #729 👍 many thanks :)
