### ISSUE TITLE
base.updateOriginal() still fires on submit when instance was destroyed

### ISSUE THREAD

**Issue by BurninLeo** [samclarke/SCEditor#735]
I have a setting where a `<textarea>` allows for formatted HTML code (jquery.sceditor.xhtml.js) or not, which can be switched using a dropdown. The dropdown either creates a (single) SCEditor instance (with `autoUpdate: true`) or destroys it.

(1) the instance is created
(2) text is entered into the SCEditor's WYSIWYG input area
(3) then the instance is destroyed, leaving the original `<textarea>` with the appropriate HTML code

-- fine so far --

(4) other content is written into the `<textarea>`
(5) the form is submitted
(6) now the "other content" from (4) is replaced by the HTML code from (3)

I added a `console.log()` to the definition of `base.updateOriginal()` and it seems that the method is invoked even though the instance was destroyed. According to the source code, destroying the instance should have removed the event handler, but something seems not to work in my case.

Browser: Firefox v66.0.3
SCEditor v2.1.3

**Comment by brunoais** [comment]
Looks like a bug. I'll try to reproduce when I can but I'm not having much time on my hands....

**Comment by BurninLeo** [comment]
When I replace ...

			if (form) {
				off(form, 'reset', handleFormReset);
				off(form, 'submit', base.updateOriginal);
			}

... in the `base.destroy()` definition with

			if (form) {
				off(form, 'reset', handleFormReset);
				off(form, 'submit', base.updateOriginal, EVENT_CAPTURE);
			}

(added the EVENT_CAPTURE that is also used in `initEvents()`), then it works for me.

**Comment by brunoais** [comment]
Thanks @BurninLeo. That's probably the bug. Will keep this open to have the bug fixed.
