### ISSUE TITLE
More of a complaint but where is boilerplate?

### ISSUE THREAD

**Issue by markmorris** [samclarke/SCEditor#737]
Ive been wanted to add a custom BB code literally identicle to HR but the documentation isnt good enough and theres no boilder plate anywhere for this kind of stuff. 

Can you provide an example of how to add a custom BB code with an icon in toolbar.

**Comment by brunoais** [comment]
You could check how the `[hr]` itself is made:
https://github.com/samclarke/SCEditor/blob/master/src/formats/bbcode.js#L165
+
https://github.com/samclarke/SCEditor/blob/master/src/formats/bbcode.js#L537

The docs tells you the API. That source code should be enough to show you how to make use of the API.

**Comment by abetis** [comment]
Don't have time for explanations.
You can see an example in my code here:
https://github.com/abetis/SCEditor/commit/46a03eb4d13d0c77176ddef3f159721c613b7432

**Comment by brunoais** [comment]
I don't have time now to do it for you.

**Comment by markmorris** [comment]
@abetis Thanks for the help i can see easilly how its done. Shame you need to re-compile just to add a new tag. i honestly assumed it would be a couple lines of code.

**Comment by brunoais** [comment]
@markmorris What do you mean "recompile"?

**Comment by markmorris** [comment]
Well in albetis example he edits folders that i dont have in the release version, im assuming thats after grunt has done its business.

**Comment by brunoais** [comment]
That is not using the API nor editing the final code, that's why you need to run Grunt again.
However, if you edit the final code the browser reads, the changes are almost immediate

**Comment by markmorris** [comment]
@abetis Ive copied the code over to my live version (exactly as is) and i cant get the buttons to show on wysiwyg no matter what i do.

**Comment by abetis** [comment]
do you have the "products" plugin and all other related configuration in place?

**Comment by markmorris** [comment]
I do indeed, literally everything you did i copied perfectly. Triple checked, something so simple is taking hours man, ive never been so stumped.

**Comment by abetis** [comment]
Check in browser loaded code to see if the plugin was loaded.
I sometimes add some printouts in the code to debug it.
Annoying, but that's what you get for free :)

**Comment by markmorris** [comment]
Well ive included the projects.js file into the page which is loading fine, it just looks like sceditor is not doing anything with it.

**Comment by markmorris** [comment]
Can someone point me to the code which should display the button, i literally just want to add a button to the tool bar that displays a [pb] in the editor, thats it. I should be able to do this in a few lines of code, dont understand why nothing is working....

**Comment by markmorris** [comment]
Okay i have limited the plugin to just the below...

According to the docs this is enough for me to be able to add a button to the toolbar, but when i add 'product' to toolbar is does nothing.

```
(function (sceditor) {
    'use strict';
    sceditor.plugins.products = function () {
        var base = this;
        base.init = function () {
            var opts = this.opts;
            console.log('loaded');

            // Enable for BBCode only
            if (opts.format && opts.format !== 'bbcode') {
                return;
            }

            // Add new commands
            sceditor.command.set('product', {
                function() {
                    //this.insert('');
                },
                txtExec: function() {
                    //this.insert('');
                },
                tooltip: 'Insert Product'
            });

            console.log('finished');
        };
    };
})(sceditor);
```

**Comment by markmorris** [comment]
So it works like so...

```

**Comment by brunoais** [comment]
Did you see this?
https://www.sceditor.com/documentation/custom-commands/
