### ISSUE TITLE
Auto Expand Not Working

### ISSUE THREAD

**Issue by markmorris** [samclarke/SCEditor#741]
Auto Expand does not work at all for me, if theres existing content it will produce a scroll bar and if i hit enter a few times the box doesnt resize, although when i set the autoExpand to true, the style does change so i know its triggered at least.

**Comment by brunoais** [comment]
It works on my test. Can you get a better description of what you are trying and which version you are using?

**Comment by markmorris** [comment]
Screenshot of my editor.
![Capture](https://user-images.githubusercontent.com/7857906/61231662-77ad0600-a724-11e9-9e26-a119936f90e5.PNG)

```
    // Replace the textarea with SCEditor
    let textarea = document.getElementById('sdLine');
    sceditor.create(textarea, {
        plugins: 'products, undo',
        format: 'bbcode',
        style: rootURL+'js/addons/sceditor-musicline/development/themes/content/default.css',
        toolbar: 'bold,italic,underline,superscript|pagebreak,columnbreak|source',
        autoExpand: true,
        autoUpdate: true
    });
```

**Comment by markmorris** [comment]
Updated to the latest version and started working, i literally had the version before it.
