### ISSUE TITLE
XSS Injection

### ISSUE THREAD

**Issue by overcrash66** [samclarke/SCEditor#753]
**Expected Behaviour:** No XSS injection allowed.
**Actual Behaviour:** XSS injection.
_Steps to Reproduce Issue:_
1-Click insert an image.
2-On the link copy past this:
`<img src="http://url.to.file.which/not.exist" onerror=alert(document.cookie);>`
3-Click insert.

**Comment by q2apro** [comment]
Tip: Use for instance htmLawed serverside to clean your HTML: https://github.com/kesar/HTMLawed

Never trust user input!
