### ISSUE TITLE
Randomly adds font or color tags

### ISSUE THREAD

**Issue by paullaffitte** [samclarke/SCEditor#764]
**Way to reproduce:**
Open the editor, paste text copied from anywhere

**Actual behavior:**
It adds bbcode tags for font color and size automatically. In my case it added `[color=#24292e][size=2][font=-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"]`. After several copy and paste (and it can happens very often), the content become a real mess full of undesired bbcode tags.

**Expected behavior:**
The editor shouldn't add tags if not explicitly asked.

**Comment by abetis** [comment]
The text you copied includes those properties, so that's what is being pasted...
If you want to paste as a plain text, there is a "plaintext" plugin:
https://www.sceditor.com/documentation/plugins/plaintext/

**Comment by frandominguez03** [comment]
If you want to paste a text without all the formatting, you can paste it using CTRL+SHIFT+V. That way you'll paste it without any formatting and without its corresponding bbcodes.
