### ISSUE TITLE
Change iframe src to "about:blank" so that nvda can read the content inside iframe

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [samclarke/SCEditor#778]
NVDA ignore iframe with src="javascript:false"

DEMO:
https://jsbin.com/tatogufiva/edit?html,output

NVDA Issue: 
https://github.com/nvaccess/nvda/issues/11902

**Comment by live627** [comment]
this  needs closed now that https://github.com/samclarke/SCEditor/pull/779 is merged.
