### ISSUE TITLE
Editor content changed event

### ISSUE THREAD

**Issue by smalos** [samclarke/SCEditor#785]
I'd like to get notified whenever the editor content has changed (text content, formatting, text pasted etc.). But navigation keys must be excluded (eg. arrow keys).

This is my code so far. I'm just wondering if there's not an easier way to achieve this or if there's anything else that I should handle.

```
	var textarea = document.getElementById("div_editor");
	var sc = sceditor.instance(textarea);

	sc.bind('valuechanged keypress paste pasteraw', function(e) {

		if ((e.type == 'valuechanged' && e.eventPhase > 1 && e.charCode === undefined) ||
			e.charCode == 9 /*Tab*/ || 
			e.charCode == 33 /*PageUp*/ || 
			e.charCode == 34 /*PageDown*/ ||
			(e.charCode > 36 && e.charCode < 41)  /*Arrow Keys*/)  {
			    return;
		} 

		console.log('Editor content changed!');
			
	});
```

**Comment by smalos** [comment]
I noticed that the events do not fire when a toolbar item has been clicked (e.g. Bold button). Is there a specific event handler?

**Comment by samclarke** [comment]
The `input` event would probably do what you want. Will need to add support for it to bind().
