### ISSUE TITLE
编辑器复制粘贴上一行的内容出现无限嵌套的font标签

### ISSUE THREAD

**Issue by ooijopk** [samclarke/SCEditor#786]
![image](https://user-images.githubusercontent.com/73647670/103354977-fc8e0a00-4ae7-11eb-88c6-ba0ea2892531.png)
编辑器里面复制上一行的内容，不停的复制上一行的内容，font标签会越来越多，这是一个bug吗？

**Comment by live627** [comment]
duplicate of https://github.com/samclarke/SCEditor/issues/764
