### ISSUE TITLE
XHTML format 'cssText' error 

### ISSUE THREAD

**Issue by karolinaskiba** [samclarke/SCEditor#795]
Hi, 
Fill and format the text content,
copy and paste it,
then opening the code editor generates the error 'cssText' - I attach a screenshot.
![tempsnip](https://user-images.githubusercontent.com/26883005/108193869-378ae200-7116-11eb-8c80-2c3aa813ca49.png)

**Comment by samclarke** [comment]
Thanks for reporting! Should be fixed in the next release.
