### ISSUE TITLE
Custom BBCode will not work if called after sceditor.create()

### ISSUE THREAD

**Issue by tomdav999** [samclarke/SCEditor#796]
Not technically a bug but would be helpful if the custom bbcode documentation emphasized that sceditor.formats.bbcode.set() must be called BEFORE sceditor.create() to work properly.  I spent a bit of time trying to figure out why my custom bbcode would convert bbcode to HTML, but not vice-versa.  I eventually figured out that sceditor.create() performs some bbcode caching operations, so any custom bbcode must added in advance.

**Comment by samclarke** [comment]
Thanks for reporting! Added a note to the docs.
