### ISSUE TITLE
Clicking bulleted or numbered list icons return "undefined" in source view

### ISSUE THREAD

**Issue by tomdav999** [samclarke/SCEditor#797]
**Describe the bug**
When editor is in source bbcode view, the bulleted list and numbered list icons replace highlighted content with "undefined"

**To Reproduce**
1. Go to https://www.sceditor.com/
2. Click on <> to go to bbcode source view
3. Select first line "Give it a try! :)"
4. Click bullet list icon

**Expected behavior**
[ul]
[li]Give it a try! :)[/li]
[/ul]

**Actual behavior**
[ul]
[li]undefined[/li]
[/ul]

Tested on:
 - Windows 10 (Firefox, Chrome)
 - Android (Chrome)

**Comment by samclarke** [comment]
Thanks for reporting! This should be fixed in the next release.

Until then they can be fixed by updating the list commands:

```javascript
sceditor.command.set('bulletlist', {
	txtExec: function (caller, selected) {
		this.insertText('[ul]\n[li]' + selected.split(/\r?\n/).join('[/li]\n[li]') + '[/li]\n[/ul]');
	}
});

sceditor.command.set('orderedlist', {
	txtExec: function (caller, selected) {
		this.insertText('[ol]\n[li]' + selected.split(/\r?\n/).join('[/li]\n[li]') + '[/li]\n[/ol]');
	}
});
```
