### ISSUE TITLE
Matching multiple attrs is very broken

### ISSUE THREAD

**Issue by live627** [samclarke/SCEditor#809]
**Describe the bug**
This bug is two-fold:
- fI the value of the attr does not match one of the strings in the array,  `convertBBCode` is not set to false`. This behavior is reproduced by reversing the order of the attrs below.
- If the final attr matches successfully, `convertBBCode` becomes `true` without considering that otter attrs may fail. The  below example reproduces this one.
None of the built in formats have multiple attrs and is why this is a seemingly hidden bug. (The most egregious ones seem to always hide in plain sight!)

I have a fix for this but still need to write a bunch of tests to prove that  it works with all permutations.

**To Reproduce**

			sceditor.formats.bbcode.set(
				'abbr', {
					tags: {
						abbr: {
							title: ['test'],
							test: null
						}
					},
					format: function (element, content) {
						return '[abbr=' + element.getAttribute('title') + ']' + content + '[/abbr]';
					},
					html: '<abbr title="{defaultattr}">{0}</abbr>'
				}
			);
			var textarea = document.getElementById('example');
			sceditor.create(textarea, {
				format: 'bbcode',
				icons: 'monocons',
				style: '../minified/themes/content/default.min.css'
			});
			var parser = sceditor.instance(document.getElementById('example'));
			console.log(parser.toBBCode(
				'<abbr title="attrs.defaultattr" test="value">content</abbr>'
			));

**Expected output**
`content`

**Actual output**
`[abbr=attrs.defaultattr]content[/abbr]`

**Comment by samclarke** [comment]
The current attributes matching is OR not AND so that is the expected output as the `test` attribute matches.

It might be worth having the ability to do AND matching though.
