### ISSUE TITLE
Question when creating custom command

### ISSUE THREAD

**Issue by juancamunoz** [samclarke/SCEditor#814]
I'm creating a custom command to highlight a portion of text. This is the code
```

sceditor.formats.bbcode.set('highlight', {
          tags: {
            span: null
          },
          allowsEmpty: false,
          isSelfClosing: false,
          format: '[highlight]{0}[/highlight]',
          html: '<span style="background:yellow">{0}</span>',
          quoteType: sceditor.BBCodeParser.QuoteType.auto
        });
```

       `sceditor.command.set('sung', {
          exec: function() {
            var editor = this;
            editor.wysiwygEditorInsertHtml('<span style="background:yellow">', '</span>')
          },
          txtExec: ['[highlight]', '[/highlight]'],
          tooltip: 'Subraya de amarillo un texto'
        });`

But I don't know how to do it like the [b] or [center] tag, I want the highlight to be deleted when the user clicks again in the highlight toolbar option, if the selected text is highlighted. Is it possible?

Thanks!!

**Comment by live627** [comment]
I have left some code that should do what you want at https://github.com/samclarke/SCEditor/issues/747#issuecomment-781241741
