### ISSUE TITLE
Upload images first (automatically). Prevent base64 encoded images.

### ISSUE THREAD

**Issue by Doidel** [samclarke/SCEditor#819]
I'm trying to do something relatively simple. When an image is added (through pasting, drag/drop, etc.) I don't want it to be inserted as a base64 encoded image, instead, I would want to upload it first to a CDN and then, when the upload is done, insert the image tag with the CDN URL.

I've browsed around for the docs and issues to find how I should go about this but wasn't quite successful. Thanks for your help!

**Comment by samclarke** [comment]
The [Drag and Drop plugin](https://www.sceditor.com/documentation/plugins/dragdrop/) should do what you want, it handles both pasted and dropped images. When an image is pasted / dropped it calls a handler with the image data letting you do whatever you want with it.

There's a [demo of it here](https://www.sceditor.com/posts/drag-drop-upload-demo/) using the Imgur API.

**Comment by Doidel** [comment]
Oh wow that's a perfect answer! Thanks, awesome. Case closed.
