### ISSUE TITLE
Recent commits causes problem copy pasting text

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#839]
Hi, I grabbed the latest commits and it seems to solve the problems of multiple [code] when pasting text. But there is a new issue that removes all the line breaks of pasted text.

To reproduce:
1. Type multiple lines.
2. Select the lines and copy them to clipboard.
3. Try pasting them below.
4. All lines should have been pasted merged into one line.

**Comment by samclarke** [comment]
Thanks for reporting!

It looks to be caused by the editor incorrectly setting the value for the `text/plain` type in the clipboard. I've added a fix (ab83735). It still needs some more testing but should fix the issue.

**Comment by timint** [comment]
Thank you for attending to this so quickly.

I want to take the opportunity and thank you for all your hard work. I have great respect in all the work you make on this editor. And I am delighted to hear you are back knowing you went off the radar for a couple of years. Hope we get to keep seeing you around. :)

I will try the fix and get back to you if there is any issues with it.
