### ISSUE TITLE
Line break in the editor deleted

### ISSUE THREAD

**Issue by lecomteb27** [samclarke/SCEditor#841]
Hi,

Desktop Microsoft Edge - V91.0.864.67

### Steps to reproduce the problem

1. Use SCEditor and send the data to the database
2. Retrieve data from the database and display it in SCEditor

I have put all the information about the examples and the SCEditor configuration in a screenshot after this help ticket. If you can tell me how to solve this problem, @samclarke. I thank you in advance, because I did not find any information about my problem.

Best regards

![Capture d’écran 2021-07-15 115131](https://user-images.githubusercontent.com/33637996/125776758-8102da1b-4a6d-4c45-8c04-d9b808109861.png)

![Capture d’écran 2021-07-15 115205](https://user-images.githubusercontent.com/33637996/125776763-f8599fcc-e700-4472-a716-f1c85f1dee92.png)

![Capture d’écran 2021-07-15 125314](https://user-images.githubusercontent.com/33637996/125776765-c2dde203-477b-40d8-8d66-6e6780558814.png)

**Comment by samclarke** [comment]
That looks like a bug. What's the contents of the textarea before SCEditor is loaded?

**Comment by lecomteb27** [comment]
> That looks like a bug. What's the contents of the textarea before SCEditor is loaded?

Yes, you are right, it was a problem, but it doesn't concern the editor. I created a code that totally compresses the page, it removes the line breaks automatically, now it's ok.

**Comment by samclarke** [comment]
Glad it's fixed. As it's not an issue with the editor I'll close this.
