### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by tjemberoot** [samclarke/SCEditor#860]
I'm using sceditor inside modal (multiple modal for add , edit the post) if i click 1 attempt to add / edit post it cache older content , but if i close the modal and open again the content correctly show. (my json show correctly data response for all click i done) . So basically content in textarea is correctly show when not using sceditor

**Comment by live627** [comment]
Do you reload the editor every time you open the popup? Also try setting [`autoUpdate: true`](https://www.sceditor.com/documentation/options/#autoupdate-a-id-autoupdate-a)

**Comment by tjemberoot** [comment]
done sir, i got solution
` ...
dataType: "JSON",
        success: function(data)
        {
$('.sceditor-container').remove();
            $('[name="idnews"]').val(data.id); 
            ....
            var editvar = document.getElementById('newsediting');
            sceditor.create(editvar, {
......
`
