### ISSUE TITLE
Code tag add extra left tags.

### ISSUE THREAD

**Issue by berkut1** [samclarke/SCEditor#869]
If you use `[code][/code]` and then switch to the source mode, SCEditor will add `[left][/left]` tag. Any time when you switch to the source mode it will continue to add it.

Example:

https://jsbin.com/bapebajufa/1/edit?html,js,output

P.S Probably the bug came in 3.1.0, because as I can see on https://www.sceditor.com/ with 3.0 it works correctly.

**Comment by berkut1** [comment]
The problem, that SCEditor take css style and convert it into the tag.
In "~sceditor/minified/themes/content/default.min.css"
```
code {
    display: block;
    background: #f1f1f1;
    white-space: pre;
    padding: 1em;
    text-align: left;  <------ this
    margin: .25em 0;
    direction: ltr
}
```
A temporary solution:
`text-align: unset;`

**Comment by samclarke** [comment]
Thanks for reporting!

This is a bug with 3.1.0. Previous versions didn't match block styles on code tags but during updates to the matching the code that skipped them was accidentally removed.
