### ISSUE TITLE
Custom link tag using <a> conflict with [url]

### ISSUE THREAD

**Issue by nguillaumin** [samclarke/SCEditor#872]
Hi,

I have defined a custom tag `[game]`, which creates a link to a game on my website based on the ID: `[game=123]Game name[/game]` results in `<a href="/games/123" data-game-id="123">Game name</a>`.

```javascript
{
  tags: {
    a: {
      'data-game-id': null
    },
  },
  allowedChildren: [],
  allowEmpty: false,
  isSelfClosing: false,
  format: function(elm, content) {
    return '[game=' + elm.getAttribute('data-game-id') + ']' + content + '[/game]';
  },
  html: function(token, attrs, content) {
    return '<a href="/games/' + attrs.defaultattr + '" data-game-id="' + attrs.defaultattr + '">' + content + '</a>';
  }
}
```

That works fine. However when I view the source in the editor, it results in: `[game=123][url=/games/123]]Game name[/url][/game]`. I suspect becaues the default `[url]` tag matches the `<a href="">` pattern.

There is a similar question in #177 however the answer given does not really help (or I don't understand it).

Is there a way to prevent this and have the source preserved as `[game=123]Game name[/game]` without the `[url]` inside?

Thanks,

Nico

**Comment by live627** [comment]
I believe your suspicion is correct. I see three ways to fix this:
1. remove the `href` from your `game` tag
2. rename the `href` in the `url` tag
3. remove the `url` tag

**Comment by nguillaumin** [comment]
Thanks. How would I do 2 or 3? Can built-in tags be re-configured / removed?

Although the issue is that I need both... I wonder why this happens in the first place, if the `<a>` tag is processed by the `[url]` or `[game]` tag, why would it get processed a second time?

**Comment by samclarke** [comment]
The `[url]` BBCode is matching as it doesn't know it shouldn't match game links. Tags and styles can be matched by multiple BBCodes as there is currently no way to tell if a BBCode should block others from matching or not..

The easiest solution is to either remove the `[url]` BBCode or if you need to keep it, update the `[url]` to skip the game links. Something like:

```js
sceditor.formats.bbcode.set('url', {
  format: function (element, content) {
    // Ignore game links
    if (element.hasAttribute('data-game-id')) {
      return content;
    }
   
    var url = sceditor.dom.attr(element, 'href');

    // make sure this link is not an e-mail,
    // if it is return e-mail BBCode
    if (url.substr(0, 7) === 'mailto:') {
      return '[email="' + url.substr(7) + '"]' +
        content + '[/email]';
    }

    return '[url=' + url + ']' + content + '[/url]';
  }
});
```

Demo: https://jsbin.com/baziramoba/1/edit?html,js,output

**Comment by nguillaumin** [comment]
Thanks a lot, it works!
