### ISSUE TITLE
Can the editor support set line-height, or how can it support line-height

### ISSUE THREAD

**Issue by liangle2020** [samclarke/SCEditor#874]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samclarke** [comment]
Do you want to change the CSS `line-height` property? If so, that can be done via the [`css()`](https://www.sceditor.com/api/sceditor/css/#css) method or by modifying the stylesheet specified in the [`style`](https://www.sceditor.com/documentation/options/#style-a-id-style-a) option.
