### ISSUE TITLE
Add SCEditor in Blazor WASM and a strange behavior

### ISSUE THREAD

**Issue by nimadir** [samclarke/SCEditor#875]
0

I want to use SCEditor in my blazor page.

For example I create a new blazor WASM project and I did these steps:

According to documentation I add this codes and references to index.html:
https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/default.min.css https://cdn.jsdelivr.net/npm/sceditor@3/minified/sceditor.min.js https://cdn.jsdelivr.net/npm/sceditor@3/minified/formats/bbcode.min.js

```
window.InitEditor = () => {
        var textarea = document.getElementById('myTextArea');
        sceditor.create(textarea, {
            format: 'bbcode',
            style: 'https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/content/default.min.css'
        });
    }
```
Add a textarea in counter page:

`<textarea id="myTextArea" style="width:100%; height:200px;"></textarea>`
add follow code to code section of counter page:

```
protected override Task OnAfterRenderAsync(bool firstRender)
{
    JsRuntime.InvokeVoidAsync("InitEditor");
    return base.OnAfterRenderAsync(firstRender);
}
```
Now I run the project and I see this editor:
![1](https://user-images.githubusercontent.com/19870383/148640541-4e0b415c-ee44-40ac-aafb-d7af5e97b169.png)

then I click on fetch data menu and I see this:
![2](https://user-images.githubusercontent.com/19870383/148640545-bbe1c339-6541-457a-8360-3f873a358172.png)

Surprisingly, editor has shown in fetch data page. if I click on counter page again I see this:
![3](https://user-images.githubusercontent.com/19870383/148640546-2faf9b9f-5665-4961-b985-f834ef5c2e0b.png)

There are 2 Editors O-O. and if I click on this menus then editors are increasing...

How can I solve this problem?

**Comment by samclarke** [comment]
It looks like `InitEditor` is being called repeatedly. Looking at the method `OnAfterRenderAsync(bool firstRender)` it appears to provide a flag if it's the first render. Could that be used to call it only once? Something like:

```csharp
protected override Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        JsRuntime.InvokeVoidAsync("InitEditor");
    }

    return base.OnAfterRenderAsync(firstRender);
}
```

**Comment by nimadir** [comment]
Thank. Yes I can write that if.The editor show one time, But editor will show on fetch data page again. I don't have any text area in that page.

**Comment by samclarke** [comment]
It looks like Razor is acting as a SPA and not re-loading the page each time. If that's the case, it could be the editor is left over from a previous page and the DOM not cleaned up.

Does calling [destroy()](https://www.sceditor.com/api/sceditor/destroy/#destroy) from the Blazor components [dispose()](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#synchronous-idisposable) method help? Something like:

```js
window.DestroyEditor = () => {
    var textarea = document.getElementById('myTextArea');
    sceditor.instance(textarea).destroy();
}
```

Then in the Razor component, implement IDisposable:

```csharp
protected void Dispose()
{
    JsRuntime.InvokeVoidAsync("DestroyEditor");
}
```

**Comment by nimadir** [comment]
I'll test it tomorrow and comment the answer.Thanks

**Comment by nimadir** [comment]
I should mention that blazor wasm is a SPA framework. I changed the code and editor is shown once but in both page again. When I changed the pages by click on their menu an empty textarea is shown in counter page
![Untitled](https://user-images.githubusercontent.com/19870383/148671511-142a4340-f1c9-420b-88bd-a55ff6aa00d2.png)
![Untitled2](https://user-images.githubusercontent.com/19870383/148671512-5342f0c2-9569-4fbe-bd21-66208c8b34e0.png)
.

**Comment by nimadir** [comment]
It solved: [https://stackoverflow.com/questions/70631085/when-i-add-sceditor-to-my-blazor-project-the-editor-keeps-appearing-in-strange](url)
