### ISSUE TITLE
Table + Heading (h2/h3/h4) creates extra lines and an empty tr style=""

### ISSUE THREAD

**Issue by nichierichetti** [samclarke/SCEditor#876]
Dear all,

I have a bug to report:
Basically whenever a heading (h2/h3/h4) is used inside of a table, two problems happen:
- Extra new lines are added between each element
- an empty style attribute is added on the tr element of the table

The scenarios are two:
- A. Switching between code and WYSIWYG mode
- B. By previewing the content

Test content (easiest):
`[table][tr][td][h2]Title[/h2]Content[/td][/tr][/table]`

I have also tried to disable all other javascript contents, etc.. - but it seems not to work at all. 
Also, the forum is on a forum hosting that shares the same editor javascripts - but despite this, on some forum it's fine, on some i get both scenarios problem (A+B), in some only one scenario

**Comment by samclarke** [comment]
The `[h1]`, `[h2]`, etc. tags are not default BBCodes. Do you know what JS is being used to add them or do you have a demo of the issue?

**Comment by nichierichetti** [comment]
The problem is based on the same website of issue #877 so you can relate to the info I sent you via email

Thanks!

**Comment by samclarke** [comment]
Closing this as it should hopefully now be fixed.

It looks to have been cause by the custom heading BBCodes missing the `isInline: false` property which was causing the editor not handle the newlines created by the block level elements correctly.
