### ISSUE TITLE
editor.insert could not insert custom html tags

### ISSUE THREAD

**Issue by fedot199614** [samclarke/SCEditor#901]
i try to insert custom html tag `<lottie-player>Test</lottie-player>` but it inserts only text - Test.
olso i try wysiwygEditorInsertHtml - but no effect.
text area are emty - `<p><br></p>`
![image](https://user-images.githubusercontent.com/33698132/200404002-1c9d6e88-492f-4dbe-bb6a-ef43615535bb.png)

**Comment by samclarke** [comment]
Thanks for reporting!

This is caused by the filtering done to prevent XSS. Before HTML is inserted into the editor it's filtered using DOMPurify. It looks like DOMPurify removes all custom elements by default.

Fixing this will probably require a new configuration option to specify allowed custom elements.

**Comment by fedot199614** [comment]
thanks, i add in my SCEditor build new options allowedTags, allowedAttributes
and make something like this
`	/**
	 * Sanitize HTML to avoid XSS
	 *
	 * @param {string} html
	 * @return {string} html
	 * @private
	 */
	function sanitize(html) {

		const allowedTags = ['iframe'].concat(options.allowedTags);
		const allowedAttr = ['allowfullscreen', 'frameborder', 'target']
			.concat(options.allowedAttributes);

		return domPurify.sanitize(html, {
			ADD_TAGS: allowedTags,
			ADD_ATTR: allowedAttr
		});
	};`
and it's works

**Comment by samclarke** [comment]
That looks great. If you want to make a PR, it can be merged into the code base.

**Comment by codertushar** [comment]
@samclarke @fedot199614 Please review my PR: https://github.com/samclarke/SCEditor/pull/925
I need this ASAP.
