### ISSUE TITLE
Formatting retained when pasting into code blocks

### ISSUE THREAD

**Issue by live627** [samclarke/SCEditor#915]
Pasting HTML formatted syntax highlighted code into the editor within the code block brings in  the formatting and outputs color bbcodes amongst the text.

1. Copy syntax highlighted code from browser
2. Passe into code block in WYSIWYG mode

![Screenshot 2023-01-26 at 13-02-29 {{ n b b _b }}yesyes](https://user-images.githubusercontent.com/431799/214949485-37b0da24-b23c-428d-b090-bfc11390010e.png)
![Screenshot 2023-01-26 at 14-41-32 {{ n b b _b }}yesyes](https://user-images.githubusercontent.com/431799/214961554-4c5db04b-5c92-4fd5-9614-f834c8b635fe.png)

**Example code**
```
// Text strings
$txt['tp-blockinbox'] = 'Inbox:';
```

**HTML Source**
```
<span class="phpcode"><span style="color: #000000"><span style="color: #FF8000">// Text strings<br></span><span style="color: #0000BB"><pre style="display: inline;">	</pre></span><span style="color: #0000BB">$txt</span><span style="color: #007700">[</span><span style="color: #DD0000">'tp-blockinbox'</span><span style="color: #007700">] = </span><span style="color: #DD0000">'Inbox:'</span><span style="color: #007700">;</span></span></span>
```

**Expected Output**
```
// Text strings
$txt['tp-blockinbox'] = 'Inbox:';
```

**Actual Output**
```
[color=#000000][color=#ff8000]// Text strings[/color][/color]
[color=#000000][color=#0000bb]$txt[/color][color=#007700][[/color][color=#dd0000]'tp-blockinbox'[/color][color=#007700]] = [/color][color=#dd0000]'Inbox:'[/color][color=#007700];[/color][/color]
```

**Comment by samclarke** [comment]
Thanks for reporting!

The formatting being retained on paste is a bug but when the code tag is converted into BBCode any formatting should be removed and the output should match the expected output. 

Do you get the same output with the editor on [sceditor.com](https://www.sceditor.com/)?

**Comment by live627** [comment]
Yes.

1. On first paste:
![Screenshot 2023-01-26 at 19-34-30 SCEditor](https://user-images.githubusercontent.com/431799/215001862-fc0c3615-d192-4c1d-9b41-053bbc0e71d0.png)

2. Switch to source  view
![Screenshot 2023-01-26 at 19-32-21 SCEditor](https://user-images.githubusercontent.com/431799/215001906-844fb896-3da3-4bcb-98dc-8f0695193ed3.png)

3. Go back to WYSIWYG mode
![Screenshot 2023-01-26 at 19-33-28 SCEditor](https://user-images.githubusercontent.com/431799/215001889-a114eb55-13c2-47e6-8104-8685491b9c34.png)

**Comment by samclarke** [comment]
Ah got it, the special handling of code tags is only excluding styles on inline tags, not blocks. This triggers the issue:

```html
<code><code><div style="color:#ff0000">test</div><br></code></code>
```

but this doesn't:

```html
<code><code><span style="color:#ff0000">test</span><br></code></code>
```
