### ISSUE TITLE
Missing language strings

### ISSUE THREAD

**Issue by wintstar** [samclarke/SCEditor#918]
**Language strings missing**

v3.1.1

These strings are translated only in Czech

https://github.com/samclarke/SCEditor/blob/d249647c20df0604bab510f9629e5b168431b0aa/languages/cs.js#L65-L66

![image](https://user-images.githubusercontent.com/2753863/215348320-a94dd58d-31eb-44d1-81ab-d0b327bf195a.png)

for german
```
		'Add indent': 'Ebene hinzufügen',
		'Remove one indent': 'Eine Ebene entfernen',
```

**Comment by samclarke** [comment]
Thanks for reporting! It looks like those strings have been missed from the translation template.

If you want to make a PR to update the German translation that would be great. Alternatively, I can create one if you're happy for your translations to be included.

**Comment by wintstar** [comment]
I am not a great master when it comes to Github. Please do the PR.

**Comment by samclarke** [comment]
Created. Thanks again for reporting and translating!
