### ISSUE TITLE
background-image: url("../images/icons/editor_sprite.png") leads to strange path

### ISSUE THREAD

**Issue by SkybuckFlying** [samclarke/SCEditor#926]
Example site where text editor icons are missing, not loaded correctly:
http://www.skybuck.org/PascalCoin/Forum/index.php?topic=3548.0

File: Themes\default\css\jquery.sceditor.css
Code: background-image: url("../images/icons/editor_sprite.png");
Leads to debugger showing strange path constructed:
GET
	http://www.skybuck.org/PascalCoin/Forum/public/sites/www.skybuck.org/PascalCoin/Forum/Themes/default/images/icons/editor_sprite.png

**Comment by samclarke** [comment]
This looks to be an issue with SMF configuration and not with the editor.

I'm not very familiar with SMF. My best guess would be has the themes `jquery.sceditor.css` been modified? The SMF default theme's value for the background is: `background-image: url("../images/icons/editor_sprite.png");`, does yours match that?

Beyond that, I can't really help, you would be better off asking on the SMF forums.

**Comment by SkybuckFlying** [comment]
The solution was to disable: "minimize javascript and css" somewhere in SMF settings ! ;)
