### ISSUE TITLE
Smiley at the beginning + emoticonsCompat: true -> Uncaught TypeError: prev is null

### ISSUE THREAD

**Issue by MioVisman** [samclarke/SCEditor#933]
Firefox 108
SCEditor 3.2.0  `format: bbcode`
The options are set `emoticonsCompat: true`

1. An empty edit box (either immediately after page load (not 100% sure here) or after clearing Ctrl+A and Delete)
2. I insert a smilie through the smilies panel
   
![sm1](https://user-images.githubusercontent.com/5917956/230275742-65cb4678-8188-4995-801e-5f4a7f84132e.png)

3. I'm typing

![sm2](https://user-images.githubusercontent.com/5917956/230276876-77514c5c-4b2a-48aa-b152-988428e306c6.png)
Recurring `TypeError: prev is null`

![sm3](https://user-images.githubusercontent.com/5917956/230277458-fba1b602-5c00-4c73-a8fa-32f8a018691c.png)

**Comment by samclarke** [comment]
Thanks for reporting! I've created a PR to fix this (#935).
