### ISSUE TITLE
bbcode.isPreFormatted

### ISSUE THREAD

**Issue by MioVisman** [samclarke/SCEditor#936]
What is this
`
!bbcode.isPreFormatted &&
`
https://github.com/samclarke/SCEditor/blob/c368667ad5d50306eadfcc19e91072b5cf9ffb0b/src/formats/bbcode.js#L1779

**Comment by samclarke** [comment]
It's an alias for [skipLastLineBreak](https://www.sceditor.com/documentation/custom-bbcodes/#skiplastlinebreak-a-id-skiplastlinebreak-a) which exists only for backwards compatibility. Ideally it would be removed but that requires a breaking change to do so, so we're stuck with it until then.

I've added a note to the [v4 propsal](https://github.com/samclarke/SCEditor/discussions/849#isPreFormatted) so it doesn't get forgotten about next time there is a breaking change.
