### ISSUE TITLE
 图标样式问题 Icon style issue

### ISSUE THREAD

**Issue by lianlianlianlianlianlian** [samclarke/SCEditor#948]
I want the effect on the official website

as follows

![image](https://github.com/samclarke/SCEditor/assets/36120596/5ad3a387-20bb-4a34-bfc4-7aaaa1d1551d)

But after I installed it
Display as follows

![image](https://github.com/samclarke/SCEditor/assets/36120596/edf41576-f9da-4c92-a18a-54df429697eb)

I like the black style on the official website. Can you tell me how to change it?

My website is using Centos7.9 PHP 8.0, and I'm not sure if it's related to PHP

**Comment by samclarke** [comment]
Sorry for the delay!

They are the monocons icon set. To use them you need to include the monocons.js file, if using jsdelivr it would be:

```html
<script src="https://cdn.jsdelivr.net/npm/sceditor@3.2.0/minified/icons/monocons.js"></script>
```

And then set the [icons](https://www.sceditor.com/documentation/options/#icons-a-id-icons-a) option to `'monocons'`, for example:
```js
sceditor.create(document.getElementById('example'), {
	format: 'bbcode',
	width: '80%',
	icons: 'monocons',
	style: 'https://cdn.jsdelivr.net/npm/sceditor@latest/minified/themes/content/default.min.css'
});
```
